#!/usr/bin/env python3
"""
make_signal_ersp_block.py - the "how a recording becomes an ERSP cube" block of the s1 tab.

    python make_signal_ersp_block.py            print it
    python make_signal_ersp_block.py --insert   splice it into analysis_status.html

EVERY NUMBER IS READ FROM config.py AT BUILD TIME. None of them is typed into this file,
so the page cannot drift from the pipeline: change cfg.min_post_s and the next --insert
says the new value. The recent-changes table carries its own dates because those are
history, not settings.

It explains; it does not duplicate. make_s1_tab.py already writes the per-patient chain,
the parameter table and the audit-driven status. This block is the part those cannot be:
what each step is for, and what it COSTS - which is the question the 2026-09-30 notch
finding made unavoidable.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "functions"))
import config as cfg  # noqa: E402

SITE = Path(os.environ.get("LF_SITE_DIR") or (Path.home() / "lorafanda.github.io")) / "analysis_status.html"
# the 03_ERSP tree's audit once it exists (2026-09-30), the frozen 04_* one until then
AUDIT = HERE / "outputs" / cfg.ERSP_TREE / "audit_140.tsv"
if not AUDIT.exists():
    AUDIT = HERE / "outputs" / "04_ersp_LM" / "audit_140.tsv"
BEGIN = "<!-- BEGIN signal ersp, generated by make_signal_ersp_block.py - do not hand-edit -->"
END = "<!-- END signal ersp -->"
ANCHOR = '<h3'          # the first h3 of the s1 tab: the block goes above it

FS_DS = 1000.0          # every channel is resampled to this before the STFT


def g(name, default=None):
    return getattr(cfg, name, default)


def build() -> str:
    df = FS_DS / g("nfft")
    hop_ms = (g("nperseg") - g("noverlap")) / FS_DS * 1000.0
    ovl = 100.0 * g("noverlap") / g("nperseg")
    n_freq = int(g("fmax") / df) + 1
    pB, pS, pP = g("proportions")
    nb = g("n_time_bins")
    hg = g("hg_band")
    bw = g("baseline_calc_w") or g("baseline_w")

    # what actually ran, rather than what the config would do
    ran = ""
    if AUDIT.exists():
        a = pd.read_csv(AUDIT, sep="\t")
        meth = sorted(set(a.notch_method.dropna().astype(str)))
        scope = sorted(set(a.notch_scope.dropna().astype(str)))
        ran = (f"{len(a)} patients in the last audit &middot; notch "
               f"{' / '.join(meth)}, {' / '.join(scope)}")

    # (step, what, the setting that governs it, what it costs)
    steps = [
        ("1", "Crop to the task",
         "per patient, <code>crop_cfg</code>",
         "nothing - it only removes recording outside the block."),
        ("2", "Re-reference to white matter",
         f"<code>reref_type = {g('reref_type')}</code>",
         "the WM channels themselves leave the data. Computed on the whole cropped "
         "recording <i>before</i> notching and epoching, so every trial sees the same "
         "reference."),
        ("3", "Drop channels that are not cortex",
         "the manual bad list, non-neural names, microwires, Unknown-labelled contacts",
         "these never reach a cube. The audit's <code>removed_by_bad_list</code> and "
         "<code>removed_not_in_bad_list</code> say which, per patient."),
        ("4", "Notch the mains, per block and per shaft",
         f"spectrum interpolation, z &ge; {g('notch_peak_z_thresh')}, "
         f"half-width measured then capped at <b>&plusmn;{g('notch_interp_max_hw_hz')} Hz</b>, "
         f"{g('notch_interp_phase')} phase",
         "<b>real signal, and this is the step that can cost the most.</b> See below."),
        ("5", "Resample to 1 kHz",
         "<code>resample_poly</code>",
         "only the anti-alias filter of the resampling; no high-pass, no low-pass, "
         "no detrending anywhere in the chain."),
        ("6", "Cut trials, and keep the good ones",
         f"scored correct &middot; stimulus &ge; {g('min_stim_s')} s &middot; "
         f"post-offset {g('min_post_s')}&ndash;{g('max_post_s')} s &middot; "
         f"Tukey fences {g('iqr_k')} &times; IQR",
         "the slowest and the fastest responses. The audit's "
         "<code>&lt;cond&gt;_trials_in</code> and <code>_trials_used</code> count both ends."),
        ("7", "Spectrogram",
         f"Hann, nperseg {g('nperseg')}, noverlap {g('noverlap')} ({ovl:.0f}%), "
         f"nfft {g('nfft')} &rarr; <b>{df:.3f} Hz</b> bins, <b>{hop_ms:.0f} ms</b> hop, "
         f"kept to {g('fmax'):.0f} Hz = <b>{n_freq}</b> bins",
         "resolution: the window's main lobe is about &plusmn;15 Hz, which is why a line "
         "left standing still reaches rows well away from it."),
        ("8", "Baseline, per trial and per frequency",
         f"mean dB over <b>{bw[0]} to {bw[1]} s</b> before onset",
         "every cube is dB <i>relative to that trial's own pre-stimulus window</i>, so a "
         "channel's absolute amplitude is already divided out before clustering sees it."),
        ("9", "Time-normalise",
         f"proportions {pB:g} / {pS:g} / {pP:g} (base / stimulus / post) "
         f"&rarr; <b>{nb}</b> bins",
         "absolute latency. A trial's stimulus and response periods are each stretched to "
         "a fixed share of the axis, so trials of different length can be averaged - and "
         "no time on the figure is a real second."),
        ("10", "Average over trials",
         f"one <b>{n_freq} &times; {nb}</b> cube per electrode &times; condition",
         "the single-trial variance. Odd and even halves are written beside every cube, "
         "which is what the stage-02 gate measures its noise from."),
    ]
    rows = "".join(
        f"<tr><td style='text-align:right;color:var(--muted)'>{n}</td>"
        f"<td><b>{what}</b></td><td>{setting}</td><td>{cost}</td></tr>"
        for n, what, setting, cost in steps)

    return f"""{BEGIN}
    <h3 id="s1chain2">How a recording becomes an ERSP cube</h3>
    <p class="sechint">Ten steps, in order, with the setting that governs each and what
      it costs. {ran}. Every number here is read from <code>config.py</code> when the page
      is built, so it cannot drift from the pipeline.</p>
    <table class="sum" style="margin:6px 0 14px">
      <tr><th></th><th>step</th><th>setting</th><th>what it costs</th></tr>
      {rows}
    </table>

    <div class="method" style="border-left:4px solid var(--s1)">
      <h4 style="margin:0 0 6px">The notch is the step that can cost real signal</h4>
      <p style="margin:0 0 8px">Every other step either removes something that is not
        cortex, or changes units. The notch removes a band of the spectrum outright and
        replaces it with the flanks' RMS at random phase &mdash; so the only question that
        matters is <b>how wide</b>.</p>
      <p style="margin:0 0 8px">A mains harmonic is a line: <code>peak_geometry</code>
        measures the real one and caps its own estimate at 5 Hz. Past that, a widening
        loop grows the band by 1 Hz whenever energy remains in the ring just outside it.
        At high frequencies that residue is often ordinary broadband brain, so the loop
        kept widening until it hit its ceiling.</p>
      <p style="margin:0 0 8px"><b>Until 2026-09-30 that ceiling was 12 Hz</b> &mdash; a
        24 Hz hole per harmonic. High gamma is
        {hg[0]:.0f}&ndash;{hg[1]:.0f} Hz and the 100 and 150 Hz notches sit inside it, so
        on the worst shafts this deleted a large part of the band every HFA feature is
        built from:</p>
      <table class="sum" style="margin:0 0 8px">
        <tr><th>patient</th><th>widest half-width</th><th>bands that never converged</th>
            <th>worst shaft lost</th><th>at the new &plusmn;3 Hz</th></tr>
        <tr><td>PAT_3975</td><td>12.0 Hz</td><td>0 %</td>
            <td><b>36.0 Hz = 45 % of high gamma</b></td><td>11 %</td></tr>
        <tr><td>EL033</td><td>12.0 Hz</td><td><b>30 %</b></td>
            <td><b>29.0 Hz = 36 %</b></td><td>11 %</td></tr>
        <tr><td>PAT_6704</td><td>11.0 Hz</td><td>0 %</td><td>20.0 Hz = 25 %</td><td>11 %</td></tr>
        <tr><td>PAT_6854</td><td>4.5 Hz</td><td>0 %</td><td>8.5 Hz = 11 %</td><td>11 %</td></tr>
        <tr><td colspan="5" style="color:var(--muted)">the other 28 patients: 0&ndash;9 %,
            median half-width 0.5&ndash;1.5 Hz &mdash; a line being removed properly</td></tr>
      </table>
      <p style="margin:0">"Never converged" means the loop used all 12 of its passes
        rather than stopping: the band was still growing when it ran out.
        <b>The cohort on the site was built with the 12 Hz ceiling</b>; the
        &plusmn;{g('notch_interp_max_hw_hz')} Hz cap reaches the cubes only after 140 is
        re-run, and a new cohort cache after that.</p>
    </div>

    <h4 id="s1recent">What changed, and when</h4>
    <table class="sum" style="margin:6px 0 0">
      <tr><th>date</th><th>change</th><th>why</th></tr>
      <tr><td>2026-09-24</td><td>notch is spectrum interpolation, per shaft, for
        <b>every</b> patient</td><td>the method had been decided per patient for 14 of 31;
        the rest got one decision for a whole montage, which both over- and under-notched.</td></tr>
      <tr><td>2026-09-24</td><td>baseline window stated explicitly as
        {bw[0]} to {bw[1]} s</td><td>it was already the default every cube was made with;
        now config and 140 both say so.</td></tr>
      <tr><td>2026-09-26</td><td>post-offset floor {g('min_post_s')} s, was 1.0 s</td>
        <td>1 s was too aggressive - it alone had cost 760 trials.</td></tr>
      <tr><td>2026-09-28</td><td>per-patient half-width <i>floors</i>
        (<code>notch_interp_min_hw_hz</code>)</td><td>EL037 and EL045 kept a trial-locked
        350 Hz stripe that the time-averaged PSD test could not see.</td></tr>
      <tr><td>2026-09-29</td><td>per-harmonic notch logging off</td><td>one line per
        harmonic per shaft per condition buried the summary; every line is still a row in
        <code>&lt;pid&gt;_notch_audit.tsv</code>.</td></tr>
      <tr><td>2026-09-29</td><td>each HG row carries its trial z</td><td>the same number
        the rejection rule compares against, so figure and rule cannot disagree.</td></tr>
      <tr><td>2026-09-30</td><td><b>half-width ceiling 12 &rarr;
        {g('notch_interp_max_hw_hz')} Hz</b></td><td>the table above.</td></tr>
    </table>
    <div class="runid">generated by <code>make_signal_ersp_block.py</code> from
      <code>config.py</code> and <code>audit_140.tsv</code></div>
{END}
"""


def main(insert: bool) -> None:
    block = build()
    if not insert:
        print(block)
        return
    s = SITE.read_text(encoding="utf-8")
    if BEGIN in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + block.strip() + s[j:]
        print("replaced the existing block")
    else:
        k = s.index('<section id="s1"')
        a = s.index(ANCHOR, k)
        a = s.rindex("\n", 0, a) + 1
        s = s[:a] + block + s[a:]
        print("inserted above the first heading of the s1 tab")
    SITE.write_text(s, encoding="utf-8")
    print("->", SITE)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    main(ap.parse_args().insert)
