#!/usr/bin/env python3
"""The "01 · Signal → ERSP" tab of analysis_status.html - outline form, numbers from the run.

    python make_s1_tab.py            (write the block, copy the figures, change nothing else)
    python make_s1_tab.py --insert   (splice it into the site)

Same mechanism as make_mm_tab.py / make_microepi_tab.py: the <section id="s1"> block is
replaced between BEGIN/END markers (the first run replaces the hand-written section), a
curated set of figures is copied into outputs/_status_png/ under stable names (the site
loads images from raw.githubusercontent, so a figure shows only once that folder is
committed), and nothing else in the file is touched. Re-run after every 140 rerun: the
run-status bullets and the per-patient table are read from outputs/04_ersp_LM/audit_140.tsv
(141_audit_140.py - run that first) at build time.

The sub-tab roles of the tab (Answer / Evidence / Method / Open / History) are the h3 ids
below, mapped in 02_FBM_Clustering/make_site_ui.py ROLES["s1"]; change both together.
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import shutil
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "outputs" / "_status_png"
AUDIT = ROOT / "outputs" / "04_ersp_LM" / "audit_140.tsv"
QC = ROOT / "outputs" / "04_ersp_LM"
SITE = Path("C:/Users/fanda/lorafanda.github.io/analysis_status.html")
FIGROOT = "01_FBM_Analysis/outputs/_status_png"
DOCS = "01_FBM_Analysis/outputs/preprocessing_docs"

B_SEC = "<!-- BEGIN s1 tab, generated by make_s1_tab.py - do not hand-edit -->"
E_SEC = "<!-- END s1 tab -->"
STAGE2 = "<!-- ============ STAGE 02 ============ -->"

EX = "PAT_6704"          # the example patient of the current run's figures
EXCH = "THD1"            # transverse temporal (Heschl) - the audio responder
FIGS = {   # stable name -> source (None: kept as already committed under _status_png)
    "s1_example_ersp.png":  QC / EX / "LM" / "ERSP" / "audio" / f"{EX}_audio_WM_ERSP_{EXCH}_TN.png",
    "s1_example_hg.png":    QC / EX / "LM" / "HG" / "audio" / f"{EX}_audio_WM_HGtrials_{EXCH}.png",
    "s1_trials_iqr.png":    QC / EX / "LM" / "Report" / f"{EX}_audio_iqr_postDur_QC.png",
    "s1_psd_raw.png":       QC / EX / "LM" / "PSD_raw" / "audio" / "PSD" / "psd_by_shaft.png",
    "s1_psd_clean.png":     QC / EX / "LM" / "PSD_clean" / "audio" / "PSD" / "psd_by_shaft.png",
}
MAX_FIG_MB = 4.5          # the repo's pre-commit guard refuses files above 5 MB

_e = html.escape


def li(*items: str) -> str:
    return "".join(f"<li>{x}</li>" for x in items)


def ul(*items: str, cls: str = "") -> str:
    return f'<ul{(" class=" + chr(34) + cls + chr(34)) if cls else ""}>{li(*items)}</ul>'


def fig(name: str, num: str, title: str, bullets: list[str], runid: str, *, sub: str = FIGROOT) -> str:
    return (f'<figure><div class="cap"><div class="fignum">{num}</div><h4>{title}</h4>'
            f'{ul(*bullets)}<div class="runid">{runid}</div></div>'
            f'<div class="imgwrap"><img data-fig="{sub}/{name}" alt="{_e(title)}"></div></figure>')


# ---------------------------------------------------------------------------------------
def read_audit() -> pd.DataFrame | None:
    if not AUDIT.exists():
        return None
    return pd.read_csv(AUDIT, sep="\t", dtype=str).fillna("")


def ref_short(r) -> str:
    ref = r["reference"]
    if ref.startswith("per-grid CAR"):
        return "grid CAR"
    if ref.startswith("whole-recording CAR"):
        return "whole CAR"
    if r["system"] == "MicroEPI":
        return f"WM {r['wm_n']} (WM kept as data)"
    return f"WM {r['wm_n']}"


def status_short(r) -> str:
    s = r["status"]
    if r["log"] == "NOT RUN":
        return "not run"
    return "ok" if s == "ok" else s.split(":")[0]


def patient_table(a: pd.DataFrame) -> str:
    head = ("<tr><th>patient</th><th>sys</th><th>run</th><th>crop (s)</th><th>ref</th><th>bad</th><th>unk</th>"
            "<th>notch</th><th>trials a / p / r</th><th>cubes / cond</th><th>status</th></tr>")
    rows = []
    for _, r in a.iterrows():
        tr = " / ".join(str(r[f"{c}_trials_used"] or "–") for c in ("audio", "picture", "reading"))
        cubes = "/".join(str(r[f"{c}_cubes"] or "0") for c in ("audio", "picture", "reading"))
        run = r["run_start"][5:] if r["run_start"] else "–"
        rows.append(f"<tr><td><b>{_e(r['patient'])}</b></td><td>{_e(r['system'])}</td><td>{_e(run)}</td>"
                    f"<td>{_e(r['crop_cfg'].replace(' s', '') or '–')}</td><td>{_e(ref_short(r))}</td>"
                    f"<td>{_e(r['bad_listed_n'])}</td><td>{_e(r['unknown_dropped'] or '0')}</td>"
                    f"<td>{_e(r['notch_method'])}{' · shaft' if r['notch_scope'] == 'per shaft' else ''}</td>"
                    f"<td>{_e(tr)}</td><td>{_e(cubes)}</td><td>{_e(status_short(r))}</td></tr>")
    return f'<table class="sum" style="margin:8px 0;font-size:12px">{head}{"".join(rows)}</table>'


def run_status(a: pd.DataFrame | None) -> str:
    if a is None:
        return ul("audit table missing: run <code>141_audit_140.py</code>")
    ran = a[a["log"] != "NOT RUN"]
    ok = ran[ran["status"] == "ok"]
    n_cubes = sum(max(int(r[f"{c}_cubes"] or 0) for c in ("audio", "picture", "reading")) for _, r in ran.iterrows())
    not_run = [p for p in a[a["log"] == "NOT RUN"]["patient"]]
    bad = [f"{r['patient']}: {r['status']}" for _, r in ran.iterrows() if r["status"] != "ok"]
    days = sorted({r["run_start"][:10] for _, r in ran.iterrows() if r["run_start"]})
    shapes = sorted({s for s in ran["shapes"] if s})
    return ul(
        f"patients in <code>cfg.patient_ids</code>: <b>{len(a)}</b> · run: <b>{len(ran)}</b> ({', '.join(days)}) · ok: <b>{len(ok)}</b>"
        + (f" · not run: {', '.join(not_run)}" if not_run else ""),
        "producer: <code>01_FBM_Analysis/140_ersp_pipeline.py --patient &lt;id&gt;</code> (one process per patient; notebook 140 = same code)",
        f"contacts with cubes: <b>{n_cubes}</b> · cube shape: {', '.join(shapes) or '–'} (freq × warped time) · fmax <b>400 Hz</b>",
        "errors: " + ("; ".join(_e(b) for b in bad) if bad else "none"),
        "table: <code>outputs/04_ersp_LM/audit_140.tsv</code> / <code>.md</code> (<code>141_audit_140.py</code>) - one row per patient, 103 columns",
    )


# ---------------------------------------------------------------------------------------
def build(a: pd.DataFrame | None) -> str:
    today = dt.date.today().isoformat()
    S = []
    S.append(B_SEC)
    S.append('  <section id="s1">')
    S.append('    <div class="eyebrow" style="color:var(--s1)">Stage 01</div>')
    S.append('    <h2 class="title">Signal → ERSP</h2>')
    S.append('    <p class="lead">Raw sEEG → one <b>ERSP cube</b> per electrode × condition (103 freq × 300 warped time bins, dB re baseline). '
             'Producer: <code>140_ersp_pipeline.py</code>. Tree: <code>04_ersp_LM_RAWONLY</code>. '
             f'Outline form, {today}; numbers from <code>audit_140.tsv</code>.</p>')

    # ---- status -------------------------------------------------------------------
    S.append('    <h3 id="s1-status">Run status</h3>')
    S.append('    <div class="method">' + run_status(a) + '</div>')
    S.append('    <h4>Since the 2026-09-18 run</h4>')
    S.append('    ' + ul(
        "<b>2026-09-22</b> · PAT_6704, PAT_6854 rerun with the MicroEPI reference fix (bad-listed contacts had been averaged in, <code>bad_channels_for_ref=[]</code>): PAT_6704 21 WM contacts used, AD8 FOD5 HAD7 IAD1 left out · PAT_6854 38 used, IAD1 left out · cube counts unchanged (134 / 178 per condition)",
        "<b>2026-09-22</b> · EL043 rerun on the two recordings joined (<code>RAW_CONCAT</code>, file 2 at 3773.5 s, window 1810–4650 s; picture triggers of 18 June by <code>el043_build_picture_triggers.py</code>, the bad 17 June table parked in prep0-bad): audio 18 / picture 25 / reading 14 trials, 74 cubes per condition (18 Sep run: picture 0 trials in crop → aborted before reading)",
        "<b>2026-09-21</b> · PAT_6953 run: 147 cubes per condition, 30 WM references, 5 Unknown drops (AD12 FOD1 TLD2 TLD4 TLD5)",
        "<b>2026-09-22</b> · stale-cube sweep by mtime over all 31 patient folders: no cube, half or CLEAN png older than its run",
        "<b>open</b> · 137 contacts / 10 patients analysed with no anatomy link (recording vs TSV spelling: aI_R / alR, MFG-L / MFG, pIns / pl, PlaT_L / PlanTL, OFA / OFAD): 20 are WM 100 %, 14 Unknown → alias table in 140 + reruns, decision pending",
    ))

    # ---- chain ----------------------------------------------------------------------
    S.append('    <h3 id="s1-chain">Chain — per patient, in order</h3>')
    S.append('    <div class="method">' + ul(
        "<b>1 · load</b>: Bern <code>.h5</code> (1024 Hz; <code>RAW_CONCAT</code> joins split recordings: EL051, EL043) · HUG <code>.TRC</code> (2048 Hz) · MicroEPI <code>.mat</code> export (macros + micros, <code>lf_micromacro</code>)",
        "<b>2 · channels out</b>: aux by name (EKG, EMG, Chin, photo, X / E families) · MicroEPI micros: raw pass-through (G-04 / G-06 microwires bad-listed) · EL: crop to preset <code>time_range</code> · EL043: hemisphere suffix stripped · grid keep-prefixes (EL044 P / p / T, PAT_3415) · <b>Unknown</b>: tissueLabel empty / NaN / “Unknown…” → dropped · <b>bad</b>: <code>cfg.bad_channels_manual</code> (+ Lookup <code>isOut</code>) → no cube",
        "<b>3 · reference</b> (one per patient, before any trial): <b>WM mean</b> of ≥ 3 contacts; WM rule = tissueWeights_1 = 1.0 ∧ first token <code>wm-</code> (BIDS electrodes TSV; Lookup workbook for EL051 / EL052); bad list excluded; <code>WM_NOT_REFERENCE</code> = PAT_6704 THD1 / THD3 / THD4 (WM by anatomy, analysed as data) · EL / HUG: WM contacts skipped as data · MicroEPI: macros only, WM contacts kept as data · EL044: per-grid CAR (P 6, Pa 55, T 48, postP 15) · EL052: whole-recording CAR (104 ch, 24 bad out; no WM contact recorded)",
        "<b>4 · notch</b> (per condition block, ±10 s pad): candidates 50 Hz + harmonics ≤ 400 (EL048 also 16.667 Hz comb) · test z ≥ 3 vs local PSD · <code>iir</code>: Q from peak sharpness · <code>interp</code> (EL036 / 037 / 040 / 043 / 045 / 048, all MicroEPI): spectrum interpolation, random phase, band widened ≤ ±12 Hz · per shaft for the same list · audit: <code>Report/&lt;pid&gt;_notch_audit.tsv</code>, <code>_unexplained_peaks.tsv</code>",
        "<b>5 · trials</b> (<code>lf_trials.collect_trials</code>, prep0 tables; byte-identical duplicates skipped): resp_accuracy ∈ {correct, valid, 1} · stimulus ≥ 0.5 s · post 1–10 s · IQR k = 1.5 on post duration · report <code>Report/&lt;pid&gt;_IQR.tsv</code> + QC png per condition",
        "<b>6 · ERSP</b> (<code>lf_ersp.compute_ersp</code>, per channel): resample 1 kHz → STFT Hann nperseg 128, noverlap 108, nfft 256 (3.906 Hz bins, 20 ms hop) → dB re baseline mean (−0.6, −0.1 s) → bins ≤ <code>cfg.fmax</code> = 400 Hz kept: <b>103 bins, last 398.4 Hz</b> (2026-09-18; was 129 / 500) → time-warp TN: stimulus onset→offset = bins 0–149, offset→<code>trial_end</code> = 150–299 (<code>proportions (0, .5, .5)</code>, bin 150 = GO) → mean over kept trials · NaN fill nearest (cube only) · halves: odd / even trials, no fill",
        "<b>7 · per-trial rejection inside the average</b>: off for every patient (configured for PAT_6684 only, now out of the dataset)",
        "<b>8 · HG QC</b>: 70–150 Hz Butterworth → Hilbert → 25 ms smoothing → baseline z · raster per channel, trials sorted by stimulus duration, excluded trials drawn last, reason-tagged (accuracy / duration / IQR / power)",
        "<b>9 · write</b>: cube <code>.npy</code> + halves + CLEAN png (RAWONLY tree) · QC ERSP + HG png for every channel incl. bad (QC tree) · PSD raw / clean · <code>wm_reref_report.tsv</code> row · log",
    ) + '</div>')
    S.append('    <h4>Downstream (stage 02, not here)</h4>')
    S.append('    ' + ul(
        "gate: <code>prop_above_pos ≥ 0.02</code> ∨ <code>prop_below_neg ≥ 0.04</code> (thr +2.2 / −3.0 dB) in ≥ 1 condition; per electrode, not per condition",
        "concatenation along time: 3 cubes → 103 × 900 (<code>concat_rawds</code>: 15 bands × 30 bins per block; <code>concat_hg</code>: 70–150 Hz mean per bin) · cache <code>concat_source_v*</code>",
        "constants moved to 103 / 398.4375 Hz on 2026-09-18 in stages 02–05 (<code>lf_dataset</code>, <code>lf_features</code>, <code>lf_clustering</code>, <code>lf_concat</code>, <code>lf_pool</code>, <code>lf_rt</code>, <code>lf_classify</code>, notebooks 240–242 / 212 / 232)",
    ))
    S.append(fig("P2_signal_conditioning.png", "FIG P.2", "Steps 3–4 · reference and notch (documentation figure)",
                 ["A: contact pair before / after WM re-reference (simulated) · B: PSD with mains harmonics · C: scheme per patient type",
                  "documentation of the method, 2026-08-26 (v4); schemes unchanged except EL052 whole CAR (09-17) and the MicroEPI bad-list fix (09-21)"],
                 "<code>make_preprocessing_figures.py</code>", sub=DOCS))
    S.append(fig("P3_one_trial_to_ersp.png", "FIG P.3", "Step 6 · one trial → one ERSP (documentation figure)",
                 ["A: raw trial, baseline window marked · B: spectrogram dB · C: after baseline subtraction · D: averaged TN cube (EL033 aH_L11 audio, v4)",
                  "axis then 0–500 Hz / 129 bins; now 0–400 Hz / 103 bins, same 3.906 Hz step"],
                 "<code>make_preprocessing_figures.py</code>, 2026-08-26", sub=DOCS))
    S.append(fig("P4_time_normalisation.png", "FIG P.4", "Step 6b · time normalisation (documentation figure)",
                 ["fast vs slow trial onto the same 300-bin axis · bin = proportion, not latency · bin 150 = stimulus offset in every trial",
                  "anything that moves <code>trial_end</code> rescales bins 150–299 (fixation-cross correction, EL033 / PAT_3965)"],
                 "<code>make_preprocessing_figures.py</code>, 2026-08-26", sub=DOCS))

    # ---- parameters -----------------------------------------------------------------
    S.append('    <h3 id="s1-params">Parameters — per patient</h3>')
    S.append('    ' + ul(
        "columns: crop = EL / HUG preset <code>time_range</code> (MicroEPI: preset) · ref = reference route, WM contact count · bad = <code>bad_channels_manual</code> entries · unk = Unknown-parcellation drops · notch = method (· shaft = per-shaft) · trials = used per condition (after accuracy / duration / IQR) · cubes = per condition",
        "source: <code>audit_140.tsv</code>; a rerun changes this table on the next <code>make_s1_tab.py --insert</code>",
    ))
    S.append('    ' + (patient_table(a) if a is not None else "<p>audit table missing</p>"))

    # ---- outputs -------------------------------------------------------------------
    S.append('    <h3 id="s1-outputs">Outputs — where things are</h3>')
    S.append('    <div class="method">' + ul(
        "<b>inputs</b> · raw: <code>DATARAW/&lt;cohort&gt;/&lt;pid&gt;/task_FBM/data_LM/raw/</code> (+ events log) · triggers: <code>…/prep0/&lt;pid&gt;_LM_&lt;cond&gt;__&lt;trig&gt;_&lt;date&gt;.tsv</code> (onset, onset_duration, sample, sample_offsets, trial_end, condition_name, resp_accuracy, trial_idx; <code>prep0/prep0-bad/</code> = parked tables) · anatomy: <code>BIDS_elec/…/sub-&lt;id&gt;/ieeg/*_electrodes.tsv</code> (EL051 / EL052: <code>anatomy/raw/*Lookup*.xlsx</code>) · config: <code>functions/config.py</code> (presets, bad lists, references, notch)",
        "<b>cubes</b> · <code>outputs/04_ersp_LM_RAWONLY/&lt;pid&gt;/LM/ERSP_matrix/&lt;cond&gt;/&lt;pid&gt;_&lt;cond&gt;_&lt;WM|CAR&gt;_ERSP_&lt;ch&gt;_TN.npy</code> (103 × 300 float) · <code>ERSP_halves/&lt;cond&gt;/…_half1|2.npy</code> · <code>ERSP_clean/&lt;cond&gt;/*_CLEAN.png</code> · <code>wm_reref_report.tsv</code>",
        "<b>QC</b> · <code>outputs/04_ersp_LM/&lt;pid&gt;/LM/</code>: <code>ERSP/&lt;cond&gt;/*.png</code> (every channel incl. bad) · <code>HG/&lt;cond&gt;/*_HGtrials_&lt;ch&gt;.png</code> · <code>PSD_raw</code>, <code>PSD_clean</code> · <code>Report/</code>: <code>_IQR.tsv</code>, <code>_&lt;cond&gt;_iqr_postDur_QC.png</code>, <code>_montage_overview.png</code>, <code>_notch_audit.tsv</code>, <code>_unexplained_peaks.tsv</code> · <code>logs/&lt;pid&gt;_&lt;stamp&gt;.log</code>",
        "<b>audit</b> · <code>outputs/04_ersp_LM/audit_140.tsv</code>, <code>.md</code> · <b>review bundle</b> · <code>02_FBM_Clustering/outputs/250_recon/fsaverage/activity_viz/review/</code> (<code>make_lm_review_bundle.py</code>)",
        "<b>previous tree</b> · <code>04_ersp_LM_RAWONLY_old</code>, <code>04_ersp_LM_old</code> (run of 2026-08-16 + reruns; 0–500 Hz cubes) · <b>RT tree</b> · <code>05_ERSP_LM_RAWONLY_RealTime</code> (notebook 150, GO-locked, see History)",
        "<b>stale cubes</b> · 140 never clears a patient folder → after a rerun that removes channels, audit by mtime before any cohort build",
    ) + '</div>')

    # ---- checks ---------------------------------------------------------------------
    S.append('    <h3 id="s1-checks">Checks — audit and review</h3>')
    S.append('    ' + ul(
        "<b><code>141_audit_140.py</code></b> → per patient: run time, status, crop, channels in / neural / Unknown / aux, bad list, reference route + WM list, notch per condition (notched / comb left / off-comb / unexplained), trials in → IQR kept → used, cubes new vs previous tree (name diff, classified), shapes, NaN sample, QC counts, <b>name reconciliation</b> (removed by bad list / removed by no rule / listed but not recorded)",
        "<b>LM_visualizer review mode</b> (key <code>r</code>): per patient, contacts shaft by shaft, each tile = concatenated ERSP (audio | picture | reading, undistorted) · native label (tissueLabel, GM / WM / sub %) + fsaverage aparc · status (data / WM ref / bad / Unknown / aux / not recorded) · split-half r, mains-row stripe index, |dB|, HG per condition · worst-first orders · HG rasters from a local server (<code>?hg=</code>) · bundle: <code>make_lm_review_bundle.py</code> (per-patient rebuilds)",
        "<b>findings, 18–21 Sep</b>: EL043 aborted (fixed) · MicroEPI bad-in-reference (fixed) · 137 contacts without anatomy link (open) · bad-list names matching nothing: EL037 pI_R1–16 + pI_L10–13, EL040 FP-R11 PlaT_L1–3, EL034 MFG-10..12, EL030 EntG_R18, EL052 aH_L8 / 9, PAT_3415 HLG5, PAT_3780 FAP9 (open) · low trial counts: EL038 audio 8 / 39, EL043 reading 14, EL046 reading 14, EL034 audio 20, PAT_6619 audio 20 · notch leftovers: EL048 56 / 184 notched, 15–16 comb peaks left, 106 unexplained; EL035 audio 7; EL042 3 / 3 / 6; PAT_6704 4 / 4 / 3",
        "<b>photodiode</b>: EL / HUG <code>LFfunctions_PDextract.get_trigger_indexes_photodiode</code> (threshold 0.40, flip per preset, log pairing) · MicroEPI <code>lf_micromacro.extract_events_from_photodiode</code> · manual triggers: EL051 / EL052 (<code>manual_trig</code>) · PAT_6704 checked 2026-09-18: Heschl (THD1) HG locks at 0 % of the audio stimulus, stimulus durations picture 0.98–1.04 s, reading 3.48–3.55 s",
    ))
    S.append(fig("s1_example_ersp.png", "FIG 1.1", f"Example ERSP · {EX} {EXCH} audio (run 2026-09-18)",
                 ["x: warped time 0–100 %, line at 50 % = GO · y: 0–400 Hz · colour: dB re baseline, ±6",
                  "transverse temporal (Heschl): HG 70–150 Hz on from 0 %, through the stimulus and the response; low-frequency onset response at 0–5 %"],
                 f"<code>04_ersp_LM/{EX}/LM/ERSP/audio/{EX}_audio_WM_ERSP_{EXCH}_TN.png</code>"))
    S.append(fig("s1_example_hg.png", "FIG 1.2", f"HG trials · {EX} {EXCH} audio (run 2026-09-18)",
                 ["rows: trials sorted by stimulus duration, numbers = rows of the trigger table · colour: HG z · black line: onset · magenta: stimulus offset",
                  "excluded trials drawn last, red, reason-tagged: 9 response &lt; 1 s, 6 duration outlier (IQR k = 1.5) → 38 of 53 in the average"],
                 f"<code>04_ersp_LM/{EX}/LM/HG/audio/{EX}_audio_WM_HGtrials_{EXCH}.png</code>"))
    S.append(fig("s1_trials_iqr.png", "FIG 1.3", f"Trial gate · {EX} audio (run 2026-09-18)",
                 ["post-stimulus duration per trial · orange: hard limits 1–10 s · blue: IQR k = 1.5 fences · green kept 38, red dropped 15"],
                 f"<code>04_ersp_LM/{EX}/LM/Report/{EX}_audio_iqr_postDur_QC.png</code>"))
    S.append('    <figure><div class="cap"><div class="fignum">FIG 1.4</div><h4>PSD per shaft · ' + EX + ' audio block, raw vs clean (run 2026-09-18)</h4>'
             + ul("top: after reference, before notch · bottom: after notch (interp, per shaft) · dashed: 50 Hz harmonics",
                  "the notch audit TSV carries before_db / after_db / hole_hw_hz per harmonic and shaft")
             + f'<div class="runid"><code>04_ersp_LM/{EX}/LM/PSD_raw|PSD_clean/audio/PSD/psd_by_shaft.png</code></div></div>'
             + f'<div class="imgwrap"><img data-fig="{FIGROOT}/s1_psd_raw.png" alt="PSD raw" style="margin-bottom:8px"><img data-fig="{FIGROOT}/s1_psd_clean.png" alt="PSD clean"></div></figure>')

    # ---- open -----------------------------------------------------------------------
    S.append('    <h3 id="s1-open">Open — before 140 is done</h3>')
    S.append('    ' + ul(
        "decide: alias table for the 137 unlinked contacts (10 patients) → reruns EL034 EL035 EL037 EL038 EL040 EL042 EL043 EL045 EL046 PAT_6619 → <code>141_audit_140.py</code> → <code>make_lm_review_bundle.py --patients …</code>",
        "decide: bad-list names that matched nothing (spelling vs the same alias problem)",
        "decide: PAT_6953 Unknown contacts (AD12, TLD2 / 4 / 5) keep-list",
        "stale-cube audit by mtime after the reruns",
        "QC pass in review mode, patient by patient: trigger lock, reference bleed, stripes, bad channels, low trial counts (accept / not)",
        "then: commit code (fmax-400 edits, 140 script, audit, review, fixes), push page + review bundle, rebuild <code>_raw_ungated</code> → cube / ERSP bundle → clustering caches → site",
        "known: <code>pd_blocks</code> (per-block photodiode equalisation) reaches notebook 13 only, not 140 · micro / macro ERSP comparison (nb 11) never run to a saved output · microwire contacts (…m) to be removed post hoc for PAT_ patients (0 in the current tree)",
    ))

    # ---- history --------------------------------------------------------------------
    S.append('    <h3 id="s1-history">History</h3>')
    S.append('    ' + ul(
        "<b>2026-09-21 / 22</b> · MicroEPI bad-in-reference fix, PAT_6704 / PAT_6854 rerun · EL043 two recordings joined, 18 June picture triggers, rerun · PAT_6953 run · review mode + review bundle · audit script · microelectrode rule in the dataset builder = lower-case-m spelling (PAT_2868 IDM / POM are stereo contacts, back in v9)",
        "<b>2026-09-18</b> · fmax 400 Hz (crop in <code>_spectro</code>, option A; downstream constants 103 / 398.4375) · 140 as per-patient script · EL051 bad list (29) · full rerun, 31 patients, 8.1 h · trees renamed <code>_old</code>",
        "<b>2026-09-17</b> · EL052 whole-recording CAR (no WM contact recorded) · <b>09-15</b> · PAT_6684 (G-05) out of the dataset · <b>09-14</b> · G-05 on its Micromed TRC, discharge spans",
        "<b>2026-09-09</b> · per-trial rejection (broadband z / band MAD, ≤ 34 %; G-05 only) · HG raster rewritten: every excluded trial drawn, reason-tagged · <code>collect_trials</code> returns the whole table",
        "<b>2026-09-07</b> · notch per condition block, per shaft for stripe patients, spectrum interpolation, audit TSVs, unexplained peaks · figures PNG not TIFF · PSD / cube-stripe review (EL036 / 037 / 040 / 045 / 048)",
        "<b>2026-08-26</b> · chain documented, FIG P.1–P.6 (v4 numbers: 9,774 cubes → 2,959 contacts with three conditions → 1,693 gated; gate = largest narrowing, 43 %)",
        "<b>2026-08-16</b> · aux-name filter widened (EKG-, EMG-, X families were ERSP'd as cortex; 425 files deleted) · run of the previous tree",
        "<b>photodiode</b> · flip applied to the array before detection and QC figure (both paths) · <code>pd_blocks</code> equalisation, notebook 13 only",
        "<b>notebook 150, RT tree</b> (<code>05_ERSP_LM_RAWONLY_RealTime</code>): same chain, no warp, epochs in seconds centred on GO (−2.5 … +5 s), cubes <code>_RT_GO</code> (129 × nt, axes not stored) · first run 9 / 30 patients (HUG path bug <code>PAT_PAT_</code>, since fixed; 11 out-of-memory → one process per patient) · sample: PAT_6854 AGm4, HG on at GO for ~1.5 s on every trial · stage 05 reads it",
        "<b>old example figures</b> (2026-07-19, G-05 rasters 2026-09-09) replaced above by the 2026-09-18 run",
    ))
    S.append(fig("P1_pipeline_overview.png", "FIG P.1", "Chain overview with v4 survival counts (2026-08-26)",
                 ["nine steps raw → feature matrix · counts per narrowing, cohort v4"], "<code>make_preprocessing_figures.py</code>", sub=DOCS))
    S.append(fig("P5_trial_and_electrode_selection.png", "FIG P.5", "Trial filters and the stage-02 gate (v4)",
                 ["trial filters in order · supra-threshold region on a real cube · gate rule with v4 counts (post limit then 1–5 s; now 1–10 s)"],
                 "<code>make_preprocessing_figures.py</code>", sub=DOCS))
    S.append(fig("P6_cube_to_features.png", "FIG P.6", "Three cubes → feature matrices (v4)",
                 ["concatenation along time · <code>concat_hg</code> (n, 900) · <code>concat_rawds</code> (n, 1350) · v4: 1,693 electrodes, 27 patients"],
                 "<code>make_preprocessing_figures.py</code>", sub=DOCS))
    S.append(fig("realtime/RT1_run_status.png", "FIG RT.1", "Notebook 150 first run · per-patient status",
                 ["9 of 30 completed (5 MicroEPI under PAT_ folder names, 4 Bern) · 10 HUG: path bug · 11: out of memory"], "<code>05_ERSP_LM_RAWONLY_RealTime</code>"))
    S.append(fig("realtime/RT_sample_hg.png", "FIG RT.2", "GO-locked single trials · PAT_6854 AGm4 audio",
                 ["black: GO · magenta: stimulus onset (−2.2 … −4.1 s) · green: response end · HG on at GO, ~1.5 s, every trial"],
                 "<code>PAT_6854/LM/HG/audio/…_AGm4_GO.png</code>"))
    S.append(fig("realtime/RT_sample_ersp.png", "FIG RT.3", "GO-locked cube · PAT_6854 AGm4, three conditions",
                 ["HG increase locked to GO in all three · audio at GO, picture +0.3 s (+ burst near +4 s), reading +0.5 s"],
                 "<code>…_AGm4_RT_GO.npy</code>"))
    S.append('  </section>')
    S.append(E_SEC)
    return "\n".join(S) + "\n"


# ---------------------------------------------------------------------------------------
def copy_figs() -> list[str]:
    OUT.mkdir(parents=True, exist_ok=True)
    missing = []
    for name, src in FIGS.items():
        if src is None:
            if not (OUT / name).exists():
                missing.append(f"{name}  <-  (expected already in _status_png)")
            continue
        if not src.exists():
            missing.append(f"{name}  <-  {src}")
            continue
        if src.stat().st_size > MAX_FIG_MB * 1e6:
            missing.append(f"{name}  <-  {src} ({src.stat().st_size / 1e6:.1f} MB, above the commit guard)")
            continue
        shutil.copy2(src, OUT / name)
        print(f"  copied {name}  <-  {src.relative_to(ROOT)}  ({src.stat().st_size / 1e3:.0f} kB)")
    return missing


def insert(block: str) -> None:
    s = SITE.read_text(encoding="utf-8")
    if B_SEC in s and E_SEC in s:
        i, j = s.index(B_SEC), s.index(E_SEC) + len(E_SEC)
        s = s[:i] + block.rstrip("\n") + s[j:]
        print("replaced the generated block")
    else:
        i = s.index('  <section id="s1">')
        j = s.index(STAGE2, i)
        s = s[:i] + block + "\n" + s[j:]
        print("replaced the hand-written <section id=\"s1\"> block")
    SITE.write_text(s, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    a = ap.parse_args()
    missing = copy_figs()
    for m in missing:
        print("  MISSING", m)
    audit = read_audit()
    block = build(audit)
    print(f"block: {len(block):,} chars · patients in table: {0 if audit is None else len(audit)}")
    if a.insert:
        insert(block)
        print(f"wrote {SITE}")
    else:
        print("(pass --insert to splice it into the site)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
