#!/usr/bin/env python3
"""The "01 · Signal → ERSP" tab of analysis_status.html - outline form, numbers from the run.

    python make_s1_tab.py            (write the block, copy the figures, change nothing else)
    python make_s1_tab.py --insert   (splice it into the site)

Same mechanism as make_mm_tab.py / make_microepi_tab.py: the <section id="s1"> block is
replaced between BEGIN/END markers (the first run replaces the hand-written section), a
curated set of figures is copied into outputs/_status_png/ under stable names (the site
loads images from raw.githubusercontent, so a figure shows only once that folder is
committed), and nothing else in the file is touched. Re-run after every 140 rerun: the
run-status bullets and the per-patient table are read from outputs/<cfg.ERSP_TREE>/audit_140.tsv
(141_audit_140.py - run that first) at build time.

The sub-tab roles of the tab (Answer / Evidence / Method / Open / History) are the h3 ids
below, mapped in 02_FBM_Clustering/make_site_ui.py ROLES["s1"]; change both together.
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import shutil
from pathlib import Path

import pandas as pd

import sys                                                            # noqa: E402
ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "functions"))
import config as cfg                                                  # noqa: E402  (the pipeline's own settings)
sys.path.insert(0, str(ROOT))
from make_s1_procedure import procedure_html                          # noqa: E402  (the cited step table)
from make_s1_patients import patients_html                            # noqa: E402  (per patient: reference, removed contacts, findings, owed)

OUT = ROOT / "outputs" / "_status_png"
TREE = ROOT / "outputs" / cfg.ERSP_TREE          # one tree since 2026-09-30 (03_ERSP): cubes + QC figures
AUDIT = TREE / "audit_140.tsv"
# until the 03_ERSP rerun has been audited, the table is the last one of the frozen 04_* way
AUDIT_FALLBACK = ROOT / "outputs" / "04_ersp_LM" / "audit_140.tsv"
QC = TREE
SITE = Path("C:/Users/fanda/lorafanda.github.io/analysis_status.html")
FIGROOT = "01_FBM_Analysis/outputs/_status_png"
DOCS = "01_FBM_Analysis/outputs/preprocessing_docs"

B_SEC = "<!-- BEGIN s1 tab, generated by make_s1_tab.py - do not hand-edit -->"
E_SEC = "<!-- END s1 tab -->"
STAGE2 = "<!-- ============ STAGE 02 ============ -->"

EX = "PAT_6704"          # the example patient of the current run's figures
EXCH = "THD1"            # transverse temporal (Heschl) - the audio responder
FIGS = {   # stable name -> source (None: kept as already committed under _status_png)
    "s1_example_ersp.png":  QC / EX / "LM" / "ERSP" / "audio" / f"{EX}_audio_WM_ERSP_{EXCH}_TN.png",
    "s1_example_hg.png":    Path(cfg.product_dir(QC / EX / "LM", "HFA")) / "audio" / f"{EX}_audio_WM_HFAtrials_{EXCH}.png",
    "s1_trials_iqr.png":    Path(cfg.product_dir(QC / EX / "LM", "Report")) / f"{EX}_audio_iqr_postDur_QC.png",
    "s1_psd_raw.png":       QC / EX / "LM" / "PSD_raw" / "audio" / "PSD" / "psd_by_shaft.png",
    "s1_psd_clean.png":     QC / EX / "LM" / "PSD_clean" / "audio" / "PSD" / "psd_by_shaft.png",
    # the trial z-score test tree (145 -> 147 / 148), 2026-09-30
    "s1_trials_counts_z.png": ROOT / "outputs" / "04_ersp-trialtestzscore" / "_summary" / "trial_counts_and_z.png",
    "s1_trial_z_heatmap.png": ROOT / "outputs" / "04_ersp-trialtestzscore" / "_summary" / "z_heatmaps" / "EL033.png",
    # the reference-contact check of 2026-10-02: drawn once from the scratch probe, kept as committed
    "s1_ref_el048.png": None,
    "s1_ref_el033_removed.png": None,
}
MAX_FIG_MB = 4.5          # the repo's pre-commit guard refuses files above 5 MB

_e = html.escape


def li(*items: str) -> str:
    return "".join(f"<li>{x}</li>" for x in items)


def ul(*items: str, cls: str = "") -> str:
    return f'<ul{(" class=" + chr(34) + cls + chr(34)) if cls else ""}>{li(*items)}</ul>'


def fig(name: str, num: str, title: str, bullets: list[str], runid: str, *, sub: str = FIGROOT) -> str:
    return (f'<figure><div class="cap"><div class="fignum">{num}</div><h4>{title}</h4>'
            f'{ul(*bullets)}<div class="runid">{runid}</div></div>'
            f'<div class="imgwrap"><img data-fig="{sub}/{name}" alt="{_e(title)}"></div></figure>')


# ---------------------------------------------------------------------------------------
AUDIT_USED = AUDIT if AUDIT.exists() else AUDIT_FALLBACK


def read_audit() -> pd.DataFrame | None:
    if not AUDIT_USED.exists():
        return None
    return pd.read_csv(AUDIT_USED, sep="\t", dtype=str).fillna("")


def ref_short(r) -> str:
    ref = r["reference"]
    if ref.startswith("per-grid CAR"):
        return "grid CAR"
    if ref.startswith("whole-recording CAR"):
        return "whole CAR"
    if r["system"] == "MicroEPI":
        return f"WM {r['wm_n']} (WM kept as data)"
    return f"WM {r['wm_n']}"


def status_short(r) -> str:
    s = r["status"]
    if r["log"] == "NOT RUN":
        return "not run"
    return "ok" if s == "ok" else s.split(":")[0]


def patient_table(a: pd.DataFrame) -> str:
    head = ("<tr><th>patient</th><th>sys</th><th>run</th><th>crop (s)</th><th>ref</th><th>bad</th><th>unk</th>"
            "<th>notch</th><th>trials a / p / r</th><th>cubes / cond</th><th>status</th></tr>")
    rows = []
    for _, r in a.iterrows():
        tr = " / ".join(str(r[f"{c}_trials_used"] or "–") for c in ("audio", "picture", "reading"))
        cubes = "/".join(str(r[f"{c}_cubes"] or "0") for c in ("audio", "picture", "reading"))
        run = r["run_start"][5:] if r["run_start"] else "–"
        rows.append(f"<tr><td><b>{_e(r['patient'])}</b></td><td>{_e(r['system'])}</td><td>{_e(run)}</td>"
                    f"<td>{_e(r['crop_cfg'].replace(' s', '') or '–')}</td><td>{_e(ref_short(r))}</td>"
                    f"<td>{_e(r['bad_listed_n'])}</td><td>{_e(r['unknown_dropped'] or '0')}</td>"
                    f"<td>{_e(r['notch_method'])}{' · shaft' if r['notch_scope'] == 'per shaft' else ''}</td>"
                    f"<td>{_e(tr)}</td><td>{_e(cubes)}</td><td>{_e(status_short(r))}</td></tr>")
    return f'<table class="sum" style="margin:8px 0;font-size:12px">{head}{"".join(rows)}</table>'


def run_status(a: pd.DataFrame | None) -> str:
    if a is None:
        return ul("audit table missing: run <code>141_audit_140.py</code>")
    ran = a[a["log"] != "NOT RUN"]
    ok = ran[ran["status"] == "ok"]
    n_cubes = sum(max(int(r[f"{c}_cubes"] or 0) for c in ("audio", "picture", "reading")) for _, r in ran.iterrows())
    not_run = [p for p in a[a["log"] == "NOT RUN"]["patient"]]
    bad = [f"{r['patient']}: {r['status']}" for _, r in ran.iterrows() if r["status"] != "ok"]
    days = sorted({r["run_start"][:10] for _, r in ran.iterrows() if r["run_start"]})
    shapes = sorted({s for s in ran["shapes"] if s})
    return ul(
        f"patients in <code>cfg.patient_ids</code>: <b>{len(a)}</b> · run: <b>{len(ran)}</b> ({', '.join(days)}) · ok: <b>{len(ok)}</b>"
        + (f" · not run: {', '.join(not_run)}" if not_run else ""),
        "producer: <code>01_FBM_Analysis/140_ersp_pipeline.py --patient &lt;id&gt;</code> (one process per patient; notebook 140 = same code)",
        f"contacts with cubes: <b>{n_cubes}</b> · cube shape: {', '.join(shapes) or '–'} (freq × warped time) · fmax <b>400 Hz</b>",
        "errors: " + ("; ".join(_e(b) for b in bad) if bad else "none"),
        "table: <code>outputs/03_ERSP/audit_140.tsv</code> / <code>.md</code> (<code>141_audit_140.py</code>) - one row per patient, 103 columns"
        + ("" if AUDIT_USED == AUDIT else " · <b>the 03_ERSP tree has not been audited yet: the numbers on this tab are the last audit of the frozen 04_* way (32 patients, runs to 2026-09-29)</b>"),
    )


def _leftovers(a: pd.DataFrame | None) -> str:
    """Patients whose audit row counts more than 50 unexplained peaks, with the count."""
    if a is None:
        return "–"
    hits = [(int(r["unexplained_peaks"] or 0), r["patient"]) for _, r in a.iterrows()]
    hits = sorted((h for h in hits if h[0] > 50), reverse=True)
    return ", ".join(f"{p} ({n})" for n, p in hits) or "none"


# ---------------------------------------------------------------------------------------
def build(a: pd.DataFrame | None) -> str:
    today = dt.date.today().isoformat()
    S = []
    S.append(B_SEC)
    S.append('  <section id="s1">')
    S.append('    <div class="eyebrow" style="color:var(--s1)">Stage 01</div>')
    S.append('    <h2 class="title">Signal → ERSP</h2>')
    S.append('    <p class="lead">Raw sEEG → one <b>ERSP cube</b> per electrode × condition (103 freq × 300 warped time bins, dB re baseline). '
             'Producer: <code>140_ersp_pipeline.py</code>. Tree: <code>outputs/03_ERSP</code> (one folder per patient, cubes and QC together, since 2026-09-30; <code>04_ersp_LM*</code> frozen as the previous way). '
             f'Outline form, {today}; numbers from <code>audit_140.tsv</code>.</p>')

    # ---- status -------------------------------------------------------------------
    S.append('    <h3 id="s1-status">Run status</h3>')
    S.append('    <div class="method">' + run_status(a) + '</div>')
    S.append('    <h4>Since the 2026-09-24 run</h4>')
    S.append('    ' + ul(
        "<b>2026-09-24</b> · full rerun of 26 patients on the settings of that day: spectrum interpolation <b>per shaft for every patient</b> (the audit of 09-23 had shown the IIR notch digging −0.7 to −8 dB holes), post-offset floor <b>0.2 s</b> (1 s had cost 760 trials on v9), baseline calc window explicit (−0.4, −0.1 s) · <b>PAT_1327</b> joins (165 contacts) · <b>EL038</b> trigger tables rebuilt from the full session log (<code>el038_rebuild_triggers.py</code>: 14 audio + 2 reading trials that a DC6 drift and a pruned log copy had lost)",
        "<b>2026-09-26</b> · EL043, EL046 rerun (EL046 bad list +4: aH_R12, A_L1, pH_L1, A_L2)",
        "<b>2026-09-28</b> · <b>bad-listed contacts are dropped before the reference, the PSD figures and the notch</b> (until then the list only kept a contact out of the reference by name and out of the cluster export: EL045's PlaT_L had three bad contacts of six in the shaft median the notch decides on, and PlaT_L4, 11 dB above the patient's floor, was a fifth of its reference) · <b>width floor</b> <code>notch_interp_min_hw_hz</code>: EL037's 350 Hz row sat 1.15 dB below its neighbours on every trial while the PSD test passed at ±1 Hz — with ±5 Hz the row bias is +0.09; the same floor for EL045 · <b>EL045</b>: a 59.94 Hz comb (the screen's refresh: 180 / 240 / 359.5 Hz on four shafts) that only stood out once the noisy contact left the reference, notched as <code>notch_extra_bases</code> like EL048's railway comb · bad lists: EL037 + pH_R12 (dead in two blocks), aI_L2–5, A_L4, pI_L14, CinG_L2 · EL043 + sSMG8–10 (12–70 Hz floor 10–14 dB up; files removed by hand, no rerun) · EL045 + PlaT_L2–4, A_R8, A_L2–4, STG_L1–2 · EL037 and EL045 rerun",
        "<b>2026-09-29</b> · <b>EL051, EL052 on their FreeSurfer reconstruction</b>: BIDS electrodes tables in <code>BIDS_elec/SEEG-BERN</code>, shaft aliases for the recon's spelling (Pul_R / Pul_, al_R / aI_R, ml / mI, PreCG / PrCG_R), Lookup route and whole-recording CAR retired · each candidate WM contact checked against the other five (ERSP, high gamma, floor): EL051 reference = A_R6, A_R9, aH_R11 (POp_R1 carries a +0.5 dB speech response → <code>WM_NOT_REFERENCE</code>, analysed as data; pH_R8, VIM_12 bad-listed), EL052 = aI_R17, aI_R18, mI_R6, mI_R7, mI_R15 (Pul_R16 14 dB above the floor → bad) · bad lists: EL051 VIM whole shaft, aH_R13 · EL052 ANT_R14, aH_R12, aH_R13, pH_L12, pH_L13, Pul_R16 · PAT_1327 FOD7 removed · both rerun, their 09-24 files deleted (EL052's old cubes carried the CAR tag)",
        "<b>2026-09-30</b> · <b>per-trial rejection on for everyone</b>: high-gamma MAD rule, k = 3.5 (<code>ersp_trial_reject_hg_mad[\"default\"]</code>; see step 7) · <b>PAT_3415 depth-only</b>: its 64 grid and 30 strip contacts (BIDS type n/a, tissueLabel “unknown”) leave with the Unknown drop now that the patient is out of <code>MIXED_GRID_DEPTH_PATIENTS</code>; reference IMG15–17, IPG10 / 12 / 13 (HLG18, 26.8 dB above the floor, had been in it); HLG1–18 bad — the whole shaft sits 25–28 dB above the other depth contacts; CAR vs WM compared on the depth contacts, alike, WM kept · <b>whole-recording CAR</b> now averages neural channels only (the HUG photodiode had been in PAT_3415's mean: a vertical line at 0 and 50 % of every ERSP) · <b>trial z-score tree</b> (145 → 146 / 147 / 148, every patient, 09-30): nobody is drastically affected at z = 3 — 39 of 3777 cohort trials by the montage-wide rule, max 3 per patient-condition · <b>PAT_3415 goes back to WM</b> (was in <code>WHOLE_CAR_PATIENTS</code> for the comparison) · <b>full 140 rerun of the 30 patients</b> on these settings into <code>03_ERSP</code> (19:27–22:23)",
        "<b>2026-10-02</b> · <b>review of the 03_ERSP tree</b> (30 patients, all run 09-30) · bad lists: PAT_3975 PHD1–6, HAG1–3, HAD1–4, FOD1 (ictal); PAT_3455 HAD9, HAD10; PAT_3390 PHG12; EL040 aH_R13, pPVH_L2 — none of them a reference contact; <b>these four patients are not rerun yet</b>, their removed contacts still have cubes · <b>non-neural channels</b>: EKG- / EMG- / the HUG photodiode / PAT_3975's E1–E4 inputs had come through the EL / HUG aux drop in 13 patients (figures only, never a cube) — the aux drop now applies the full non-neural test, their figures and score rows were removed from the tree (<code>143</code>, 15:19) · the <b>photodiode</b> is kept as a figures-only channel in PAT_2868 / 3390 / 3415 / 3455 (trigger check); the 15:19 sweep was the earlier version and removed those figures, they return with the next run of those patients · <b>Signal figures</b> (<code>PerTrial/Signal/</code>): the HFA raster's rows as traces of the cleaned signal, 200 µV per row for every patient; the five <code>.edf</code> patients reach the pipeline in volts and are converted for the figure · <b>PerTrial/</b>: HFA, Signal, TrialScores and Report of a patient in one subfolder (140 writes there; <code>144</code> moves the older folders; readers look in both places meanwhile) · <b>first audit of the tree</b> (<code>141</code>): 30 of 30 ok, 3068 contacts with cubes · <b>EL038</b>: pH_R1, pH_R2, LinG_R5, LinG_R6, A_L1 bad-listed and removed from the tree without a rerun (<code>143 --bad-listed</code>; none is a reference contact) → 61 contacts",
        "<b>2026-10-02, evening</b> · <b>a faulty reference contact can be the whole notch problem</b> (see Checks, FIG 1.7): after the white-matter reference, what is identical on every contact is the reference's own content. EL048's lines sat at the same amplitude and phase on all 69 other contacts and at 10.0×, sign flipped, on aH_L1 — one of its 11 reference contacts, broken in the recording (3230 µV SD against 60–75). aH_L1 bad-listed, <b>EL048 rerun 20:53</b>: lines before the notch 28–57 dB → 6–26 dB, floor −2.1 to −4.1 dB over 70–390 Hz, every band notched at ±1 Hz, the 200 / 300 Hz ERSP rows from −0.61 / −0.76 dB to −0.09 / +0.11 dB (audio), no row above 30 Hz more than 0.3 dB off its neighbours · the same check where the audits pointed: <b>PAT_3965</b> cmd12 and <b>EL033</b> PHG_R4 are the same fault — bad-listed, <b>not rerun yet</b>; EL043's pIns2 carries a line but changes nothing measurable and stays · the notch code is unchanged · bad lists by review of the tree: EL035 CinG_R1 / 3 / 5 / 7 + aI_R1–7, EL033 pH_R7 + aH_R12 + aH_L1–12, EL045 TTG_L4 / 7 / 8 + A_L1 / 5 / 6 + EntG_L5–11 — none a reference contact, removed without a rerun (<code>143 --bad-listed</code>, 19:44 / 20:05 / 20:46) · <code>01_FBM_LM_report.py</code>: one overview PDF per patient (<code>03_ERSP/&lt;pid&gt;/&lt;pid&gt;_overview.pdf</code> — the clean PSD per shaft, then per shaft and condition the clean ERSP, the HFA trials and the Signal trials, six contacts a page) · <code>144</code> applied: HFA, Signal, TrialScores and Report sit under <code>PerTrial/</code> for all 30 (where both folders existed the newer file won) · the per-patient table under Parameters",
        "<b>known</b> · 140 never clears a patient folder: after every rerun the removed contacts' files stay until <code>142_stale_cubes.py --delete</code> or a hand sweep (done for EL037, EL043, EL045, EL051, EL052, PAT_1327; PAT_3415's <code>_CAR_</code> files wait for the sweep after the WM run)",
    ))

    # ---- chain ----------------------------------------------------------------------
    S.append('    <h3 id="s1-chain">Procedure — what the code does, step by step, and where</h3>')
    S.append('    <p class="sechint">Each row is one thing <code>140_ersp_pipeline.py</code> does to a recording, in the order it does it, written from the function that does it; '
             'the last column is the path from <code>Analysis_LoraFanda/</code>, the function and the line (links open the file on GitHub at that line). '
             'Settings are read from <code>functions/config.py</code> when this page is built. Generated by <code>01_FBM_Analysis/make_s1_procedure.py</code>, which fails if a '
             'cited function or block no longer exists.</p>')
    S.append('    ' + procedure_html())
    S.append('    <h4>Downstream (stage 02, not here)</h4>')
    S.append('    ' + ul(
        "gate (noise-scaled since v10, <code>lf_dataset</code> schema 3): a bin counts beyond max(2.2 dB, 2 × noise) / min(−3 dB, −2 × noise), noise = sd(half1 − half2) / 2 of that electrode-condition; <code>prop_above_pos ≥ 0.02</code> ∨ <code>prop_below_neg ≥ 0.04</code> in ≥ 1 condition; per electrode, not per condition",
        "concatenation along time: 3 cubes → 103 × 900 (<code>concat_rawds</code>: 15 bands × 30 bins per block; <code>concat_hg</code>: 70–150 Hz mean per bin) · cache <code>concat_source_v*</code>",
        "constants moved to 103 / 398.4375 Hz on 2026-09-18 in stages 02–05 (<code>lf_dataset</code>, <code>lf_features</code>, <code>lf_clustering</code>, <code>lf_concat</code>, <code>lf_pool</code>, <code>lf_rt</code>, <code>lf_classify</code>, notebooks 240–242 / 212 / 232)",
    ))
    S.append(fig("P2_signal_conditioning.png", "FIG P.2", "Steps 3–4 · reference and notch (documentation figure)",
                 ["A: contact pair before / after WM re-reference (simulated) · B: PSD with mains harmonics · C: scheme per patient type",
                  "documentation of the method, 2026-08-26 (v4); since then: MicroEPI bad-list fix (09-21), bad list applied before the notch (09-28), EL052 on a WM reference instead of a whole-recording CAR (09-29)"],
                 "<code>make_preprocessing_figures.py</code>", sub=DOCS))
    S.append(fig("P3_one_trial_to_ersp.png", "FIG P.3", "Step 6 · one trial → one ERSP (documentation figure)",
                 ["A: raw trial, baseline window marked · B: spectrogram dB · C: after baseline subtraction · D: averaged TN cube (EL033 aH_L11 audio, v4)",
                  "axis then 0–500 Hz / 129 bins; now 0–400 Hz / 103 bins, same 3.906 Hz step"],
                 "<code>make_preprocessing_figures.py</code>, 2026-08-26", sub=DOCS))
    S.append(fig("P4_time_normalisation.png", "FIG P.4", "Step 6b · time normalisation (documentation figure)",
                 ["fast vs slow trial onto the same 300-bin axis · bin = proportion, not latency · bin 150 = stimulus offset in every trial",
                  "anything that moves <code>trial_end</code> rescales bins 150–299 (fixation-cross correction, EL033 / PAT_3965)"],
                 "<code>make_preprocessing_figures.py</code>, 2026-08-26", sub=DOCS))

    # ---- parameters -----------------------------------------------------------------
    S.append('    <h3 id="s1-params">Parameters — per patient</h3>')
    S.append('    ' + ul(
        "columns: crop = EL / HUG preset <code>time_range</code> (MicroEPI: preset) · ref = reference route, WM contact count · bad = <code>bad_channels_manual</code> entries · unk = Unknown-parcellation drops · notch = method (· shaft = per-shaft) · trials = used per condition (after accuracy / duration / IQR) · cubes = per condition",
        "source: <code>audit_140.tsv</code>; a rerun changes this table on the next <code>make_s1_tab.py --insert</code>",
    ))
    S.append('    ' + (patient_table(a) if a is not None else "<p>audit table missing</p>"))
    S.append('    <h4>Per patient — the reference it ran on, the contacts removed and why, what was found, what is owed</h4>')
    S.append('    ' + ul(
        "read at build time: the bad list and the per-patient settings from <code>functions/config.py</code> · the reference of the last run from <code>wm_reref_report.tsv</code> (names in the electrodes table's spelling) · the run time from <code>logs/</code> · the contacts with cubes from the tree · the contacts removed without a rerun from the <code>143</code> logs",
        "written by hand, dated: why a contact is on the list and what a check found — in <code>01_FBM_Analysis/make_s1_patients.py</code>, which refuses a reason for a contact that is not on the list and prints “reason not recorded” for a listed contact nobody wrote a reason for",
        "<b>owed</b> is derived: a reference contact of the last run that is bad-listed now = rerun (the reference changes, so every cube does); a bad-listed contact that still has cubes = <code>143 --bad-listed --delete</code>",
    ))
    S.append('    ' + patients_html())

    # ---- outputs -------------------------------------------------------------------
    S.append('    <h3 id="s1-outputs">Outputs — where things are</h3>')
    S.append('    <div class="method">' + ul(
        "<b>inputs</b> · raw: <code>DATARAW/&lt;cohort&gt;/&lt;pid&gt;/task_FBM/data_LM/raw/</code> (+ events log; <code>RAW_CONCAT</code> joins EL043's and EL051's two files) · triggers: <code>…/prep0/&lt;pid&gt;_LM_&lt;cond&gt;__&lt;trig&gt;_&lt;date&gt;.tsv</code> (onset, onset_duration, sample, sample_offsets, trial_end, condition_name, resp_accuracy, trial_idx; <code>prep0/prep0-bad/</code> = parked tables) · anatomy: <code>BIDS_elec/&lt;site&gt;/sub-&lt;id&gt;/ieeg/*_electrodes.tsv</code> for every patient (EL051 / EL052 since 2026-09-29; the Lookup route in config is empty but kept) · config: <code>functions/config.py</code> (presets, bad lists, references, notch, aliases)",
        "<b>cubes</b> · <code>outputs/03_ERSP/&lt;pid&gt;/LM/ERSP_matrix/&lt;cond&gt;/&lt;pid&gt;_&lt;cond&gt;_&lt;WM|CAR&gt;_ERSP_&lt;ch&gt;_TN.npy</code> (103 × 300 float) · <code>ERSP_halves/&lt;cond&gt;/…_half1|2.npy</code> · <code>ERSP_clean/&lt;cond&gt;/*_CLEAN.png</code> · <code>wm_reref_report.tsv</code>",
        "<b>QC</b> · <code>outputs/03_ERSP/&lt;pid&gt;/LM/</code> (same folder as the cubes): <code>ERSP/&lt;cond&gt;/*.png</code> (every channel that reaches the ERSP: not the bad-listed, not the reference contacts) · <code>PerTrial/</code> (everything with one row per trial, since 2026-10-02): <code>HFA/&lt;cond&gt;/*_HFAtrials_&lt;ch&gt;.png</code> (“HG” in the old tree), <code>Signal/&lt;cond&gt;/*_SIGtrials_&lt;ch&gt;.png</code>, <code>TrialScores/*_trial_scores.tsv</code>, <code>Report/</code> (<code>_IQR.tsv</code>, <code>_&lt;cond&gt;_iqr_postDur_QC.png</code>, <code>_montage_overview.png</code>, <code>_notch_audit.tsv</code>, <code>_unexplained_peaks.tsv</code>) · <code>PSD_raw</code>, <code>PSD_clean</code> · <code>Report/</code>: <code>_IQR.tsv</code>, <code>_&lt;cond&gt;_iqr_postDur_QC.png</code>, <code>_montage_overview.png</code>, <code>_notch_audit.tsv</code>, <code>_unexplained_peaks.tsv</code> · <code>logs/&lt;pid&gt;_&lt;stamp&gt;.log</code>",
        "<b>audit</b> · <code>outputs/03_ERSP/audit_140.tsv</code>, <code>.md</code> · <b>review bundle</b> · <code>02_FBM_Clustering/outputs/250_recon/fsaverage/activity_viz/review/</code> (<code>make_lm_review_bundle.py</code>)",
        "<b>previous trees</b> · <code>04_ersp_LM_RAWONLY</code> + <code>04_ersp_LM</code> (the way up to 2026-09-29, 32 patients, frozen 09-30 for the comparison with 03_ERSP: <code>compare_140_trees.py</code>) · <code>04_ersp_LM_RAWONLY_old</code>, <code>04_ersp_LM_old</code> (run of 2026-08-16 + reruns; 0–500 Hz cubes) · <b>RT tree</b> · <code>05_ERSP_LM_RAWONLY_RealTime</code> (notebook 150, GO-locked, see History)",
        "<b>stale cubes</b> · 140 never clears a patient folder → after a rerun that removes channels, audit by mtime before any cohort build",
        # 2026-09-22: what the cube is normalised TO is the first thing stage 02's distance
        # metric sees, so it belongs here and not only in the clustering tab.
        "<b>what the cube is normalised <i>to</i></b> · dB re the pre-stimulus baseline (−0.4…−0.1 s; the trial segment starts at −0.6 s), per trial and per frequency — so a contact's gain and impedance are divided out, but its <b>response size</b> is not, and that is what drives a Euclidean clustering downstream (<a href=\"#s2norm\">stage 02 · FIG N.1–N.6</a>). <code>compute_ersp</code> also returns <code>avg_z</code> — the same thing divided by the baseline SD, per frequency (<code>lf_ersp.py:1230</code>) — which is the quantity Hamilton, Edwards &amp; Chang 2018 (<i>Curr Biol</i> 28:1860, STAR Methods e1) cluster on; 140 saves only <code>avg_db</code>, so one <code>np.save</code> in the export block would give stage 02 a third space with a published precedent",
        "<b>what the responsiveness gate assumes</b> · the gate is a <i>duration</i> test (|dB| over threshold in ≥ 2–4 % of bins), so a contact with a large but brief transient can fail it. The same hazard made Hamilton et al. 2018 reject a response-vs-silence criterion and select electrodes by held-out STRF prediction instead (STAR Methods e2, “false exclusion of onset electrodes”) — worth one count before v9: gated-out contacts with max |dB| &gt; 4 in under 2 % of bins",
    ) + '</div>')

    # ---- checks ---------------------------------------------------------------------
    S.append('    <h3 id="s1-checks">Checks — audit and review</h3>')
    S.append('    ' + ul(
        "<b><code>141_audit_140.py</code></b> → per patient: run time, status, crop, channels in / neural / Unknown / aux, bad list, reference route + WM list, notch per condition (notched / comb left / off-comb / unexplained), trials in → IQR kept → used, cubes new vs previous tree (name diff, classified), shapes, NaN sample, QC counts, <b>name reconciliation</b> (removed by bad list / removed by no rule / listed but not recorded) · <b>caveat, 10-02</b>: “listed but not recorded” compares the bad list with the ERSP figure names; since the bad list is applied before the ERSP stage (09-28) a listed contact never has a figure, so the column now names every listed contact and is not usable until it reads the recording's channel names",
        "<b>LM_visualizer review mode</b> (key <code>r</code>): per patient, contacts shaft by shaft, each tile = concatenated ERSP (audio | picture | reading, undistorted) · native label (tissueLabel, GM / WM / sub %) + fsaverage aparc · status (data / WM ref / bad / Unknown / aux / not recorded) · split-half r, mains-row stripe index, |dB|, HG per condition · worst-first orders · HG rasters from a local server (<code>?hg=</code>) · bundle: <code>make_lm_review_bundle.py</code> (per-patient rebuilds)",
        "<b>findings, 18–22 Sep</b> (all closed): EL043 aborted → two recordings joined · MicroEPI bad-in-reference → fixed · 137 contacts without anatomy link → <code>CHANNEL_SHAFT_ALIAS</code> · EL038 audio 8 / 39 trials → tables rebuilt from the full log (09-24)",
        "<b>findings, 28–29 Sep</b> (closed): EL045 looked noisy after every notch — a reference contact (PlaT_L4) 11 dB above the patient's floor and three bad contacts in the shaft median the notch decides on → bad list applied before everything · a 350 Hz residue that is trial-locked and invisible to the time-averaged PSD test (EL037 −1.15 dB row bias, EL045 −0.74) → width floor · EL045's screen comb → second comb · the run report's <code>wm_channels_excluded_as_bad</code> compares TSV keys with bad-list spellings (PlanTL4 vs PlaT_L4) → both spellings listed · EL051 / EL052 white-matter candidates checked one by one before the switch to their BIDS tables",
        "<b>findings, 30 Sep</b>: PAT_3415's HLG shaft is bad as a whole (every contact 25–28 dB above the other depth contacts at 70–150 Hz and 16–20 dB at 1–30 Hz — a connector, not tissue) and HLG18 had been one of its nine reference contacts; its OI / OS / TA / TM / TP are subdural strips, not depth shafts (BIDS type n/a like the grid) → depth-only · the HUG photodiode channel survives the aux drop and had entered PAT_3415's CAR mean → CAR on neural channels only · EL039 has no usable triggers (the task ran 09:25–09:48 on 3 Dec 2024; the recording that overlaps it has an unplugged DC6, the one left in raw/ starts after the task) → recon only · the trial z tree (145) on all 32 patients: 13 trials over z = 4 on ≥ 20 % of channels — four are montage-wide (EL033 picture #46 on 67 of 75 channels), the rest sit on one or two shafts (PAT_3965 audio #41 on HAG / AG / CAG only: a discharge, not a trial problem), which is what the per-shaft heatmaps (148) are for",
        "<b>findings, 2 Oct — the reference</b>: EL048's 200 / 300 Hz ERSP bands survived every notch setting because they were not a filter problem. <b>How it was checked</b>: (1) per contact, the complex amplitude of each line in the block signal after the reference and before the notch (the FFT bins within ±0.5 Hz of the harmonic): the same amplitude and phase on every data contact, with one reference contact at (n − 1)× and the sign flipped, is that one contact's line divided by n; (2) that contact against the others in the raw recording (SD, floor, line height); (3) the fix simulated before any rerun — the block re-referenced to the remaining contacts (exact: the reference is linear), then the pipeline's own notch and ERSP — and for EL048 the real rerun gave the simulated numbers to two decimals. <b>Why the notch could not do it</b>, measured on EL048's audio block (200 / 300 Hz row against its neighbours): no notch at all +0.01 / −0.01 dB (the line swamps the row); the notch −0.61 / −0.76 dB; the line taken out as one spatial component, skirts included, −0.02 / +0.10 dB. The line's amplitude steps with the trial — the 400 Hz line is 7–10 % weaker from −0.4 to +0.1 s, the 200 Hz line 1.3–1.7 % stronger, which is the baseline window — and my reading is that a narrow band takes the carrier and leaves those steps' transients in the baseline, so the whole trial reads lower. <b>Result</b>: EL048 aH_L1 (10.0×), PAT_3965 cmd12 (43×), EL033 PHG_R4 (9.0×) — each one reference contact carrying 98–102 % of the line all contacts shared, plus broadband noise into every contact (floor −2.1 to −4.1 dB for EL048, −1.1 to −1.9 dB for PAT_3965, −7 to −10 dB in EL033's audio block once removed) · EL043 pIns2 (21–28× on 50 / 100 / 200 / 300 / 400 Hz, ordinary broadband): no change in floor, notch result or ERSP rows without it — left in",
        "<b>the screen over all 30 patients</b> (10-02, from files already in the tree): the notch audits — a line of the same height on every shaft (EL048: 21 of 21 lines; partly EL043, PAT_3965, EL033, EL036) — and the per-channel PSD tables before the notch — each reference contact's 70–150 Hz power against the median data contact, divided by n²: PAT_3965 cmd12 +26 dB (21 % of a contact's floor), EL033 PHG_R4 +11 dB (14 %); in every other patient the loudest reference contact is within 8 dB of the median data contact (EL034 aH-L7 +7.9, EL043 pIns2 +7.5 — about 1 % at their reference sizes) · thin references add more by construction, with no faulty contact: EL051 (3 contacts) ~15 %, PAT_3415 (6) ~13 %, EL045 (4) ~10 %, EL036 (4) ~9 % · not followed up per contact: EL036's 350 Hz line (17 dB, the same on its 7 shafts) and EL040's CinG_R13 (a reference contact 10 dB above the median data contact at 12–30 Hz)",
        "<b>still open</b>: bad-list names that match no recorded channel, as established in September (EL037 pI_R1–16 + pI_L5 / 10–16 + aI_L18, EL040 PlaT_L1–3 marked “example”, EL034 MFG-10..12, EL030 EntG_R18, PAT_3415 HLG5, PAT_3780 FAP9) — harmless · PAT_6953 Unknown keep-list (AD12, TLD2 / 4 / 5) · thin references: EL051 3 contacts, EL045 4, EL036 4 · notch leftovers (more than 50 unexplained peaks in the audit): " + _leftovers(a),
        "<b>photodiode</b>: EL / HUG <code>LFfunctions_PDextract.get_trigger_indexes_photodiode</code> (threshold 0.40, flip per preset, log pairing) · MicroEPI <code>lf_micromacro.extract_events_from_photodiode</code> · manual trigger tables: EL030, EL038, EL051, EL052, PAT_3301, PAT_3975, PAT_3780 (<code>manual_trig</code>) · PAT_6704 checked 2026-09-18: Heschl (THD1) HG locks at 0 % of the audio stimulus, stimulus durations picture 0.98–1.04 s, reading 3.48–3.55 s · EL038 census 2026-09-24: every logged trial of EL037 / 040 / 042 / 045 / 046 / 052 sits on a pulse",
    ))
    ex_run = "?"
    if a is not None and (a["patient"] == EX).any():
        ex_run = str(a.loc[a["patient"] == EX, "run_start"].iloc[0])[:10] or "?"
    S.append(fig("s1_example_ersp.png", "FIG 1.1", f"Example ERSP · {EX} {EXCH} audio (run {ex_run})",
                 ["x: warped time 0–100 %, line at 50 % = GO · y: 0–400 Hz · colour: dB re baseline, ±6",
                  "transverse temporal (Heschl): HG 70–150 Hz on from 0 %, through the stimulus and the response; low-frequency onset response at 0–5 %"],
                 f"<code>03_ERSP/{EX}/LM/ERSP/audio/{EX}_audio_WM_ERSP_{EXCH}_TN.png</code>"))
    S.append(fig("s1_example_hg.png", "FIG 1.2", f"HFA trials · {EX} {EXCH} audio (run {ex_run})",
                 ["rows: trials sorted by stimulus duration, numbers = rows of the trigger table · colour: HG z · black line: onset · magenta: stimulus offset",
                  f"excluded trials drawn last, red, reason-tagged (accuracy · response &lt; {cfg.min_post_s:g} s or &gt; {cfg.max_post_s:g} s · duration outlier, IQR k = {cfg.iqr_k:g} · power); the header gives the counts of this run"],
                 f"<code>03_ERSP/{EX}/LM/PerTrial/HFA/audio/{EX}_audio_WM_HFAtrials_{EXCH}.png</code>"))
    S.append(fig("s1_trials_iqr.png", "FIG 1.3", f"Trial gate · {EX} audio (run {ex_run})",
                 [f"post-stimulus duration per trial · orange: hard limits {cfg.min_post_s:g}–{cfg.max_post_s:g} s · blue: IQR k = {cfg.iqr_k:g} fences · green kept, red dropped"],
                 f"<code>03_ERSP/{EX}/LM/PerTrial/Report/{EX}_audio_iqr_postDur_QC.png</code>"))
    S.append('    <figure><div class="cap"><div class="fignum">FIG 1.4</div><h4>PSD per shaft · ' + EX + f' audio block, raw vs clean (run {ex_run})</h4>'
             + ul("top: after reference, before notch · bottom: after notch (interp, per shaft) · dashed: 50 Hz harmonics",
                  "the notch audit TSV carries before_db / after_db / hole_hw_hz per harmonic and shaft")
             + f'<div class="runid"><code>03_ERSP/{EX}/LM/PSD_raw|PSD_clean/audio/PSD/psd_by_shaft.png</code></div></div>'
             + f'<div class="imgwrap"><img data-fig="{FIGROOT}/s1_psd_raw.png" alt="PSD raw" style="margin-bottom:8px"><img data-fig="{FIGROOT}/s1_psd_clean.png" alt="PSD clean"></div></figure>')
    S.append(fig("s1_trials_counts_z.png", "FIG 1.5", "Trials per patient: kept / removed, and the spread of the trial z (145 tree, 2026-09-30)",
                 ["A: per patient × condition, kept (pink audio / blue picture / brown reading) and removed before the ERSP (incorrect response, discharge span, duration filters); n in the trigger table on top",
                  "B: one dot per trial — the median over channels of its per-channel z (146: z within each channel across its trials, score = 99th percentile of |dB| in 70–150 Hz); red = the 12 trials 146's montage rule drops at z &gt; 4 on ≥ 20 % of channels, numbered as on the HFA raster · 30 patients of the 03_ERSP tree, 3777 trials",
                  "what it answers: at z = 3 nobody is drastically affected — 39 trials by the montage rule (max 3 in one patient-condition), 13 by median z; the low counts (EL043 20–25, EL046 reading 23) are set by the accuracy / duration filters, not by z"],
                 "<code>147_trial_figure.py</code> · <code>outputs/04_ersp-trialtestzscore/_summary/trial_counts_and_z.png</code>"))
    S.append(fig("s1_trial_z_heatmap.png", "FIG 1.6", "Channel × trial z · EL033 (148, one page per patient)",
                 ["rows: channels grouped by shaft · columns: the trials that reached the ERSP, numbered as on the HFA raster · colour: per-channel z, clipped at 6 · red triangle: the trial 146's rule drops",
                  "a full column is a trial event (picture #46: every shaft) → drop the trial; a block inside a column is one region during that trial (a discharge) → the per-channel MAD rule of step 7 removes it from those channels and keeps the rest; a horizontal band is a channel problem, which z cannot see (it is within-channel) — that is the floor check's job"],
                 "<code>148_trial_z_heatmaps.py</code> · <code>outputs/04_ersp-trialtestzscore/_summary/z_heatmaps/&lt;pid&gt;.png</code>"))

    S.append(fig("s1_ref_el048.png", "FIG 1.7", "One reference contact · EL048, three contacts, the run of 09-30 against the rerun of 10-02",
                 ["per contact: audio | picture | reading, 0–400 Hz, dB re baseline ±6 · left: aH_L1 in the white-matter reference (11 contacts) · right: aH_L1 bad-listed (10 contacts), nothing else changed",
                  "left: the bands at 200 and 300 Hz and at the top of the axis, on every contact · right: gone, and the response half shows a broadband response the injected noise had buried (EntG_R3, aH_L4)",
                  "both sides are the pipeline's own cubes (the 09-30 ones as reproduced by the scratch run, identical to the tree's to 1e-9 dB)"],
                 "<code>03_ERSP/EL048/LM/ERSP_matrix/</code> · figure drawn from the scratch probe of 2026-10-02"))
    S.append(fig("s1_ref_el033_removed.png", "FIG 1.8", "EL033 · the 13 contacts removed on 10-02, with the run's reference and with PHG_R4 out of it (scratch simulation)",
                 ["rows: pH_R7, aH_R12, aH_L1–11 · per contact: audio | picture | reading · left: reference of the 09-30 run (10 contacts) · right: the same blocks re-referenced to the 9 other contacts, then the pipeline's notch and ERSP",
                  "left: horizontal stripes at the harmonics, worst in the audio block (where PHG_R4 is 18 dB above the median data contact) · right: the stripes are gone from all 13",
                  "what stays on the right is the contact's own: aH_L1 / aH_L2 (floor +6 to +12 dB, kurtosis 23–37), a floor rising towards the outermost contact on aH_L9–11 · which of the 13 come back is Lora's call, before EL033's rerun"],
                 "scratch probe of 2026-10-02 (<code>140</code>'s own functions on the captured blocks; nothing in the tree)"))

    # ---- open -----------------------------------------------------------------------
    S.append('    <h3 id="s1-open">Open — what stage 01 still owes</h3>')
    S.append('    ' + ul(
        "<b>rerun owed</b> (the per-patient table derives it): <b>PAT_3965</b> — cmd12 leaves the reference · <b>EL033</b> — PHG_R4 leaves the reference; before that, decide which of the 13 contacts removed on 10-02 come back (FIG 1.8) · then <code>141_audit_140.py</code>",
        "<b>worth a rerun, not owed</b>: the patients whose contacts were removed from the tree without one — EL035, EL038, EL040, EL045, PAT_3390, PAT_3455, PAT_3975. The notch is decided per shaft, so a shaft that lost a contact was notched with it in; measured on EL033 against a fresh run: the cubes of aH_R and pH_R differ by 0.35 dB on average (0.5 dB in the rows within ±15 Hz of a harmonic, 0.06–0.08 dB elsewhere), the five untouched shafts are identical to 1e-10 dB · the photodiode figures of PAT_2868 / 3390 / 3415 / 3455 return with their next run",
        "<b>after the reruns</b>: <code>141_audit_140.py</code> → <code>142_stale_cubes.py --delete</code> → <code>rebuild_concat_cache.py --version 14</code> (reads 03_ERSP) → 240 / 241 / 242 → <code>make_paper2_outputs.py</code> · the v13 cache and everything on the site below it are the last of the 04_* way · every run fitted from here on carries its cache name and the readers refuse another cohort's run",
        "<b>Signal figures at the old scale</b>: PAT_5515, PAT_6704, PAT_6854 (all) and PAT_5533 (165 of 492) → <code>149_signal_plots_only.py --patient G-01 G-02 G-04 G-06</code> · <b>EL048's overview PDF</b> predates its rerun → <code>01_FBM_LM_report.py --patients EL048</code> · the LM review bundle and its QC images still show EL048 before the rerun and the removed contacts of the swept patients (<code>make_lm_review_bundle.py</code>, <code>make_lm_qc_images.py</code>)",
        "<b>reference, not followed up per contact</b>: EL040's CinG_R13 (10 dB above the median data contact at 12–30 Hz; one of 9) · EL036's 350 Hz line (the same height on its 7 shafts; a 4-contact reference)",
        "<b>known gap in the notch</b>: for a patient with a second comb (EL048, EL045) the candidate list stops below <code>fmax</code>, so 400 Hz is never tested (<code>notch_by_interpolation</code>, one comparison). EL048 after its rerun: the top rows are within ±0.2 dB of the rows below (the simulation leaves an 8 dB line there before the notch)",
        "compare the two ways: <code>compare_140_trees.py</code> (old = <code>04_ersp_LM*</code>, new = <code>03_ERSP</code>) — trial counts per channel, cube differences, the HFA rasters with the MAD-dropped trials",
        "decide: the bad-list names that match no recorded channel (list under Checks) — delete the dead entries or leave them · <code>141</code>'s “listed but not recorded” column to be rebuilt on the recording's channel names (caveat under Checks)",
        "decide: PAT_6953 Unknown contacts (AD12, TLD2 / 4 / 5) keep-list",
        "QC pass in review mode, patient by patient: trigger lock, reference bleed, stripes, bad channels, low trial counts (EL037 / EL043 / EL045 done 09-28)",
        "aparc labels on fsaverage for PAT_1327, EL051, EL052: <code>211_validation.ipynb</code> (<code>aparc_lookup.csv</code> is of 09-22), then the review bundle again",
        "known: <code>pd_blocks</code> (per-block photodiode equalisation) reaches notebook 13 only, not 140 · micro / macro ERSP comparison (nb 11) never run to a saved output",
    ))

    # ---- history --------------------------------------------------------------------
    S.append('    <h3 id="s1-history">History</h3>')
    S.append('    ' + ul(
        "<b>2026-10-02</b> · review of the tree: bad lists PAT_3975 / PAT_3455 / PAT_3390 / EL040 · full non-neural aux drop for EL / HUG, photodiode kept as a figures-only channel · Signal figures (200 µV per row; .edf patients converted from volts) · PerTrial/ subfolder (HFA, Signal, TrialScores, Report) · <code>143</code>, <code>144</code>, <code>149</code> · first audit of 03_ERSP · LM review bundle rebuilt from 03_ERSP, non-cohort patients starred · the procedure table with code citations · <b>the reference check</b>: EL048 aH_L1 (rerun), PAT_3965 cmd12, EL033 PHG_R4 — one faulty white-matter contact each, injecting its lines and noise into every contact through the reference mean · bad lists EL035 / EL033 / EL045 / EL038 by review, removed without a rerun · overview PDF per patient · the per-patient table",
        "<b>2026-09-30</b> · one output tree <code>03_ERSP</code> (cubes + QC per patient; <code>HG</code> → <code>HFA</code>; 04_* frozen) for the 30 patients of the 03_ERSP tree · per-trial rejection for everyone: HFA MAD k = 3.5 per channel (the z form is blind to channels with many bad trials) · PAT_3415 depth-only (grid + strips out via the Unknown drop, HLG shaft bad, 6-contact reference; CAR vs WM alike, WM kept) · CAR mean on neural channels only · trial z tree 145–148 on all patients: counts, violins, per-shaft heatmaps · TABLE C.0 (every patient and why it is or is not in the cohort) under FIG C.0 · EL039 = no triggers",
        "<b>2026-09-29</b> · EL051 / EL052 on their FreeSurfer reconstruction (BIDS tables, shaft aliases, WM references 3 / 5 after a contact-by-contact check; POp_R1 kept as data, Pul_R16 bad) · Lookup anatomy route and whole-recording CAR retired · PAT_1327 FOD7 out",
        "<b>2026-09-28</b> · bad list applied before the reference and the notch · width floor at 350 Hz (EL037, EL045) · EL045 screen comb 59.94 Hz · bad lists EL037 / EL043 / EL045 after per-contact sheets (floor vs the patient's median, ERSP, HG raster) · stale files of the removed contacts swept by hand",
        "<b>2026-09-24 / 26</b> · rerun of all patients on interp per shaft, post floor 0.2 s, PAT_1327 in, EL038 triggers rebuilt · EL043 / EL046 rerun 09-26",
        "<b>2026-09-21 / 22</b> · MicroEPI bad-in-reference fix, PAT_6704 / PAT_6854 rerun · EL043 two recordings joined, 18 June picture triggers, rerun · PAT_6953 run · review mode + review bundle · audit script · microelectrode rule in the dataset builder = lower-case-m spelling (PAT_2868 IDM / POM are stereo contacts, back in v9) · <code>CHANNEL_SHAFT_ALIAS</code> for 137 contacts of 10 patients, reruns of those ten · <code>142_stale_cubes.py</code> sweep (546 files)",
        "<b>2026-09-18</b> · fmax 400 Hz (crop in <code>_spectro</code>, option A; downstream constants 103 / 398.4375) · 140 as per-patient script · EL051 bad list (29) · full rerun, 31 patients, 8.1 h · trees renamed <code>_old</code>",
        "<b>2026-09-17</b> · EL052 whole-recording CAR (no WM contact recorded) · <b>09-15</b> · PAT_6684 (G-05) out of the dataset · <b>09-14</b> · G-05 on its Micromed TRC, discharge spans",
        "<b>2026-09-09</b> · per-trial rejection (broadband z / band MAD, ≤ 34 %; G-05 only) · HG raster rewritten: every excluded trial drawn, reason-tagged · <code>collect_trials</code> returns the whole table",
        "<b>2026-09-07</b> · notch per condition block, per shaft for stripe patients, spectrum interpolation, audit TSVs, unexplained peaks · figures PNG not TIFF · PSD / cube-stripe review (EL036 / 037 / 040 / 045 / 048)",
        "<b>2026-08-26</b> · chain documented, FIG P.1–P.6 (v4 numbers: 9,774 cubes → 2,959 contacts with three conditions → 1,693 gated; gate = largest narrowing, 43 %)",
        "<b>2026-08-16</b> · aux-name filter widened (EKG-, EMG-, X families were ERSP'd as cortex; 425 files deleted) · run of the previous tree",
        "<b>photodiode</b> · flip applied to the array before detection and QC figure (both paths) · <code>pd_blocks</code> equalisation, notebook 13 only",
        "<b>notebook 150, RT tree</b> (<code>05_ERSP_LM_RAWONLY_RealTime</code>): same chain, no warp, epochs in seconds centred on GO (−2.5 … +5 s), cubes <code>_RT_GO</code> (129 × nt, axes not stored) · first run 9 / 30 patients (HUG path bug <code>PAT_PAT_</code>, since fixed; 11 out-of-memory → one process per patient) · sample: PAT_6854 AGm4, HG on at GO for ~1.5 s on every trial · stage 05 reads it",
        "<b>old example figures</b> (2026-07-19, G-05 rasters 2026-09-09) replaced above by the 2026-09-18 run",
    ))
    S.append(fig("P1_pipeline_overview.png", "FIG P.1", "Chain overview with v4 survival counts (2026-08-26)",
                 ["nine steps raw → feature matrix · counts per narrowing, cohort v4"], "<code>make_preprocessing_figures.py</code>", sub=DOCS))
    S.append(fig("P5_trial_and_electrode_selection.png", "FIG P.5", "Trial filters and the stage-02 gate (v4)",
                 ["trial filters in order · supra-threshold region on a real cube · gate rule with v4 counts (post limit then 1–5 s; now 1–10 s)"],
                 "<code>make_preprocessing_figures.py</code>", sub=DOCS))
    S.append(fig("P6_cube_to_features.png", "FIG P.6", "Three cubes → feature matrices (v4)",
                 ["concatenation along time · <code>concat_hg</code> (n, 900) · <code>concat_rawds</code> (n, 1350) · v4: 1,693 electrodes, 27 patients"],
                 "<code>make_preprocessing_figures.py</code>", sub=DOCS))
    S.append(fig("realtime/RT1_run_status.png", "FIG RT.1", "Notebook 150 first run · per-patient status",
                 ["9 of 30 completed (5 MicroEPI under PAT_ folder names, 4 Bern) · 10 HUG: path bug · 11: out of memory"], "<code>05_ERSP_LM_RAWONLY_RealTime</code>"))
    S.append(fig("realtime/RT_sample_hg.png", "FIG RT.2", "GO-locked single trials · PAT_6854 AGm4 audio",
                 ["black: GO · magenta: stimulus onset (−2.2 … −4.1 s) · green: response end · HG on at GO, ~1.5 s, every trial"],
                 "<code>PAT_6854/LM/HG/audio/…_AGm4_GO.png</code>"))
    S.append(fig("realtime/RT_sample_ersp.png", "FIG RT.3", "GO-locked cube · PAT_6854 AGm4, three conditions",
                 ["HG increase locked to GO in all three · audio at GO, picture +0.3 s (+ burst near +4 s), reading +0.5 s"],
                 "<code>…_AGm4_RT_GO.npy</code>"))
    S.append('  </section>')
    S.append(E_SEC)
    return "\n".join(S) + "\n"


# ---------------------------------------------------------------------------------------
def copy_figs() -> list[str]:
    OUT.mkdir(parents=True, exist_ok=True)
    missing = []
    for name, src in FIGS.items():
        if src is None:
            if not (OUT / name).exists():
                missing.append(f"{name}  <-  (expected already in _status_png)")
            continue
        if not src.exists():
            missing.append(f"{name}  <-  {src}")
            continue
        if src.stat().st_size > MAX_FIG_MB * 1e6:
            missing.append(f"{name}  <-  {src} ({src.stat().st_size / 1e6:.1f} MB, above the commit guard)")
            continue
        shutil.copy2(src, OUT / name)
        print(f"  copied {name}  <-  {src.relative_to(ROOT)}  ({src.stat().st_size / 1e3:.0f} kB)")
    return missing


def insert(block: str) -> None:
    s = SITE.read_text(encoding="utf-8")
    if B_SEC in s and E_SEC in s:
        i, j = s.index(B_SEC), s.index(E_SEC) + len(E_SEC)
        s = s[:i] + block.rstrip("\n") + s[j:]
        print("replaced the generated block")
    else:
        i = s.index('  <section id="s1">')
        j = s.index(STAGE2, i)
        s = s[:i] + block + "\n" + s[j:]
        print("replaced the hand-written <section id=\"s1\"> block")
    SITE.write_text(s, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    a = ap.parse_args()
    missing = copy_figs()
    for m in missing:
        print("  MISSING", m)
    audit = read_audit()
    block = build(audit)
    print(f"block: {len(block):,} chars · patients in table: {0 if audit is None else len(audit)}")
    if a.insert:
        insert(block)
        print(f"wrote {SITE}")
    else:
        print("(pass --insert to splice it into the site)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
