#!/usr/bin/env python3
"""
make_cnmf_method_block.py - the "how convex NMF is applied" block of the clustering tab.

    python make_cnmf_method_block.py            print it
    python make_cnmf_method_block.py --insert   splice it into analysis_status.html

Short text, two big figures. Every number in the prose is read from
explainers/E13_cnmf_on_data.json (make_cnmf_on_data_explainer.py: six arbitrary electrodes,
k = 2) and explainers/E14_cnmf_three_roles.json (make_cnmf_three_roles_explainer.py: forty
electrodes chosen by rule to be auditory, visual, motor or negative, k = 4, plus the
arithmetic entry by entry) - so the words cannot drift from the pictures, and re-running an
explainer updates both.
"""
from __future__ import annotations

import argparse
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SITE = Path.home() / "lorafanda.github.io" / "analysis_status.html"
JSON = ROOT / "outputs" / "clustering" / "explainers" / "E13_cnmf_on_data.json"
FIG = "02_FBM_Clustering/outputs/clustering/explainers/E13_cnmf_on_data.png"
JSON2 = ROOT / "outputs" / "clustering" / "explainers" / "E14_cnmf_three_roles.json"
FIG2 = "02_FBM_Clustering/outputs/clustering/explainers/E14_cnmf_three_roles.png"
BEGIN = "<!-- BEGIN cnmf method, generated by make_cnmf_method_block.py - do not hand-edit -->"
END = "<!-- END cnmf method -->"
ANCHOR = '<h4 id="s2where">'          # the block goes immediately before this

REFS = [
    ("Ding, Li &amp; Jordan (2010)", "IEEE TPAMI 32(1):45&ndash;55",
     "10.1109/TPAMI.2008.277", "the algorithm, and the A&#8314;/A&#8315; split that lets X be signed"),
    ("Hamilton, Edwards &amp; Chang (2018)", "Curr Biol 28:1860&ndash;1871",
     "10.1016/j.cub.2018.04.033", "cNMF on intracranial high-gamma"),
    ("Hamilton et al. (2021)", "Cell 184:4626&ndash;4639",
     "10.1016/j.cell.2021.07.019", "on signed, z-scored high-gamma"),
    ("Kurteff et al. (2024)", "J Neurosci 44:e1109242024",
     "10.1523/JNEUROSCI.1109-24.2024", "across concatenated conditions, as here"),
    ("Norman-Haignere et al. (2022)", "Curr Biol 32:1470&ndash;1484",
     "10.1016/j.cub.2022.01.069", "rank by cross-validated prediction, not an internal index"),
]


def build() -> str:
    d = json.loads(JSON.read_text())
    n = len(d["electrodes"])
    p = d["n_features"]
    k = d["k"]
    neg, tot = d["n_negative"], d["n_values"]
    var = d["var_explained"]
    G = d["G"]
    # the true median, matching the figure's np.median - sorted()[n//2] is the UPPER middle
    # value for an even n, which would print a different threshold here than the figure used
    from statistics import median
    tots = [sum(g) for g in G]
    med = median(tots)
    mixed = [i for i in range(n)
             if tots[i] > 1e-9 and max(g / tots[i] for g in G[i]) < 0.6]
    faint = [i for i in range(n) if tots[i] <= 0.25 * median([t for t in tots if t > 1e-9])]
    short = [e.replace("|", " ") for e in d["electrodes"]]

    refs = "".join(
        f'<li><b>{a}</b> &middot; {j} &middot; '
        f'<a href="https://doi.org/{doi}">{doi}</a> &mdash; {what}</li>'
        for a, j, doi, what in REFS)

    return f"""{BEGIN}
    <h4 id="s2cnmf">How convex NMF is applied to this data</h4>
    <div class="method" style="border-left:4px solid var(--s2)">
      <p style="margin:0 0 8px"><b>The whole model is one line:</b>
        <code>X &asymp; G (W&prime;X)</code>. Everything below is that line, worked through on
        {n} real electrodes of this cohort &mdash; one per patient, high-gamma averaged into
        {p // len(d['conditions'])} time bins per condition so every matrix fits on a page at
        readable precision. Nothing else is simplified: the values are dB relative to baseline,
        they are signed, and they go through the pipeline's own
        <code>lf_decompose.convex_nmf</code>.</p>
      <ul style="margin:0 0 10px">
        <li><b>The data is signed, so plain NMF is not an option.</b> {neg} of {tot} values
          in this sample sit below baseline. Convex NMF never requires <code>X &ge; 0</code>:
          it works on the Gram matrix <code>A = X X&prime;</code> and splits it into two
          non-negative halves, <code>A = A&#8314; &minus; A&#8315;</code>. Only <b>W</b> and
          <b>G</b> must stay non-negative.</li>
        <li><b>A component is a real response, not an abstract axis.</b> The columns of
          <b>W</b> sum to 1, so <code>W&prime;X</code> is a weighted <i>average</i> of recorded
          electrodes. It keeps dB units and can be drawn on the same axes as the data.</li>
        <li><b>A loading is graded.</b> <b>G</b> says how much of each component an electrode
          expresses. In this sample {len(mixed)} of {n} electrodes have <i>no</i> majority
          component &mdash; {', '.join(short[i] for i in mixed)} split near 50/50 &mdash; and
          {short[faint[0]] if faint else 'one'} barely loads at all
          (&Sigma;&nbsp;{tots[faint[0]]:.2f} against a median of {med:.2f}). A hard method must still hand each of them
          a single label.</li>
        <li><b>The argmax is imposed afterwards.</b> It exists to make the result comparable
          with k-means and Ward, and it is exactly where the grading is discarded.</li>
        <li><b>k is chosen by held-out reconstruction</b>
          (<code>lf_decompose.cv_rank_curve</code>): fit without a fold of electrodes, project
          that fold on by non-negative least squares, measure its error. A rank that overfits
          scores <i>worse</i> &mdash; which an internal index like silhouette cannot do.
          The figure is drawn at k&nbsp;=&nbsp;{k}, which accounts for {var:.0%} of the
          variance of this {n}-electrode sample.</li>
      </ul>
      <p style="margin:0 0 4px"><b>Where the method comes from</b>, and where it has been used
        on this data type:</p>
      <ul style="margin:0">{refs}</ul>
      <div class="runid">every reference checked against Crossref (author, journal, year,
        volume, pages) &middot; figure and numbers from
        <code>make_cnmf_on_data_explainer.py</code> &rarr;
        <code>explainers/E13_cnmf_on_data.json</code></div>
    </div>
    <figure>
      <div class="cap"><div class="fignum">FIG E.13</div>
        <h4>Convex NMF worked through on this cohort's own high-gamma</h4>
        <div class="runid"><code>{FIG.split('/')[-1]}</code> &middot;
          <code>make_cnmf_on_data_explainer.py --k {k} --bins {p // len(d['conditions'])} --n {n}</code></div></div>
      <div class="imgwrap"><img data-fig="{FIG}" alt="convex NMF on six real electrodes: the
        signed data, the Gram split, W and G, the components in dB, and the variance
        accounted for"></div>
    </figure>
{build_part2()}{END}
"""


def build_part2() -> str:
    """Three roles, thirty electrodes, k = 3, and the arithmetic - every number from E14's JSON."""
    d = json.loads(JSON2.read_text(encoding="utf-8"))
    n, k, per, nb = len(d["electrodes"]), d["k"], d["per_group"], d["bins_per_condition"]
    pools, conf, C = d["pools"], d["confusion"], d["corr_component_group"]
    groups = list(d["groups"])
    g2c = {g: int(j) for j, g in d["component_to_group"].items()}
    anat = d["anatomy"]

    def lst(g):
        return ", ".join(f"{e.replace('|', ' ')} ({anat[e]})" for e in d["groups"][g])

    head = "".join(f'<th style="padding:2px 10px;font-weight:normal;color:#68727d">&rarr; {g}</th>' for g in groups)
    rows = "".join(
        f'<tr><th style="text-align:left;padding:2px 8px 2px 0;font-weight:normal">chosen as {g}</th>'
        + "".join(f'<td style="text-align:center;padding:2px 10px{";font-weight:bold" if q == r else ""}">{conf[r][q]}</td>'
                  for q in range(k))
        + f'<td style="padding:2px 10px;color:#68727d">its component: r = {C[g2c[g]][r]:+.2f} with the group mean</td></tr>'
        for r, g in enumerate(groups))
    mixed = d["mixed"]
    shares = d.get("mixed_shares", {})

    def mix(e):
        s = shares.get(e, {})
        top = sorted(s.items(), key=lambda kv: -kv[1])[:2]
        return e + (" (" + " / ".join(f"{v:.0%} {g}" for g, v in top) + ")" if top else "")
    split = (f"The {len(mixed)} that split &mdash; {'; '.join(mix(e) for e in mixed)} &mdash; have no majority "
             "component; <b>G</b> records the mixture, the argmax cannot."
             if mixed else "No electrode is split.")
    pre = html.escape("\n".join(d["arithmetic_lines"]))
    words = {3: "Three", 4: "Four", 5: "Five"}.get(len(groups), str(len(groups)))
    nword = {30: "thirty", 40: "forty", 50: "fifty"}.get(n, str(n))
    kinds = ", ".join(groups[:-1]) + " or " + groups[-1]
    return f"""    <h4 id="s2cnmf3">{words} roles, {nword} electrodes, k&nbsp;=&nbsp;{k}: does it find them, and what is computed on the way?</h4>
    <div class="method" style="border-left:4px solid var(--s2)">
      <p style="margin:0 0 8px">FIG&nbsp;E.13 shows the method on six arbitrary electrodes. Here the sample is
        built to have an answer: {per} electrodes per role, chosen <b>by rule, not by hand</b>, from the same
        cache and the same {nb}-bin high-gamma profiles (the first {nb // 2} bins of each condition are the
        stimulus, the last {nb // 2} the response). Anatomy is the review bundle's label for the contact.
        The fourth group is the <b>negative network</b>: contacts that sit below baseline for the whole trial,
        there so the negative values have something to contrast against.</p>
      <ul style="margin:0 0 10px">
        <li><b>auditory</b> &mdash; {pools['auditory']} candidates: &ge;&nbsp;1.5&nbsp;dB during the audio
          stimulus, &le;&nbsp;0.5&nbsp;dB during the visual ones, superior or transverse temporal, at most 3 per
          patient &mdash; {lst('auditory')}.</li>
        <li><b>visual</b> &mdash; {pools['visual']} candidates: &ge;&nbsp;0.7&nbsp;dB during the picture and
          reading stimuli, &le;&nbsp;0.6&nbsp;dB during the audio one, quieter in the response than in the
          stimulus; no per-patient cap, because only two patients carry a visual-only response at all &mdash;
          {lst('visual')}.</li>
        <li><b>motor</b> &mdash; {pools['motor']} candidates: &ge;&nbsp;1&nbsp;dB in the response half and
          &ge;&nbsp;1&nbsp;dB above the stimulus half, pre-/postcentral or pars opercularis, at most 3 per
          patient &mdash; {lst('motor')}.</li>
        <li><b>negative</b> &mdash; {pools['negative']} candidates: mean of the whole profile
          &le;&nbsp;&minus;0.8&nbsp;dB and no bin above 0.5&nbsp;dB, any anatomy, at most 3 per patient &mdash;
          {lst('negative')}.</li>
      </ul>
      <p style="margin:0 0 6px"><b>What the factorisation finds.</b> The {words.lower()} components of
        <code>W&prime;X</code> line up with the {words.lower()} group means, and the argmax of <b>G</b> puts
        {d['argmax_correct']} of {n} electrodes in the group they were chosen for:</p>
      <table style="border-collapse:collapse;margin:0 0 8px;font-size:0.92em">
        <tr><th></th>{head}<th></th></tr>{rows}
      </table>
      <p style="margin:0 0 10px">{split} At k&nbsp;=&nbsp;{k} the model keeps {d['var_explained']:.0%} of the
        variance of the sample; {d['n_negative']} of its {d['n_values']} values are below baseline, which is why
        it has to be <i>convex</i> NMF.</p>
      <p style="margin:0 0 4px"><b>The arithmetic, entry by entry.</b> Every number is read off the matrices in
        FIG&nbsp;E.14; the sums are computed at full precision and printed to two decimals:</p>
      <pre style="white-space:pre-wrap;font-size:12px;line-height:1.55;margin:0 0 8px;padding:10px 12px;border:1px solid var(--line);border-radius:6px;overflow-x:auto">{pre}</pre>
      <div class="runid">figure and numbers from <code>make_cnmf_three_roles_explainer.py</code> &rarr;
        <code>explainers/E14_cnmf_three_roles.json</code></div>
    </div>
    <figure>
      <div class="cap"><div class="fignum">FIG E.14</div>
        <h4>Convex NMF at k = {k} on {nword} electrodes chosen to be {kinds}</h4>
        <div class="runid"><code>{FIG2.split('/')[-1]}</code> &middot;
          <code>make_cnmf_three_roles_explainer.py --k {k} --bins {nb} --per {per}</code></div></div>
      <div class="imgwrap"><img data-fig="{FIG2}" alt="convex NMF at k = {k} on {nword} real electrodes: the
        signed data in {len(groups)} groups, the components against the group means, W and G, the argmax
        table, the reconstruction and residual, the convergence, and the arithmetic entry by entry"></div>
    </figure>
"""


def main(insert):
    block = build()
    if not insert:
        print(block)
        return
    s = SITE.read_text(encoding="utf-8")
    if BEGIN in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + block.strip() + s[j:]
        print("replaced the existing block")
    else:
        a = s.index(ANCHOR)
        a = s.rindex("\n", 0, a) + 1
        s = s[:a] + block + s[a:]
        print(f"inserted before {ANCHOR}")
    SITE.write_text(s, encoding="utf-8")
    print("->", SITE)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    main(ap.parse_args().insert)
