#!/usr/bin/env python3
"""
make_s2_gallery.py - the "what this stage actually produces" gallery of the 02 tab.

One real example of every image the clustering stage writes, pulled from a run that
actually has it and captioned with how to read it. Every path is CHECKED before it is
emitted, so a figure that has not been generated is reported here as missing rather than
rendering as a broken box on the site.

The point of the gallery is the pairing. Each feature set produces TWO views of the same
cluster and they answer different questions:

    concat_hg     the centroid line says what the average member does;
                  the raster says whether the average is describing anyone.
    concat_rawds  the centroid ERSP says the same for a time-frequency plane;
                  the dotted version says where the members disagree about it.

    python make_s2_gallery.py            # write the fragment
    python make_s2_gallery.py --insert   # AND splice it into the site
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CLUST = ROOT / "outputs" / "clustering"
SITE = Path("C:/Users/fanda/lorafanda.github.io/analysis_status.html")
REPO = "02_FBM_Clustering/outputs/clustering"

BEGIN = "<!-- BEGIN s2 gallery, generated by make_s2_gallery.py - do not hand-edit -->"
END = "<!-- END s2 gallery -->"


def newest(method, fset, pat="20260826_*"):
    d = CLUST / method / fset / "runs"
    r = sorted(d.glob(pat)) if d.is_dir() else []
    if not r:
        r = sorted(p for p in d.iterdir() if p.is_dir()) if d.is_dir() else []
    return r[-1] if r else None


def tracked_set():
    """Every path git knows about.

    EXISTING ON DISK IS NOT ENOUGH. The site fetches figures from raw.githubusercontent,
    so a file that is present locally but never committed renders as a 404 - which is
    exactly what the first version of this gallery shipped: S.1-S.4 happened to be
    committed already and worked, S.5-S.14 existed here and did not.
    """
    out = subprocess.run(["git", "-C", str(ROOT.parent), "ls-files"],
                         capture_output=True, text=True)
    return set(out.stdout.splitlines()) if out.returncode == 0 else None


def esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build(peak, tracked=None):
    R = {(m, f): newest(m, f) for m in ("kmeans", "hierarchical", "cnmf")
         for f in ("concat_hg", "concat_rawds")}
    KH, KR = peak.get("concat_hg", 11), peak.get("concat_rawds", 12)

    def rel(run, sub):
        return f"{REPO}/{run.relative_to(CLUST).as_posix()}/{sub}"

    # (id, FIG, title, run, subpath, bullets, alt)
    items = [
        # ── A: what a single cluster produces ──────────────────────────────
        ("g-hg-centroid", "S.1",
         "<code>concat_hg</code> &mdash; the centroid, mean dB with &plusmn;1 SD",
         R[("cnmf", "concat_hg")], f"cluster_centroids/k_{KH}/cluster_00.png",
         ["The cluster's <b>mean high-gamma time course</b> in raw dB, audio | picture | "
          "reading laid end to end, on a y range fitted once across the whole run so the "
          "clusters are comparable to each other.",
          "The band is <b>&plusmn;1 standard deviation ACROSS ELECTRODES</b>, not the "
          "SEM. With 90&ndash;300 electrodes per cluster the SEM is a hairline and says "
          "only that the mean is well estimated, which was never in doubt. SD answers "
          "the question the plot is for: <b>is this cluster a tight family or a loose "
          "one</b>.",
          "Dashed = the GO cue, at 50% of each condition. Solid = the condition "
          "boundary. A singleton cluster has no SD, so only the line shows &mdash; a "
          "statement about n, not a rendering failure.",
          "This is the chip the <a href='clustering_visualizer.html'>visualizer</a> "
          "embeds in each cluster card, one set per K from 5 to 30."],
         "cluster centroid for concat high gamma: mean time course in dB with a plus "
         "or minus one standard deviation band, three conditions side by side"),

        ("g-hg-raster", "S.2",
         "<code>concat_hg</code> &mdash; the raster, every electrode in the cluster",
         R[("cnmf", "concat_hg")], "cluster_rasters/cluster_00.png",
         ["<b>The centroid above is a mean, and a mean cannot say how much its members "
          "agreed.</b> Here every electrode in the cluster gets its own row.",
          "Rows are <b>sorted by how strongly the electrode belongs</b>, strongest at "
          "the top &mdash; the loading on its own component for convex NMF, the "
          "silhouette for k-means and Ward. Those are different measurements, so the "
          "y-axis names which one it is and two runs should not be read as directly "
          "comparable.",
          "<b>What to look for:</b> a cluster that is one thing degrades smoothly "
          "downwards. A cluster that is secretly two things <b>breaks visibly</b> "
          "&mdash; a band of rows doing something the rows above them do not.",
          "The colour limit is the run's own 99th percentile rather than a fixed range: "
          "|dB| reaches 13 here but the 99th percentile is near 3, and a fixed "
          "&plusmn;6.5 would wash every raster out to pale blue."],
         "per-sample raster for a concat high gamma cluster: every electrode as one row "
         "of a heatmap, sorted by membership strength with the strongest at the top"),

        ("g-rawds-centroid", "S.3",
         "<code>concat_rawds</code> &mdash; the centroid, averaged ERSP with SD dots",
         R[("cnmf", "concat_rawds")], f"cluster_centroids/k_{KR}/cluster_00.png",
         ["A <code>concat_rawds</code> sample is 1350 features &mdash; <b>15 frequency "
          "bands &times; 3 conditions &times; 30 time bins</b> &mdash; so its centroid "
          "is a <b>time-frequency plane</b>, not a line. The grid is read from the run's "
          "own <code>feature_schema.json</code>; assuming it is the bug that once "
          "reshaped an ERSP as if it were a time course.",
          "Every bin carries a <b>dot whose area is that bin's SD across the cluster's "
          "electrodes</b>, so it reads in the same direction as the band in S.1: "
          "<b>bigger means the electrodes disagree more</b>.",
          "The SD scale is computed <b>once per run</b>, not per chip. Normalising each "
          "chip to its own worst bin would make a tight cluster and a loose one look "
          "identical, which is the opposite of what the dots are for.",
          "This is the thumbnail in the visualizer card. <b>For the readable version "
          "with a scale bar and a dot legend, see S.4</b>, which is the one to quote."],
         "cluster centroid for concat rawds: the averaged event-related spectral "
         "perturbation as 15 frequency bands by three conditions, with a dot on each "
         "time-frequency bin sized by the standard deviation across electrodes"),

        ("g-rawds-raster", "S.4",
         "<code>concat_rawds</code> &mdash; the same plane, with the SD legend",
         R[("cnmf", "concat_rawds")], "cluster_rasters/cluster_00.png",
         ["<b>Why there is no per-electrode raster here.</b> A <code>concat_hg</code> "
          "sample IS one time course, so it can be a row. A <code>concat_rawds</code> "
          "sample is a whole time-frequency plane and has no single time axis, so it "
          "cannot be flattened into a row without inventing an ordering. The "
          "disagreement is annotated onto the mean instead.",
          "<b>What the dots buy over a plain mean.</b> A plain average cannot separate "
          "<i>the whole cluster sits near zero here</i> from <i>the cluster is split "
          "here and the average cancels</i> &mdash; both come out white. The first keeps "
          "a clear bin; the second gets a dark dot.",
          "The dot sits <b>on</b> the mean rather than tinting it, so the colour read "
          "off the scale bar is still the value.",
          "<b>This dot scale is pooled over EVERY run of the feature set</b>, not per "
          "cluster and not per run. <code>X_train</code> is the same matrix whichever "
          "method partitioned it, so a dot means the same disagreement on convex NMF, "
          "k-means and Ward &mdash; which is the comparison anyone will actually make. "
          "Frequency axis, colour bar and the dot-size legend are all on the figure."],
         "concat rawds cluster centroid with a frequency axis, colour bar and a legend "
         "mapping dot darkness to the within-cluster standard deviation in dB"),

        ("g-recon-cond", "S.5",
         "Where the cluster sits &mdash; glassbrain by condition",
         R[("kmeans", "concat_hg")], "recon/cluster_00/by_condition/lateral_L.png",
         ["Every electrode assigned to the cluster, rendered on the fsaverage surface "
          "and coloured by the condition it responds to. Four views per cluster "
          "(lateral L/R, dorsal, frontal) plus a legend.",
          "<b>Anatomy is never given to any of the algorithms.</b> All of them cluster "
          "on response shape alone, so any spatial structure here was found rather than "
          "imposed &mdash; which is what makes the anatomical-coherence statistic below "
          "worth reporting."],
         "left lateral fsaverage glassbrain showing the electrodes of one cluster "
         "coloured by condition"),

        ("g-recon-pat", "S.6",
         "The same cluster, coloured by patient",
         R[("kmeans", "concat_hg")], "recon/cluster_00/by_patient/lateral_L.png",
         ["The identical electrodes, recoloured by <b>which patient contributed "
          "them</b>. This is the sanity check that a cluster is not one patient's "
          "electrode strip wearing a response type.",
          "It is the per-cluster counterpart of the leave-one-patient-out statistic "
          "below: that one asks whether removing a patient changes the solution, this "
          "one shows at a glance whether a single colour dominates."],
         "the same cluster's electrodes on a left lateral glassbrain, coloured by "
         "patient instead of by condition"),

        # ── B: what a whole run produces ───────────────────────────────────
        ("g-centroids", "S.7", "Every cluster of a run at once",
         R[("kmeans", "concat_hg")], "centroids.png",
         ["All K centroids tiled on one shared y range, which is the quickest read on "
          "<b>whether the run found distinct shapes or K variations on one shape</b>.",
          "Written by <code>fit_and_save</code>, so k-means and Ward have it. The "
          "convex-NMF runs go through <code>run_decomposition.py</code> instead and do "
          "not, which is why this example is a k-means run."],
         "all cluster centroids of one run tiled together on a shared y axis"),

        ("g-sweep", "S.8", "The K sweep &mdash; every K scored, not just the winner",
         R[("kmeans", "concat_hg")], "sweep_metrics.png",
         ["Silhouette, inertia and the other fit metrics across K = 5..30, so the "
          "published K can be seen in the context of the ones that were not chosen.",
          "<b>Read this next to <a href='#s2heldout'>FIG C.13</a>, not instead of "
          "it.</b> These metrics are computed on the data the model was fitted to, so "
          "they cannot say whether an extra cluster earned its place. Only the "
          "bi-cross-validated curve can, and it is the one that picks K."],
         "sweep metrics across K from 5 to 30 for one clustering run"),

        ("g-sil-k", "S.9", "Silhouette across K",
         R[("kmeans", "concat_hg")], "silhouette_by_k.png",
         ["How well separated the partition is at each K, in the space the method fits "
          "in. <b>Silhouette is not space-free</b> &mdash; scoring every method in dB is "
          "the error that made the first version of the separation figure wrong &mdash; "
          "so this is comparable across K within a run, and not across methods."],
         "silhouette score as a function of K for one run"),

        ("g-sil-cluster", "S.10", "Silhouette per cluster, at the published K",
         R[("kmeans", "concat_hg")], "silhouette_per_cluster.png",
         ["The same score broken out per cluster. <b>The mean hides the finding</b>: a "
          "run can have a respectable overall silhouette and still contain one cluster "
          "that is not a real object, and this is where that shows."],
         "per-cluster silhouette scores at the published K"),

        ("g-similarity", "S.11", "Cluster similarity",
         R[("kmeans", "concat_hg")], "similarity_heatmap.png",
         ["Correlation between every pair of centroids. Bright off-diagonal blocks mean "
          "two clusters are describing nearly the same response and K may be too "
          "high."],
         "heatmap of correlations between every pair of cluster centroids"),

        ("g-distance", "S.12", "Centroid distances",
         R[("kmeans", "concat_hg")], "centroid_distance_heatmap.png",
         ["The same question in the metric the method actually minimises. Similarity and "
          "distance disagree when two centroids have the same SHAPE at different "
          "AMPLITUDE, and that disagreement is informative rather than a fault."],
         "heatmap of pairwise distances between cluster centroids"),

        ("g-consensus", "S.13", "Consensus &mdash; would these clusters come back?",
         R[("cnmf", "concat_hg")], f"stability_by_k/k_{KH}/consensus_heatmap.png",
         ["Refit on 50 random 80% subsamples; for each pair of electrodes, of the rounds "
          "where <b>both</b> were drawn, how often did they land together. Reordered by "
          "cluster, so <b>tight blocks on the diagonal = stable clusters</b> and an "
          "off-diagonal smear = clusters that trade members.",
          "A pair only counts in a round where both were present, otherwise sitting out "
          "would look like disagreement.",
          "<b>This is the version that resamples with k-means.</b> On a k-means or Ward "
          "run that is exact. On the convex-NMF run shown here it is not &mdash; see "
          "S.14."],
         "consensus matrix reordered by cluster, showing how often each pair of "
         "electrodes was assigned together across 50 resamples"),

        ("g-consensus-native", "S.14",
         "The same run, resampled with its own method",
         R[("cnmf", "concat_hg")], f"stability_by_k_native/k_{KH}/consensus_heatmap.png",
         ["<b>Identical procedure, one thing changed: the refit uses the method the run "
          "was actually fitted by</b>, in that method's own space &mdash; convex NMF "
          "unit-normed rather than k-means in raw dB.",
          "It moves the number a long way. At K=11 on <code>concat_hg</code> the mean "
          "Jaccard goes from <b>0.332 to 0.658</b> &mdash; from below Hennig's 0.60 rule "
          "of thumb, which reads as <i>not a real cluster</i>, to above it.",
          "<b>The control that makes this a correction and not just a different "
          "number:</b> on a k-means run the native refit IS the old refit, so the two "
          "must agree exactly &mdash; and they come out bit-identical at every K on both "
          "feature sets.",
          "Both are kept. The old column is what was published, and a number that "
          "silently changes meaning is worse than a wrong number sitting next to a right "
          "one. Explained in plain words on the "
          "<a href='#kiss-native'>KISS tab</a>."],
         "consensus matrix for the same convex NMF run, resampled by refitting convex "
         "NMF rather than k-means"),
    ]

    P = [BEGIN,
         '    <h3 id="s2gallery">What this stage produces, one example of each</h3>',
         '    <div class="method" style="border-left:4px solid var(--s2)">',
         "      <b>Every figure below is a real file from a real run</b>, named under it, "
         "and the paths are checked when this section is generated &mdash; a figure that "
         "has not been produced is listed as missing rather than rendered as a broken "
         "box.",
         "      <p style='margin:8px 0 0'><b>Each feature set gets TWO views of every "
         "cluster, and they answer different questions.</b> The centroid says what the "
         "average member does. The second view says <i>whether the average is describing "
         "anyone at all</i> &mdash; as a per-electrode raster for "
         "<code>concat_hg</code>, and as per-bin disagreement dots for "
         "<code>concat_rawds</code>, which has no single time axis to make rows "
         "from.</p>",
         "    </div>"]

    missing, untracked = [], []
    for fid, num, title, run, sub, bullets, alt in items:
        if run is None or not (run / sub).exists():
            missing.append(f"{fid}: {sub}")
            continue
        if tracked is not None and rel(run, sub) not in tracked:
            untracked.append((fid, num, rel(run, sub)))
            continue
        li = "".join(f"<li>{b}</li>" for b in bullets)
        rid = f"{run.relative_to(CLUST).as_posix()}"
        P.append(f"""
    <figure id="{fid}"><div class="cap"><div class="fignum">FIG {num}</div>
      <h4>{title}</h4>
      <ul>{li}</ul>
      <div class="runid"><code>{rid}</code> &middot; <code>{sub}</code></div></div>
      <div class="imgwrap"><img data-fig="{rel(run, sub)}" alt="{esc(alt)}"></div>
    </figure>""")

    if missing:
        P.append('    <div class="method" style="border-left:4px solid #c1121f">'
                 "<b>Not generated yet:</b> " +
                 ", ".join(f"<code>{esc(m)}</code>" for m in missing) + "</div>")
    if untracked:
        P.append('    <div class="method" style="border-left:4px solid #c1121f">'
                 "<b>Generated but not committed</b>, so the page cannot fetch them: " +
                 ", ".join(f"<code>{esc(u[1])}</code>" for u in untracked) + "</div>")
    P.append(END)
    return "\n".join(P), missing, untracked


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    a = ap.parse_args()

    pk = CLUST / "bsf_comparison" / "peak_k.json"
    peak = json.loads(pk.read_text()) if pk.exists() else {}
    tracked = tracked_set()
    if tracked is None:
        print("  (not a git checkout - skipping the tracked check)")
    html, missing, untracked = build(peak, tracked)

    out = CLUST / "statistics" / "webblock_s2gallery.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    n = html.count("<figure")
    print(f"-> {out}   ({n} figures, {len(html):,} chars)")
    for m in missing:
        print(f"   MISSING   {m}")
    for fid, num, path in untracked:
        print(f"   UNTRACKED {num}  {path}")
    if untracked:
        print("\n  commit these or the site will 404 on them:")
        for _, _, path in untracked:
            print(f"    {path}")
    if not a.insert:
        print("\n(pass --insert to splice it into the site)")
        return 0

    s = SITE.read_text(encoding="utf-8")
    if BEGIN in s and END in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + html + s[j:]
        print("replaced the existing gallery")
    else:
        # in front of the generated statistics block: what the stage produces, then
        # what the statistics say about it
        anchor = "<!-- BEGIN generated by make_cluster_webblock.py - do not hand-edit -->"
        if anchor not in s:
            raise SystemExit("statistics block not found - splice by hand this once")
        i = s.index(anchor)
        s = s[:i] + html + "\n\n    " + s[i:]
        print("inserted the gallery before the statistics block")
    SITE.write_text(s, encoding="utf-8")
    print(f"-> {SITE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
