#!/usr/bin/env python3
"""
make_site_gate.py - a password gate on analysis_status.html.

    python make_site_gate.py --insert --password '...'   put the gate on, or change the password
    python make_site_gate.py --remove                    take it off
    python make_site_gate.py --check                     say whether it is on

WHAT IT IS. A screen that hides the page until the right password is typed. The
password never leaves this command line: the page carries only a random salt and a
PBKDF2-SHA256 hash (300,000 rounds), and the browser derives the same hash from what
is typed and compares. A correct entry is remembered in that browser's localStorage,
so the password is typed once per browser, not once per visit. Wrong entries get
"wrong password" and nothing else.

WHAT IT IS NOT. Security against anyone who looks at the source. This is a static
site on GitHub Pages: the HTML is public in the repository, the git history holds every
past version in the clear, and the figures load from a public raw.githubusercontent
URL whether or not the gate is passed. The gate stops a person with the link. It does
not stop a person with curl. Real protection means a private repository or a server
that checks the password before sending the page, and neither is a change this script
can make.

The hash is slow on purpose. Anyone who downloads the page can try passwords against
it offline, and 300,000 rounds of PBKDF2 makes each guess cost about a third of a
second of CPU - enough to make a dictionary run tedious, not enough to make a short or
guessable password safe. Pick a long one.

HOW IT SITS IN THE FILE. One marked block just before </head>: a <style> that hides
.wrap until <html> carries the class "unlocked", and a <script> that adds that class
when the stored token matches, or builds the password screen when it does not. With
JavaScript off the page stays hidden. The other generators splice by their own markers
and are not touched by this one; the only thing to know is that this block adds a
</script> to the <head>, so a generator anchoring on the FIRST </script> for a
first-ever insert would land here - every generator that exists already has its markers
in place and replaces in situ, so this is a note for the next new one, not a problem.

Other pages on the site (poolv2, clustering_visualizer, results, ...) are not gated by
this script. It gates the one file it is pointed at.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

SITE = Path.home() / "lorafanda.github.io" / "analysis_status.html"
BEGIN = "<!-- BEGIN site gate, generated by make_site_gate.py - do not hand-edit -->"
END = "<!-- END site gate -->"
ITERATIONS = 300_000
STORE_KEY = "fbm.gate.ok"


def derive(password: str, salt_hex: str) -> str:
    """Byte-for-byte what Web Crypto's PBKDF2 deriveBits(256) returns in the browser."""
    return hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"),
                               bytes.fromhex(salt_hex), ITERATIONS, dklen=32).hex()


def block(salt_hex: str, hash_hex: str) -> str:
    css = """<style>
  html:not(.unlocked) .wrap{display:none!important}
  html.unlocked #gate{display:none!important}
  #gate{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;
    background:#f6f7f9;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    color:#1c2530}
  #gate .card{background:#fff;border:1px solid #e4e8ec;border-radius:14px;padding:26px 28px 22px;
    width:min(380px,92vw);box-shadow:0 8px 30px rgba(20,30,45,.08)}
  #gate h1{font-size:16px;margin:0 0 2px;letter-spacing:.2px}
  #gate p{margin:0 0 16px;font-size:12.5px;color:#67727e;line-height:1.45}
  #gate input{display:block;width:100%;box-sizing:border-box;font:inherit;padding:9px 11px;
    border:1px solid #e4e8ec;border-radius:8px;margin:0 0 10px;background:#fbfcfd}
  #gate input:focus{outline:none;border-color:#1f77b4;background:#fff;box-shadow:0 0 0 3px rgba(31,119,180,.10)}
  #gate button{display:block;width:100%;font:inherit;font-weight:600;padding:9px;border:0;border-radius:8px;
    background:#1f77b4;color:#fff;cursor:pointer}
  #gate button:hover{background:#0f5e97} #gate button:disabled{opacity:.6;cursor:default}
  #gate .msg{min-height:18px;font-size:12.5px;color:#c0392b;margin:9px 0 0}
  #gate.shake .card{animation:gshake .35s}
  @keyframes gshake{0%,100%{transform:none}25%{transform:translateX(-6px)}75%{transform:translateX(6px)}}
</style>"""
    js = """<script>
(function(){
  var SALT = "%s", HASH = "%s", ITER = %d, KEY = "%s";
  var root = document.documentElement;
  try { if (localStorage.getItem(KEY) === HASH) { root.classList.add("unlocked"); return; } } catch(e){}
  function hex(buf){ return Array.prototype.map.call(new Uint8Array(buf),
    function(b){ return ("0" + b.toString(16)).slice(-2); }).join(""); }
  function fromHex(h){ var a = new Uint8Array(h.length / 2);
    for (var i = 0; i < a.length; i++) a[i] = parseInt(h.substr(2 * i, 2), 16); return a; }
  function derive(pw){
    var enc = new TextEncoder();
    return crypto.subtle.importKey("raw", enc.encode(pw), "PBKDF2", false, ["deriveBits"])
      .then(function(key){ return crypto.subtle.deriveBits(
        {name: "PBKDF2", salt: fromHex(SALT), iterations: ITER, hash: "SHA-256"}, key, 256); })
      .then(hex);
  }
  document.addEventListener("DOMContentLoaded", function(){
    var ov = document.createElement("div");
    ov.id = "gate";
    ov.innerHTML = '<form class="card" autocomplete="off">'
      + '<h1>FBM &middot; Analysis status</h1>'
      + '<p>This page is not public. Enter the password to open it.</p>'
      + '<input type="password" name="p" placeholder="password" autocomplete="current-password" autofocus>'
      + '<button type="submit">Open</button><div class="msg"></div></form>';
    document.body.appendChild(ov);
    var form = ov.querySelector("form"), inp = ov.querySelector("input"),
        btn = ov.querySelector("button"), msg = ov.querySelector(".msg");
    setTimeout(function(){ inp.focus(); }, 50);
    form.onsubmit = function(ev){
      ev.preventDefault();
      if (!window.crypto || !crypto.subtle){
        msg.textContent = "This browser cannot check the password. Use Chrome, Edge, Firefox or Safari over https.";
        return;
      }
      btn.disabled = true; msg.textContent = "";
      derive(inp.value).then(function(h){
        if (h === HASH){
          try { localStorage.setItem(KEY, HASH); } catch(e){}
          root.classList.add("unlocked");
          ov.remove();
        } else {
          msg.textContent = "wrong password";
          inp.value = ""; inp.focus(); btn.disabled = false;
          ov.classList.add("shake"); setTimeout(function(){ ov.classList.remove("shake"); }, 400);
        }
      }).catch(function(e){ msg.textContent = "could not check: " + e; btn.disabled = false; });
    };
  });
})();
</script>""" % (salt_hex, hash_hex, ITERATIONS, STORE_KEY)
    return BEGIN + "\n" + css + "\n" + js + "\n" + END


def strip(s: str) -> tuple[str, bool]:
    if BEGIN in s and END in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        # eat the newline the insert added after the block
        if s[j:j + 1] == "\n":
            j += 1
        return s[:i] + s[j:], True
    return s, False


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--insert", action="store_true", help="put the gate on / change the password")
    g.add_argument("--remove", action="store_true", help="take the gate off")
    g.add_argument("--check", action="store_true", help="report whether the gate is on")
    ap.add_argument("--password", help="with --insert; not stored anywhere, only its hash")
    ap.add_argument("--site", default=str(SITE))
    a = ap.parse_args()

    site = Path(a.site)
    if not site.exists():
        raise SystemExit(f"no {site}")
    s = site.read_text(encoding="utf-8")
    on = BEGIN in s and END in s

    if a.check:
        print(f"gate is {'ON' if on else 'OFF'} for {site}")
        return 0

    if a.remove:
        s, had = strip(s)
        if not had:
            print("no gate to remove")
            return 0
        site.write_text(s, encoding="utf-8")
        print(f"gate removed -> {site}")
        return 0

    if not a.password:
        raise SystemExit("--insert needs --password '...'  (quote it: shells eat & and !)")
    if len(a.password) < 8:
        raise SystemExit("that password is under 8 characters; the hash will not save it")

    salt_hex = os.urandom(16).hex()
    hash_hex = derive(a.password, salt_hex)
    s, had = strip(s)
    if "</head>" not in s:
        raise SystemExit("no </head> in the file - nowhere to put the gate")
    i = s.index("</head>")
    s = s[:i] + block(salt_hex, hash_hex) + "\n" + s[i:]
    site.write_text(s, encoding="utf-8")
    print(f"gate {'replaced' if had else 'inserted'} -> {site}")
    print(f"  PBKDF2-SHA256, {ITERATIONS:,} rounds, salt {salt_hex[:8]}..., hash {hash_hex[:8]}...")
    print("  the password itself is in no file; keep it somewhere you will find it")
    return 0


if __name__ == "__main__":
    sys.exit(main())
