#!/usr/bin/env python3
"""
make_patient_roster.py - TABLE C.0, every patient and why it is (not) in the clustering cohort.

    python make_patient_roster.py                 print the roster, write the JSON
    python make_patient_roster.py --insert        also splice the block under FIG C.0 in the site

One row per patient in the union of three lists: the fsaverage coordinate table (recon done),
audit_140.tsv (140 ran) and the newest concat_source_v<N> cache (cubes reached the cohort).
Everything a rule can say is READ from the rules - config.py (presets, joined files, bad lists,
references, combs), lf_dataset (grid / noisy shafts, microwires), lf_concat (excluded patients,
all-three-conditions, activity gate via make_cohort_figure.cohort_of) - so the table cannot
drift from the code. NOTES below holds only what no rule records (why a recording has no
triggers, what a join cost); edit it there.

Status, in the order the table lists them
  in the cohort           gated electrodes from this patient are in the newest cache's cohort
  in, subdural only       in the cohort, but every electrode is a grid / strip contact
  140 run, not in cohort  ERSP cubes exist but no electrode survives the concat rules
  excluded                lf_concat.DEFAULT_EXCLUDE_PATIENTS
  recon only              coordinates exist, no 140 run
"""
from __future__ import annotations

import argparse
import csv
import glob
import html
import json
import os
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "functions"))
import lf_concat as CC                                    # noqa: E402
import lf_dataset as LD                                   # noqa: E402
from make_cohort_figure import caches, cohort_of          # noqa: E402

# 01's config.py has no imports of its own; loaded by path so that 01's `functions`
# package never shadows 02's (lf_concat imports functions.lf_dataset).
import importlib.util                                     # noqa: E402
_spec = importlib.util.spec_from_file_location("cfg01", REPO / "01_FBM_Analysis" / "functions" / "config.py")
cfg = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(cfg)

AUDIT = REPO / "01_FBM_Analysis" / "outputs" / "03_ERSP" / "audit_140.tsv"   # one tree since 2026-09-30
COORDS = ROOT / "outputs" / "250_recon" / "fsaverage" / "coords" / "ALL_PATIENTS_contacts_fsaverage_nowm.csv"
META = ROOT / "patient_meta.csv"
OUT = ROOT / "outputs" / "clustering" / "cohort"
SITE = Path(os.environ.get("LF_SITE_DIR") or (Path.home() / "lorafanda.github.io")) / "analysis_status.html"

BEGIN = "<!-- BEGIN patient roster, generated by make_patient_roster.py - do not hand-edit -->"
END = "<!-- END patient roster -->"
# Straight under FIG C.0; the figure's own END marker is the anchor, its ANCHOR the fallback.
AFTER = "<!-- END cohort composition -->"
FALLBACK = '<div class="method" id="s2runbook"'

CONDS = ("audio", "picture", "reading")

# What no rule records. Keys are the ids the cohort uses (PAT_<n> / EL<n>).
NOTES = {
    "EL044": "ECoG throughout (grids Pa, T, P, postP), per-grid CAR; only the audio block was "
             "recorded (24 trials; picture 2, reading none), so it could never pass the "
             "all-three-conditions rule either.",
    "PAT_6684": "MicroEPI G-05 run on its Micromed TRC (PATH_OVERRIDES); excluded after the "
                "seizure review - the discharge spans are in bad_time_spans.",
    "EL031": "Three one-block recordings (March 2024) joined, triggers from DC6 per file; the "
             "audio block stopped after 23 trials with the patient asleep and 8 survive the "
             "response-window filters (reading 27 of 53, picture 47 of 51). Excluded whole-"
             "patient on 2026-10-09; its 140 run (whole-recording CAR) stays for a look.",
    "PAT_3415": "Only three depth shafts: IMG and IPG are the reference, HLG1-18 is bad-listed. "
                "GA-GH is an 8x8 grid (dropped on read), OI / OS / TA / TM / TP are subdural "
                "strips (BIDS type n/a, same as the grid) - the electrodes that reach the "
                "cohort are those strips. Decision pending: keep, or exclude whole-patient.",
    "PAT_3301": "Picture naming only - no audio or reading block on file.",
    "EL039": "No usable triggers: the task log runs 09:25-09:48 on 3 Dec 2024, the 26-min "
             "recording (09:28-09:54, in raw/temp moved) has a flat, unplugged DC6 and the "
             "50-min recording left in raw/ starts after the task ended. prep0 is empty; "
             "dropped from patient_ids on 2026-06-02.",
    "EL043": "Picture naming of 17 June was bad and redone on 18 June; the two recordings are "
             "joined and the window 1810-4650 s skips the bad block.",
    "EL051": "Task run in two parts (morning: picture + an abandoned 24-trial audio block; "
             "afternoon: audio + reading); files joined, triggers written on the joined axis, "
             "the 24 morning audio trials left out. Thin reference (3 WM contacts).",
    "EL052": "Photodiode inverted; blocks audio -> reading -> picture; the two dips after "
             "1640 s are not trials. WM reference from the BIDS table since 2026-09-29 "
             "(was a whole-recording CAR while its Lookup had no plugged WM contact).",
    "PAT_1327": "Task spans two TRC files with ~0.8 s missing at the join (a step in every "
                "channel; the one audio trial across it is dropped).",
    "EL038": "Trigger tables rebuilt 2026-09-24 from the full session log (the 2025 detection "
             "lost 14 audio + 2 reading trials in a DC6 drift). Never re-run 140 --pd for it.",
    "EL045": "Reference contact PlaT_L4 was bad and pulled a 350 Hz trial-locked stripe and "
             "a 59.94 Hz screen comb into every channel; fixed by the bad-list drop before "
             "the notch, the screen comb and the 350 Hz width floor (reruns 09-28/29).",
    "EL037": "350 Hz width floor; 24 of its bad-listed names are dead channels the recording "
             "does not carry.",
    "EL048": "Railway comb (16.667 Hz) on top of mains; ~100 peaks the comb model leaves "
             "unexplained. No BIDS entry, anatomy from the Lookup workbook.",
    "EL046": "No BIDS entry, anatomy from the Lookup workbook; task window 21120-23320 s of "
             "a long recording.",
    "PAT_6704": "MicroEPI G-06: THD1/3/4 are white matter but kept as data, not reference; "
                "microwires removed.",
    "PAT_6953": "No anatomy table - the white-matter reference contacts are a manual list.",
    "PAT_3965": "Microwire bundles carry lower-case names (cmd11, y1-y4) and are bad-listed.",
    "PAT_2868": "IDM / POM are stereo shafts, not microwires (2026-09-22 rule).",
}
RECON_ONLY_NOTE = ("Anatomy only on the share - no task_FBM recording for this patient, so "
                   "nothing to run.")


def norm_pid(p) -> str:
    s = str(p)
    return s if s.startswith(("EL", "PAT_", "G-", "B-")) else f"PAT_{s}"


def cfg_get(d: dict, pid: str, raw: str, default=None):
    return d.get(pid, d.get(raw, default))


def rules_for(pid: str, raw: str, audit: dict) -> list[str]:
    """Every rule that names this patient, read from config / lf_dataset."""
    out = []
    if raw in getattr(cfg, "RAW_CONCAT", {}):
        out.append(f"{len(cfg.RAW_CONCAT[raw])} raw files joined")
    pre = cfg.EL_PRESETS.get(raw) if raw.startswith("EL") else None
    if pre:
        bits = []
        if pre.get("flip"):
            bits.append("photodiode flipped")
        tr = pre.get("time_range")
        if tr and tr[1] > 0:
            bits.append(f"window {tr[0]}-{tr[1]} s")
        if pre.get("manual_trig"):
            bits.append("manual trigger table")
        if pre.get("invalid_trials"):
            bits.append(f"{len(pre['invalid_trials'])} invalid trials")
        out += bits
    if raw in getattr(cfg, "MICROEPI_MAT_PRESETS", {}) or raw in getattr(cfg, "MICROEPI_MAT_PATIENTS", []):
        out.append("MicroEPI .mat loader, macros only")
    if pid in getattr(cfg, "PATH_OVERRIDES", {}):
        out.append("PATH_OVERRIDES")
    if pid in getattr(cfg, "STRIP_HEMI_PATIENTS", set()):
        out.append("hemisphere suffix stripped")
    if raw in getattr(cfg, "EL_GRID_PATIENTS", set()):
        out.append("grid patient" + (", per-grid CAR" if raw in getattr(cfg, "GRID_CAR_PATIENTS", set()) else ""))
    if pid in LD.GRID_SHAFTS:
        out.append(f"grid shafts {'/'.join(LD.GRID_SHAFTS[pid])} dropped on read")
    if pid in LD.NOISY_SHAFTS:
        out.append(f"noisy shafts {'/'.join(LD.NOISY_SHAFTS[pid])} dropped")
    wnr = cfg_get(getattr(cfg, "WM_NOT_REFERENCE", {}), pid, raw)
    if wnr:
        out.append(f"WM kept as data: {', '.join(wnr)}")
    if pid in getattr(cfg, "MANUAL_WM_CHANNELS", {}):
        out.append("manual WM list")
    bad = cfg_get(getattr(cfg, "bad_channels_manual", {}), pid, raw, []) or []
    if bad:
        out.append(f"{len(bad)} bad-listed")
    al = cfg_get(getattr(cfg, "CHANNEL_SHAFT_ALIAS", {}), pid, raw)
    if al:
        out.append(f"{len(al)} shaft aliases")
    xb = cfg_get(getattr(cfg, "notch_extra_bases", {}), pid, raw)
    if xb:
        out.append("extra comb " + ", ".join(f"{b:g} Hz" for b in xb))
    fl = cfg_get(getattr(cfg, "notch_interp_min_hw_hz", {}), pid, raw)
    if fl:
        out.append("notch floor " + ", ".join(f"{int(k)} Hz ±{v:g}" for k, v in fl.items()))
    sp = cfg_get(getattr(cfg, "bad_time_spans", {}), pid, raw)
    if sp:
        out.append(f"{len(sp)} excluded time spans")
    if audit.get("wm_source", "").lower().startswith("lookup"):
        out.append("Lookup anatomy (no BIDS entry)")
    if str(audit.get("unknown_dropped", "0")) not in ("", "0", "0.0", "nan"):
        out.append(f"{int(float(audit['unknown_dropped']))} Unknown-tissue contacts dropped")
    return out


def build() -> tuple[str, list[dict]]:
    cache = caches()[-1]
    df, gated, _ = cohort_of(cache)
    gated_by = pd.Series([k.split("|")[0] for k in gated]).value_counts().to_dict()
    cubes_by = {p: g.groupby("condition")["electrode"].nunique().to_dict()
                for p, g in df.groupby("patient_id")}
    excl = {str(p) for p in CC.DEFAULT_EXCLUDE_PATIENTS}

    audit = {}
    if AUDIT.exists():
        with open(AUDIT, encoding="utf-8") as fh:
            audit = {r["patient"]: r for r in csv.DictReader(fh, delimiter="\t")}
    meta = pd.read_csv(META).set_index("patient") if META.exists() else pd.DataFrame()
    recon = set(pd.read_csv(COORDS, usecols=["patient"]).patient.astype(str)) if COORDS.exists() else set()
    # the MicroEPI ids (G-01 ...) run and are written under their preset's pat_name
    mat = {raw: pre["pat_name"] for raw, pre in getattr(cfg, "MICROEPI_MAT_PRESETS", {}).items()}
    raw_of = {mat.get(str(p), norm_pid(p)): str(p) for p in cfg.patient_ids}

    pids = sorted(set(audit) | set(cubes_by) | recon | set(raw_of), key=lambda s: (s[:2] != "EL", s))
    rows = []
    for pid in pids:
        a = audit.get(pid, {})
        raw = raw_of.get(pid, pid)
        n_gated = int(gated_by.get(pid, 0))
        cubes = cubes_by.get(pid, {})
        subdural = {e for e in df.loc[df.patient_id == pid, "electrode"]
                    if LD.is_grid_electrode(e, pid)}
        # every gated electrode of the patient sits on a grid / strip shaft listed for it
        strips = {s.upper() for s in ("OI", "OS", "TA", "TM", "TP")} if pid == "PAT_3415" else set()
        gated_shafts = {re.sub(r"\d+$", "", k.split("|")[1]) for k in gated if k.startswith(pid + "|")}
        if pid in excl:
            status, cls = "excluded", "bad"
        elif n_gated and strips and gated_shafts <= strips:
            status, cls = "in, subdural only", "warnc"
        elif n_gated:
            status, cls = "in the cohort", "good"
        elif a or cubes:
            status, cls = "140 run, not in cohort", "warnc"
        else:
            status, cls = "recon only", ""
        why = []
        if pid in excl:
            why.append("lf_concat.DEFAULT_EXCLUDE_PATIENTS")
        if (a or cubes) and n_gated == 0 and pid not in excl:
            have = [c for c in CONDS if cubes.get(c, 0)]
            if len(have) < 3:
                why.append("conditions on file: " + ", ".join(have or ["none"]) + " - the concat needs all three")
            else:
                why.append("no electrode passes the activity gate")
        if status == "recon only":
            why.append(NOTES.get(pid, RECON_ONLY_NOTE))
        note = NOTES.get(pid, "") if status != "recon only" else ""
        ref = a.get("reference", "")
        ref = re.sub(r"\s*\((skipped as data|selective: WM contacts stay as data)\)", "", ref)
        if a.get("wm_source"):
            ref += f" · {a['wm_source']}"
        rows.append(dict(
            patient=pid, status=status, cls=cls,
            centre=str(meta.centre.get(pid, "")) if len(meta) else "",
            language=str(meta.language.get(pid, "")) if len(meta) else "",
            gated=n_gated, cubes={c: int(cubes.get(c, 0)) for c in CONDS},
            subdural_in_cache=len(subdural),
            run=(a.get("run_start", "") or "")[:10],
            reference=ref, rules=rules_for(pid, raw, a), why=why, note=note))
    return cache.name, rows


def render(cache: str, rows: list[dict]) -> str:
    order = {"in the cohort": 0, "in, subdural only": 1, "140 run, not in cohort": 2, "excluded": 3, "recon only": 4}
    rows = sorted(rows, key=lambda r: (order[r["status"]], r["patient"][:2] != "EL", r["patient"]))
    counts = pd.Series([r["status"] for r in rows]).value_counts().to_dict()
    head = " &middot; ".join(f"{counts.get(k, 0)} {html.escape(k)}" for k in order if counts.get(k))
    e = html.escape
    # the anatomy-only patients share one line: nine identical rows say nothing more
    plain = [r for r in rows if r["status"] == "recon only" and r["why"] == [RECON_ONLY_NOTE]]
    rows = [r for r in rows if r not in plain]
    tr = []
    for r in rows:
        cubes = " / ".join(str(r["cubes"][c]) for c in CONDS) if any(r["cubes"].values()) else "&mdash;"
        el = f"<b>{r['gated']}</b> gated<br><span style='color:var(--muted)'>{cubes} cubes</span>" \
            if r["gated"] or any(r["cubes"].values()) else "&mdash;"
        rules = "; ".join(e(x) for x in r["rules"]) or "&mdash;"
        notes = " ".join([e(x) for x in r["why"]] + ([e(r["note"])] if r["note"] else [])) or "&mdash;"
        cl = f' class="{r["cls"]}"' if r["cls"] else ""
        cen = " ".join(x for x in (r["centre"], r["language"]) if x and x != "nan")
        run = f"<br><span style='color:var(--muted)'>run {e(r['run'])}</span>" if r["run"] else ""
        tr.append(f"        <tr><td><b>{e(r['patient'])}</b><br><span style='color:var(--muted)'>{e(cen)}</span></td>"
                  f"<td{cl} style='white-space:nowrap'>{e(r['status'])}</td><td>{el}</td>"
                  f"<td>{e(r['reference']) or '&mdash;'}{run}</td><td>{rules}</td><td>{notes}</td></tr>")
    if plain:
        names = ", ".join(e(r["patient"]) for r in plain)
        tr.append(f"        <tr><td><b>{len(plain)} more</b><br><span style='color:var(--muted)'>{names}</span></td>"
                  f"<td style='white-space:nowrap'>recon only</td><td>&mdash;</td><td>&mdash;</td><td>&mdash;</td>"
                  f"<td>{e(RECON_ONLY_NOTE)}</td></tr>")
    return f"""{BEGIN}
    <div class="tabhead" style="margin:0 0 18px">
      <div class="cap"><div class="fignum">TABLE C.0</div>
        <h4>Every patient, and why it is or is not in the cohort &mdash; {e(cache)}</h4>
        <div class="runid">{head} &middot; statuses and rules read from <code>config.py</code>,
          <code>lf_dataset</code>, <code>lf_concat</code>, <code>audit_140.tsv</code> and the cache
          &middot; <code>make_patient_roster.py --insert</code></div></div>
      <div style="overflow-x:auto"><table class="cmp" style="font-size:12.4px;margin:0">
        <tr><th>patient</th><th>status</th><th>electrodes</th><th>reference</th><th>rules that name it</th><th>why / notes</th></tr>
{chr(10).join(tr)}
      </table></div>
    </div>
{END}
"""


def insert_block(block: str) -> None:
    if not SITE.exists():
        print(f"  (no {SITE} - block not inserted)")
        return
    page = SITE.read_text(encoding="utf-8")
    if BEGIN in page:
        i, j = page.index(BEGIN), page.index(END) + len(END)
        page = page[:i] + block.strip() + page[j:]
        print("  replaced the existing block")
    else:
        k = page.index('<section id="s2"')
        if AFTER in page[k:]:
            a = page.index(AFTER, k) + len(AFTER)
            a = page.index("\n", a) + 1
            print("  inserted under FIG C.0")
        else:
            a = page.index(FALLBACK, k)
            a = page.rindex("\n", 0, a) + 1
            print("  no FIG C.0 block - inserted at the top of the clustering tab")
        page = page[:a] + block + page[a:]
    SITE.write_text(page, encoding="utf-8")
    print(f"  -> {SITE}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true", help="splice the block into the site")
    a = ap.parse_args()
    cache, rows = build()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "C0_patient_roster.json").write_text(json.dumps(dict(cache=cache, rows=rows), indent=1),
                                                encoding="utf-8")
    for r in rows:
        print(f"{r['patient']:<10} {r['status']:<24} gated {r['gated']:>4}  "
              f"cubes {'/'.join(str(r['cubes'][c]) for c in CONDS):<12} {'; '.join(r['why'])}")
    print(f"  -> {OUT / 'C0_patient_roster.json'}  ({cache})")
    if a.insert:
        insert_block(render(cache, rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
