#!/usr/bin/env python3
"""
make_rebuild_block.py - the "how to rebuild stage 02" block of the clustering tab.

    python make_rebuild_block.py            print it
    python make_rebuild_block.py --insert   splice it into analysis_status.html

The phase list is read from make_paper2_outputs.plan(), not retyped, so the page cannot
drift from the driver: add a step there and it appears here on the next --insert.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
import make_paper2_outputs as DRV  # noqa: E402

SITE = Path.home() / "lorafanda.github.io" / "analysis_status.html"
BEGIN = "<!-- BEGIN stage02 rebuild, generated by make_rebuild_block.py - do not hand-edit -->"
END = "<!-- END stage02 rebuild -->"
ANCHOR = '<h4 id="s2where">'

WHY = {
    "audit": "<code>audit_140.tsv</code> &mdash; the s1 tab, the figure audit and the LM bundle all read it",
    "select": "the held-out curves. <b>Nine scripts read <code>heldout_variance.csv</code></b>, so out of order every K curve is drawn from the previous cohort",
    "runs": "centroids and rasters; a fresh run has neither",
    "paper": "FIG 0&ndash;5, at the K you chose",
    "stage02": "the stage-02 figures this page carries",
    "norm": "the normalisation figures and notes",
    "prep": "the preprocessing figures and the s1 tab",
    "bundles": "coverage first (it writes the manifest the others resolve runs through), then centroids, the visualizer, the LM bundle",
    "site": "the <code>--insert</code> blocks, <code>make_site_ui</code> last, then the audit",
}


def build() -> str:
    steps = DRV.plan(DRV.KS_DEFAULT)
    n = {ph: sum(1 for s in steps if s[0] == ph) for ph in DRV.PHASES}
    rows = "".join(
        f'<tr><td><code>{ph}</code></td><td style="text-align:right">{n[ph]}</td>'
        f'<td>{WHY[ph]}</td></tr>' for ph in DRV.PHASES)

    return f"""{BEGIN}
    <h4 id="s2rebuild">Rebuilding stage 02 &mdash; the order, and why</h4>
    <div class="method" style="border-left:4px solid var(--s2)">
      <p style="margin:0 0 8px">One driver, nine phases, in dependency order. Fit the
        cohort first (<code>rebuild_concat_cache.py</code>, then 240 / 241 / 242); the
        driver reads runs, it never fits one.</p>
      <table class="sum" style="margin:0 0 10px">
        <tr><th>phase</th><th>steps</th><th>what it writes, and why it is here</th></tr>
        {rows}
      </table>
      <p style="margin:0 0 6px"><b>Run it in two halves, because picking K sits between
        them.</b></p>
<pre style="margin:0 0 10px;padding:10px 12px;border-radius:6px;background:var(--chip);overflow-x:auto;font-size:12.5px;line-height:1.5"><code>cd 02_FBM_Clustering

<span style="color:var(--muted)"># 1 - the inputs and the held-out curves</span>
python make_paper2_outputs.py --only audit select

<span style="color:var(--muted)"># 2 - read the curves and pick K (below), then everything else at that K</span>
python make_paper2_outputs.py --ks 8 --only runs paper stage02 norm prep bundles site

<span style="color:var(--muted)"># add --headless if the screen is locked: five steps render brains through
# pyvista and die without a GL context. Run those at the desk afterwards.</span></code></pre>
      <p style="margin:0 0 6px">Then commit what changed, re-run
        <code>make_s2_gallery.py --insert</code> and
        <code>make_paper_figures_webblock.py --insert</code> (both refuse to show an
        uncommitted figure, because the page fetches them from raw.githubusercontent),
        and push the LM bundle with
        <code>python scripts/push_review_bundle.py</code> &mdash; the driver builds it
        but never pushes.</p>
      <p style="margin:0 0 4px"><b>What to look at to pick K.</b> Not the held-out peak:
        the one this page used to quote (K&nbsp;=&nbsp;10&nbsp;/&nbsp;13&nbsp;/&nbsp;13&nbsp;/&nbsp;14)
        was an artefact of <code>convex_nmf</code> returning G and the components on
        different scales, fixed 2026-09-27. Corrected, the curve climbs instead of
        peaking, so K is a judgement, made on these:</p>
      <ul style="margin:0">
        <li><b>Patient spread &mdash; the criterion that decides it.</b> The largest K
          with no one-patient cluster. <code>&lt;run&gt;/cluster_labels_by_k.csv</code>
          joined to <code>labels.csv</code> gives patients per cluster at every K; at the
          old peak K, 15&ndash;45&nbsp;% of electrodes sat in one-patient clusters, and
          K&nbsp;=&nbsp;8 was clean.</li>
        <li><b>Where the curve flattens</b>, not where it tops out &mdash;
          <code>bsf_comparison/heldout_variance_summary_all.csv</code>. A knee is weak
          evidence; treat it as a range, not a value.</li>
        <li><b>Stability</b> &mdash; <code>decomposition/&lt;feature set&gt;/K_selection.png</code>
          with <code>k_stability.csv</code> (leave-one-patient-out) and
          <code>k_split.csv</code> (split-half). K should survive dropping a patient.</li>
        <li><b>Whether the components still separate</b> &mdash; <code>sweep_by_k.csv</code>:
          if <code>frac_no_majority</code> keeps rising and
          <code>median_top_weight</code> keeps falling, the extra components are
          splitting electrodes rather than finding response types.</li>
        <li><b>Cluster sizes</b> &mdash; the <code>sizes</code> column. A K that produces
          a cluster of a handful of electrodes has gone too far.</li>
      </ul>
      <div class="runid">generated from <code>make_paper2_outputs.plan()</code> by
        <code>make_rebuild_block.py</code>, so this list is the driver's own</div>
    </div>
{END}
"""


def main(insert: bool) -> None:
    block = build()
    if not insert:
        print(block)
        return
    s = SITE.read_text(encoding="utf-8")
    if BEGIN in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + block.strip() + s[j:]
        print("replaced the existing block")
    else:
        a = s.index(ANCHOR)
        a = s.rindex("\n", 0, a) + 1
        s = s[:a] + block + s[a:]
        print(f"inserted before {ANCHOR}")
    SITE.write_text(s, encoding="utf-8")
    print("->", SITE)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    main(ap.parse_args().insert)
