#!/usr/bin/env python3
"""
make_paper_figures_webblock.py - the Paper 2 figures section of analysis_status.html.

    python make_paper_figures_webblock.py            print it
    python make_paper_figures_webblock.py --insert   and splice it into the site

Every bullet is READ FROM THE FILES the figures were written with - the peak K, the
one-patient counts, the agreement numbers - so the prose on the site cannot outlive the
figure it describes. Nothing here is typed in by hand except the sentences that explain
what a panel is for.

A figure that is not on disk is listed as missing rather than rendered as a broken box,
and one that is on disk but NOT COMMITTED is called out separately: the site fetches
from raw.githubusercontent, so an uncommitted figure is a 404 with no other symptom.
"""
from __future__ import annotations

import argparse
import html
import subprocess
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
FIGDIR = ROOT / "outputs" / "clustering" / "paper_figures"
SITE = Path.home() / "lorafanda.github.io" / "analysis_status.html"
BEGIN = ("<!-- BEGIN paper2 figures, generated by make_paper_figures_webblock.py "
         "- do not hand-edit -->")
END = "<!-- END paper2 figures -->"
esc = lambda t: html.escape(str(t), quote=True)


def tracked_files():
    """What git actually has. The site 404s on anything else, silently."""
    try:
        out = subprocess.run(["git", "ls-files", "02_FBM_Clustering/outputs/clustering/"
                              "paper_figures"], cwd=str(ROOT.parent), text=True,
                             capture_output=True, timeout=180)
        return set(out.stdout.split()) if out.returncode == 0 else None
    except Exception:
        return None


def rel(p: Path) -> str:
    return p.relative_to(ROOT.parent).as_posix()


def fig1_bullets(png: Path):
    """The numbers behind one FIG 1, read from the CSVs written beside it."""
    stem = png.with_suffix("").name
    b = []
    pc = FIGDIR / f"{stem}_patients.csv"
    gk = FIGDIR / f"{stem}_generalization.csv"
    k = int(stem.split("_K")[-1])
    if pc.exists():
        d = pd.read_csv(pc)
        over = int((d.top_share > 0.50).sum())
        worst = d.loc[d.top_share.idxmax()]
        b.append(f"<b>{over} of {len(d)}</b> clusters are more than half one patient"
                 + (f"; the worst is c{int(worst.cluster)} at "
                    f"<b>{100*worst.top_share:.0f}%</b> from "
                    f"{int(worst.n_patients)} patient"
                    f"{'s' if worst.n_patients != 1 else ''}" if over else "")
                 + f". A size-matched random draw puts the largest patient at "
                   f"{100*d.null_share.mean():.0f}%.")
        b.append(f"Median {int(d.n_patients.median())} patients per cluster.")
    if gk.exists():
        g = pd.read_csv(gk)
        row = g[g.k == k]
        clean = g[g.n_dominated == 0].k.max() if (g.n_dominated == 0).any() else None
        if len(row):
            b.append(f"At this K, <b>{100*float(row.frac_electrodes.iloc[0]):.0f}%</b> "
                     f"of electrodes sit in one-patient clusters"
                     + (f"; the largest K with none at all is <b>K={int(clean)}</b>."
                        if clean is not None else "."))
    return b


def fig2_bullets(png: Path):
    stem = png.with_suffix("").name
    b, ca = [], FIGDIR / f"{stem}_cluster_agreement.csv"
    ea = FIGDIR / f"{stem}_electrode_agreement.csv"
    if ca.exists():
        d = pd.read_csv(ca)
        for half, label in (("feature_set", "feature sets"), ("algorithm", "algorithms")):
            h = d[d.half == half]
            if h.empty:
                continue
            w = h.groupby("block_position").jaccard.min()
            b.append(f"Across <b>{label}</b>: {int((w < 0.30).sum())} of {len(w)} "
                     f"clusters fall below a Jaccard of 0.30 against their match "
                     f"somewhere (median worst match {w.median():.2f}).")
    if ea.exists():
        d = pd.read_csv(ea)
        for col, n, label in (("feature_set_agreement", "n_feature_sets", "feature sets"),
                              ("algorithm_agreement", "n_algorithms", "algorithms")):
            if col in d.columns:
                N = int(d[n].iloc[0])
                b.append(f"Only <b>{100*(d[col] == N).mean():.0f}%</b> of electrodes "
                         f"are placed in the same cluster by all {N} {label}; "
                         f"{100*(d[col] <= 1).mean():.0f}% by no two.")
    return b


def fig3_bullets(png: Path):
    """What FIG 3 found, from the per-cluster table written beside it."""
    stem = png.with_suffix("").name
    f = FIGDIR / f"{stem}_clusters.csv"
    if not f.exists():
        return []
    d = pd.read_csv(f)
    top = d.loc[d.mean_P.idxmax()]
    base = float(d.baseline_P.iloc[0])
    b = [f"<b>{int((d.q_mean < 0.05).sum())} of {len(d)}</b> clusters sit in more LanA "
         f"than a within-patient permutation of the same electrodes would give "
         f"(q &lt; 0.05). The cohort mean is {base:.3f}.",
         f"Most language-aligned: <b>c{int(top.cluster)}</b> at {top.mean_P:.3f} "
         f"(q = {top.q_mean:.2g}); least: c{int(d.loc[d.mean_P.idxmin(), 'cluster'])} "
         f"at {d.mean_P.min():.3f}.",
         f"<b>{int((d.q_rho < 0.05).sum())} of {len(d)}</b> loading-vs-P(LanA) "
         f"correlations survive FDR, and none is large "
         f"(|rho| at most {d.rho.abs().max():.2f}) &mdash; belonging more strongly to a "
         f"cluster barely predicts sitting further into language cortex."]
    thin = d[d.coverage < 0.70]
    b.append(f"LanA covers {100*d.n_lana.sum()/d.n.sum():.0f}% of the electrodes; the "
             f"missing ones are whole patients the atlas run predates"
             + (f", and c{int(thin.cluster.iloc[0])} is only "
                f"{100*thin.coverage.min():.0f}% covered, so its mean is not comparable "
                f"with the rest." if len(thin) else "."))
    return b


def build():
    figs = (sorted(FIGDIR.glob("FIG1*.png")) + sorted(FIGDIR.glob("FIG2*.png"))
            + sorted(FIGDIR.glob("FIG3*.png")))
    figs = [f for f in figs if " - Copy" not in f.name]
    tracked = tracked_files()

    P = [BEGIN,
         '    <h3 id="paper2figs">Paper 2 figures</h3>',
         '    <div class="method" style="border-left:4px solid var(--s2)">',
         "      <b>Built by <code>00_Paper2_Figures.py</code> and "
         "<code>00_paper2_figures2_2.py</code>, driven and explained by "
         "<code>000_Paper2_figures.ipynb</code>.</b> Nothing is written on a figure: "
         "each one ships a <code>_caption.txt</code> beside it with the full "
         "provenance, and the numbers behind every panel as CSV. The bullets below are "
         "read from those files when this section is generated, so a verdict here "
         "cannot outlive the figure it describes.",
         "      <p style='margin:8px 0 0'><b>FIG 3 asks a different question and its "
         "answer is mostly negative</b> &mdash; where the clusters sit relative to the "
         "LanA probabilistic language atlas. LanA is a prior about a LOCATION, not a "
         "measurement in a patient, so a cluster scoring high sits where language "
         "cortex usually is; whether it responded to language is FIG 1.</p>",
         "      <p style='margin:8px 0 0'><b>FIG 1 is cut at two K.</b> The held-out "
         "peak per feature set (11 / 12 / 14 / 13) and <b>K = 8</b>. They disagree, and "
         "the disagreement is the point &mdash; held-out variance cannot see a cluster "
         "that is one patient's electrode strip, because splitting a cohort until each "
         "patient has their own component fits held-out data perfectly well.</p>",
         "    </div>"]

    missing, untracked = [], []
    for png in figs:
        stem = png.with_suffix("").name
        is1 = stem.startswith("FIG1")
        k = int(stem.split("_K")[-1])
        if is1:
            tag = stem[4]
            fset = stem.split("_cnmf_")[0][6:]
            num, title = f"1{tag} &middot; K={k}", f"{fset}, convex NMF, K = {k}"
            bullets = fig1_bullets(png)
            alt = (f"four panels: held-out variance vs K, a schematic key, a "
                   f"generalization curve, and one block per cluster with its mean, "
                   f"two hemisphere renders and its patient composition")
        elif stem.startswith("FIG2"):
            num, title = f"2 &middot; K={k}", f"agreement, K = {k}"
            bullets = fig2_bullets(png)
            alt = ("six panels: pairwise agreement, per-cluster agreement and "
                   "per-electrode agreement, for feature sets and for algorithms")
        else:
            fset = stem.split("_K")[0][len("FIG3_lana_"):]
            num, title = f"3 &middot; K={k}", f"LanA language atlas, {fset}, K = {k}"
            bullets = fig3_bullets(png)
            alt = ("four panels: clusters ranked by LanA probability, per-cluster "
                   "loading against LanA, those correlations ranked, and LanA on this "
                   "electrode coverage")
        if tracked is not None and rel(png) not in tracked:
            untracked.append(rel(png))
            continue
        cap = FIGDIR / f"{stem}_caption.txt"
        li = "".join(f"<li>{b}</li>" for b in bullets) or "<li>numbers not on disk</li>"
        P.append(f"""
    <figure id="paper2-{stem}"><div class="cap"><div class="fignum">FIG {num}</div>
      <h4>{esc(title)}</h4>
      <ul>{li}</ul>
      <div class="runid"><code>{rel(png)}</code>"""
                 + (f" &middot; <code>{cap.name}</code>" if cap.exists() else "")
                 + f"""</div></div>
      <div class="imgwrap"><img data-fig="{rel(png)}" alt="{esc(alt)}"></div>
    </figure>""")

    if missing:
        P.append('    <div class="method" style="border-left:4px solid #c1121f">'
                 "<b>Not generated yet:</b> "
                 + ", ".join(f"<code>{esc(m)}</code>" for m in missing) + "</div>")
    if untracked:
        P.append('    <div class="method" style="border-left:4px solid #c1121f">'
                 "<b>On disk but not committed, so the site would 404 on them:</b> "
                 + ", ".join(f"<code>{esc(u)}</code>" for u in untracked) + "</div>")
    P.append(END)
    return "\n".join(P), untracked


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    a = ap.parse_args()
    if not FIGDIR.is_dir():
        raise SystemExit(f"no {FIGDIR}")
    block, untracked = build()
    if untracked:
        print("commit these or the site will 404 on them:")
        for u in untracked:
            print(f"    {u}")
    if not a.insert:
        print(block)
        print("\n(pass --insert to splice it into the site)")
        return 0
    if not SITE.exists():
        raise SystemExit(f"no {SITE}")
    s = SITE.read_text(encoding="utf-8")
    if BEGIN in s and END in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + block + s[j:]
        print("replaced the existing Paper 2 section")
    else:
        # in front of the gallery of what the stage produces: the paper figures are the
        # argument, the gallery is the inventory behind it
        anchor = ("<!-- BEGIN s2 gallery, generated by make_s2_gallery.py "
                  "- do not hand-edit -->")
        if anchor not in s:
            raise SystemExit("s2 gallery anchor not found - splice by hand this once")
        i = s.index(anchor)
        s = s[:i] + block + "\n\n    " + s[i:]
        print("inserted the Paper 2 section before the s2 gallery")
    SITE.write_text(s, encoding="utf-8")
    print(f"-> {SITE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
