#!/usr/bin/env python3
"""
make_lm_visualizer.py - LM_visualizer.html: the activity visualizer, per patient and per contact.

    "C:/Users/fanda/AppData/Local/Programs/Python/Python311/python.exe" make_lm_visualizer.py

Writes ~/lorafanda.github.io/LM_visualizer.html. Nothing else is touched.

WHAT IT IS. A copy of activity_visualizer.html - same data bundle (the activity_viz cube:
conditions x bands x contacts x warped time, one contact = one electrode contact of one
patient), same transport (bands, window, speed, video export), same expected-activity
track - with these things changed (2026-09-17):

  1. THE GLASS BRAIN of cluster_visualizer.html as the default surface: translucent bone
     pial on white, the contacts drawn as small spheres. The painted pial and the
     inflated surface of the activity visualizer stay as a switch. On glass the surface is
     not painted - the CONTACTS carry the colour: bwr of the mean of the selected band(s)
     over the current time window, on the same +-scale as the colour bar.
  2. PATIENTS. A 4-column grid with contact counts; one, several or all. Only the selected
     patients' contacts are drawn and plotted, in every condition.
  3. ONE CONTACT, BY SHAFT. A shaft dropdown (patient · shaft) over the selected patients,
     then a contact dropdown on that shaft. Up/down arrows step the contact and run on
     into the next shaft; left/right arrows step the shaft. The selected contact is
     marked with a RING drawn in the viewer's plane - black outside, bright green inside -
     so the brain and the dot under it stay visible; its line is drawn on top in the
     panel below, and its numbers are in the info panel.
  4. TWO PANELS. Top right: what is on screen. Bottom right: the concatenated ERSP -
     audio | picture | reading side by side, cue at the middle of each, one line per
     contact of the selected patients, the mean in black, the selected contact in green,
     the playhead moving with the brains.
  5. KEYS. h j k l hide and show the control panel, the concatenated ERSP, the info panel
     and the regions; space plays; up/down and left/right pick the contact and the shaft.
     The A-B band equation of the activity visualizer is gone.

The loading screen's turning brain is copied from cluster_visualizer.html at build time
(the inlined sprite strip), so the two pages open the same way.

THE RING. Niivue 0.69 exposes calculateMvpMatrix(_, [0,0,w,h], azimuth, elevation) and
calculateScreenPoint(xyz, mvp, [0,0,w,h]); every animation frame the selected contact is
projected with them onto a 2D canvas laid over each brain and the two circles are drawn
there. Nothing in the 3D scene is added for it, so nothing is occluded by it.

DATA. BUNDLE below - the activity_viz folder on the activity-visualizer branch, built by
scripts/precompute_activity_cube.py. To show a newer ERSP run: rebuild the pooling cache
it reads (04_FBM_Pooling/outputs/_dataset/pooling/_raw_ungated - it is keyed on
parameters, not on the ERSP files, so move the old one aside first), run the precompute,
commit the folder to that branch and push. The manifest's source_run is shown on the page.
"""
from __future__ import annotations

import re
from pathlib import Path

SITE_DIR = Path.home() / "lorafanda.github.io"
CLUSTER_VIZ = SITE_DIR / "cluster_visualizer.html"
DST = SITE_DIR / "LM_visualizer.html"

FALLBACK_SPIN = """  .spin { --w:132px; width:var(--w); height:var(--w); border-radius:50%;
    border:3px solid rgba(255,255,255,.12); border-top-color:var(--accent);
    animation:brainSpin 1.1s linear infinite; }
  @keyframes brainSpin { to { transform:rotate(360deg); } }"""


def spin_css() -> str:
    """The turning-brain sprite of the cluster visualizer: .spin {...} through the
    @keyframes line. A plain ring if the source moved."""
    try:
        s = CLUSTER_VIZ.read_text(encoding="utf-8")
    except OSError:
        return FALLBACK_SPIN
    m = re.search(r"^  \.spin \{ --w:132px;.*?^  @keyframes brainSpin \{[^\n]*\n", s, re.S | re.M)
    return m.group(0).rstrip("\n") if m else FALLBACK_SPIN


TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>LM Visualizer</title>
<!-- generated by 02_FBM_Clustering/make_lm_visualizer.py from activity_visualizer.html - do not hand-edit -->
<style>
  :root { --panel-bg: rgba(18,18,22,.84); --fg:#e8e8ec; --muted:#9aa0aa; --accent:#5ab0ff; --sel:#19ff6a; }
  * { box-sizing: border-box; }
  html, body { margin:0; height:100%; background:#000; color:var(--fg);
    font:13px/1.4 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif; overflow:hidden; }
  body.glass { background:#fff; }
  #brains { position:fixed; top:0; left:0; right:0; bottom:210px; display:flex; gap:2px; }
  .braincell { flex:1; min-width:0; position:relative; display:none; }
  .braincell.show { display:block; }
  .braincell canvas { width:100%; height:100%; display:block; }
  .braincell canvas.ov { position:absolute; inset:0; pointer-events:none; z-index:2; }
  .blabel { position:absolute; top:8px; left:0; right:0; text-align:center; z-index:2;
    font-size:12px; font-weight:600; letter-spacing:.5px; color:var(--muted); pointer-events:none; }
  #brains.single .blabel { display:none; }
  .dlBtn { position:absolute; top:8px; left:8px; z-index:3; width:30px; height:30px; padding:0;
    display:grid; place-items:center; cursor:pointer; color:#e8e8ec; border-radius:8px;
    background:rgba(18,18,22,.7); border:1px solid rgba(255,255,255,.14); }
  .dlBtn:hover { background:var(--accent); color:#001; }
  .dlBtn[disabled] { opacity:.5; cursor:progress; }

  .panel { position:fixed; background:var(--panel-bg); backdrop-filter:blur(8px);
    border:1px solid rgba(255,255,255,.08); border-radius:12px; padding:12px 14px;
    box-shadow:0 6px 24px rgba(0,0,0,.4); transition:opacity .18s ease; z-index:5; }
  .panel.hidden { opacity:0; pointer-events:none; }

  #controls { top:14px; left:14px; width:336px; }
  #controls h2 { cursor:pointer; user-select:none; display:flex; align-items:center; gap:6px;
    margin:0 0 8px; font-size:13px; font-weight:600; letter-spacing:.3px; }
  #ctlChevron { margin-left:auto; font-size:11px; opacity:.7; }
  #ctlBody { overflow:hidden; overflow-y:auto; max-height:calc(100vh - 80px); opacity:1;
    transition:max-height .22s ease, opacity .18s ease; }
  #controls.collapsed #ctlBody { max-height:0; opacity:0; }
  #controls.collapsed h2 { margin-bottom:0; }
  #controls .grp { margin:10px 0 0; }
  #controls .grp > label.title { display:block; font-size:11px; text-transform:uppercase;
    letter-spacing:.6px; color:var(--muted); margin-bottom:5px; }
  .bands { display:grid; grid-template-columns:repeat(4, 1fr); gap:3px 6px; }
  .pats { display:grid; grid-template-columns:repeat(4, 1fr); gap:2px 4px; font-size:10.5px; }
  .bands label, .conds label, .pats label { display:flex; align-items:center; gap:4px; cursor:pointer;
    padding:1px 0; white-space:nowrap; min-width:0; }
  .pats label span.id { overflow:hidden; text-overflow:ellipsis; letter-spacing:-.1px; }
  .bands input, .conds input, .pats input { accent-color:var(--accent); margin:0; }
  .conds { display:flex; gap:12px; flex-wrap:wrap; }
  .row { display:flex; align-items:center; gap:8px; margin-top:6px; }
  .row label { color:var(--muted); min-width:54px; }
  .row input[type=range] { flex:1; accent-color:var(--accent); }
  .row .val { min-width:42px; text-align:right; font-variant-numeric:tabular-nums; }
  .row select { flex:1; min-width:0; background:#101318; color:var(--fg); border:1px solid rgba(255,255,255,.14);
    border-radius:6px; padding:3px 4px; font:inherit; font-size:12px; }
  button.link { background:none; border:none; color:var(--accent); cursor:pointer; padding:0; font-size:12px; }
  button.step { width:26px; height:24px; padding:0; border-radius:6px; cursor:pointer; color:var(--fg); flex:none;
    background:#101318; border:1px solid rgba(255,255,255,.14); font-size:11px; }
  button.step:hover { border-color:var(--accent); }
  .seg { display:flex; gap:4px; }
  .seg button { flex:1; padding:4px 0; border-radius:6px; cursor:pointer; color:var(--muted); font:inherit; font-size:12px;
    background:#101318; border:1px solid rgba(255,255,255,.14); }
  .seg button.on { color:#001; background:var(--accent); border-color:var(--accent); font-weight:600; }
  .seg.mini button { padding:2px 0; font-size:11px; }
  #concat h3 .seg { margin-left:10px; }
  #concat h3 .seg button { flex:none; padding:1px 8px; font-size:11px; }
  .braincell.pickable canvas:not(.ov) { cursor:crosshair; }

  #transport { bottom:16px; left:14px; width:min(760px, calc(100vw - 500px)); display:flex; flex-direction:column; gap:8px; }
  .trow { display:flex; align-items:center; gap:14px; }
  #playBtn { width:42px; height:42px; flex:none; border-radius:50%; border:none; cursor:pointer;
    background:var(--accent); color:#001; font-size:16px; display:grid; place-items:center; }
  #playBtn:hover { filter:brightness(1.1); }
  #scrub { accent-color:var(--accent); display:block; }
  #timeLabel { font-variant-numeric:tabular-nums; white-space:nowrap; flex:1; text-align:left; color:var(--muted); }
  #timeLabel b { color:var(--fg); }
  #annoTrack { display:block; width:100%; height:132px; }
  #annoTrack text { font-family:inherit; }
  #annoCaption { font-size:10px; color:var(--muted); line-height:1.35; margin-top:2px;
    border-top:1px solid rgba(255,255,255,.08); padding-top:4px; }
  #annoCaption b { color:#cdd3dc; }

  #info { top:14px; right:16px; width:300px; font-size:12px; }
  #info h3 { margin:0 0 6px; font-size:12px; font-weight:600; letter-spacing:.3px; }
  #info .kv { display:grid; grid-template-columns:78px 1fr; gap:2px 8px; }
  #info .kv .k { color:var(--muted); }
  #info .kv .v { font-variant-numeric:tabular-nums; word-break:break-all; }
  #info .sel { margin-top:8px; padding-top:6px; border-top:1px solid rgba(255,255,255,.1); }
  #info .sel b { color:var(--sel); }
  #info .cb { margin-top:8px; }
  #info .cb .bar { height:10px; border-radius:4px; border:1px solid rgba(255,255,255,.15);
    background:linear-gradient(to right,#0000ff,#ffffff 50%,#ff0000); }
  #info .cb .labs { display:flex; justify-content:space-between; font-size:10.5px; color:var(--muted); margin-top:2px; }

  #concat { bottom:16px; right:16px; width:460px; padding:10px 12px 8px; }
  #concat h3 { margin:0 0 6px; font-size:12px; font-weight:600; display:flex; gap:8px; align-items:baseline; }
  #concat h3 span { color:var(--muted); font-weight:400; font-size:11px; margin-left:auto; }
  #concat canvas { display:block; width:436px; height:196px; border-radius:6px; background:#fff; }
  #concat .note { font-size:10.5px; color:var(--muted); margin-top:4px; }

  #regionLegend { left:14px; bottom:16px; max-width:240px; max-height:48vh; overflow:auto; font-size:11px; display:none; }
  #regionLegend.on { display:block; }
  #regionLegend .sys { margin:7px 0 2px; font-size:9.5px; font-weight:700; text-transform:uppercase; letter-spacing:.5px; color:#aab0ba; }
  #regionLegend .ritem { display:flex; align-items:center; gap:7px; padding:1px 0 1px 4px; }
  #regionLegend .sw { width:12px; height:12px; border-radius:3px; flex:none; border:1px solid rgba(255,255,255,.25); }
  #hint { position:fixed; bottom:6px; left:8px; color:#5a5f68; font-size:11px; z-index:5; }

  #status { position:fixed; inset:0; display:grid; place-items:center; text-align:center; background:#000;
    color:var(--muted); font-size:15px; padding:24px; z-index:9; pointer-events:none;
    transition:opacity .45s ease, background-color .45s ease; }
  #status.staged { align-content:end; background:transparent; }
  #status.staged .spin { display:none; }
  #status.staged .statusText { font-size:12.5px; opacity:.85; color:#8a9098; }
  #status.gone { opacity:0; }
  #status.failed .spin { animation:none; }
  .statusWrap { display:grid; justify-items:center; gap:12px; }
{{SPIN_CSS}}
  @media (prefers-reduced-motion: reduce) { .spin { animation-duration:14s; } }
</style>
</head>
<body class="glass">
  <div id="brains">
    <div class="braincell show" data-cond="audio"><div class="blabel">Audio</div><canvas></canvas><canvas class="ov"></canvas></div>
    <div class="braincell show" data-cond="picture"><div class="blabel">Picture</div><canvas></canvas><canvas class="ov"></canvas></div>
    <div class="braincell show" data-cond="reading"><div class="blabel">Reading</div><canvas></canvas><canvas class="ov"></canvas></div>
  </div>

  <div id="status"><div class="statusWrap"><div class="spin" aria-hidden="true"></div>
    <div class="statusText" id="statusText">Loading the brain…</div></div></div>

  <div id="controls" class="panel">
    <h2 id="ctlToggle" title="Collapse / expand (c)">🧠 LM Visualizer <span id="ctlChevron">▾</span></h2>
    <div id="ctlBody">

    <div class="grp">
      <label class="title">Conditions (one brain each)</label>
      <div class="conds" id="conds"></div>
    </div>

    <div class="grp">
      <label class="title">Patients selected <button class="link" id="patsAll" style="margin-left:6px">all</button>
        <button class="link" id="patsNone" style="margin-left:6px">none</button></label>
      <div class="pats" id="pats"></div>
    </div>

    <div class="grp">
      <label class="title">Contact</label>
      <div class="row" style="margin-top:0">
        <label style="min-width:44px">shaft</label>
        <select id="shaftSel"><option value="">— none —</option></select>
        <button class="step" id="shaftPrev" title="previous shaft (←)">◀</button>
        <button class="step" id="shaftNext" title="next shaft (→)">▶</button>
      </div>
      <div class="row">
        <label style="min-width:44px">contact</label>
        <select id="contactSel"><option value="">— none —</option></select>
        <button class="step" id="contactPrev" title="previous (↑)">▲</button>
        <button class="step" id="contactNext" title="next (↓)">▼</button>
      </div>
      <div class="row" style="margin-top:4px">
        <label style="min-width:44px">order</label>
        <div class="seg mini" id="orderSeg" style="flex:1">
          <button data-order="shaft" class="on" title="shaft by shaft, contact by contact">by shaft</button>
          <button data-order="rank" title="strongest first: mean of the selected bands in the current window, averaged over the shown conditions">by response</button>
        </div>
      </div>
      <div class="note" id="orderNote" style="font-size:10.5px;color:var(--muted);margin-top:3px">click a dot on a brain to select it</div>
    </div>

    <div class="grp">
      <div class="row" style="margin-bottom:5px">
        <label class="title" style="margin:0;flex:1">Frequency bands (Hz)</label>
        <button class="link" id="bandsAll">all</button>
        <button class="link" id="bandsNone">none</button>
      </div>
      <div class="bands" id="bands"></div>
    </div>

    <div class="grp">
      <label class="title">Window &amp; display</label>
      <div class="row"><label>Width</label>
        <input type="range" id="width" min="1" max="120" step="1">
        <span class="val" id="widthVal"></span></div>
      <div class="row"><label>Speed</label>
        <input type="range" id="speed" min="0.1" max="4" step="0.1" value="1">
        <span class="val" id="speedVal">1.0×</span></div>
      <div class="row"><label>Color ±</label>
        <input type="range" id="clim" min="1" max="12" step="0.5">
        <span class="val" id="climVal"></span></div>
      <div class="row"><label>Surface</label>
        <div class="seg" id="surfSeg" style="flex:1">
          <button data-surf="glass" class="on">glass</button>
          <button data-surf="pial">pial</button>
          <button data-surf="inflated">inflated</button>
        </div>
      </div>
      <div class="row">
        <label style="min-width:auto"><input type="checkbox" id="showElec" checked> contacts</label>
        <label style="min-width:auto;margin-left:10px"><input type="checkbox" id="showRegions"> regions</label>
        <label style="min-width:auto;margin-left:10px"><input type="checkbox" id="loop" checked> loop</label>
      </div>
      <div class="row"><label>Dot size</label>
        <input type="range" id="dotR" min="0.8" max="4" step="0.1" value="1.8">
        <span class="val" id="dotRVal">1.8</span></div>
      <div class="row"><label>View</label>
        <div class="seg mini" id="viewSeg" style="flex:1">
          <button data-view="90,0">L lateral</button><button data-view="270,0">R lateral</button>
          <button data-view="0,90">top</button><button data-view="180,0">front</button><button data-view="0,0">back</button>
        </div></div>
      <div class="row"><label>Hemi</label>
        <div class="seg mini" id="hemiSeg" style="flex:1">
          <button data-hemi="both" class="on">both</button><button data-hemi="lh">left only</button><button data-hemi="rh">right only</button>
        </div></div>
    </div>
    </div><!-- /#ctlBody -->
  </div>

  <div id="info" class="panel">
    <h3>What is on screen</h3>
    <div class="kv" id="infoKV"></div>
    <div class="sel" id="infoSel">no contact selected — pick a shaft and a contact, or ↑ ↓ ← →</div>
    <div class="cb"><div class="bar"></div>
      <div class="labs"><span id="cbLo">−6</span><span id="cbMode">ERSP dB · mean of selected bands in the window</span><span id="cbHi">+6</span></div></div>
  </div>

  <div id="concat" class="panel">
    <h3>Concatenated ERSP
      <div class="seg" id="plotSeg"><button data-plot="lines" class="on">lines</button><button data-plot="spectro" title="the selected contact's ERSP, 0-400 Hz">spectrogram</button></div>
      <span id="concatNote"></span></h3>
    <canvas id="concatCanvas" width="872" height="392"></canvas>
    <div class="note" id="concatCaption">one thin line per contact of the selected patients · black = mean · green = selected contact · cue at the middle of each block</div>
  </div>

  <div id="transport" class="panel">
    <div class="trow">
      <button id="playBtn" title="Play / pause (space)">▶</button>
      <div id="timeLabel"></div>
    </div>
    <input type="range" id="scrub" min="0" max="299" step="1" value="0">
    <svg id="annoTrack" preserveAspectRatio="none" viewBox="0 0 1000 132"></svg>
    <div id="annoCaption"></div>
  </div>

  <div id="regionLegend" class="panel"></div>
  <div id="hint">drag = rotate · scroll = zoom · click a dot = select · <b>h j k l</b> = hide controls / ERSP / info / regions · <b>space</b> = play · <b>↑ ↓</b> = contact · <b>← →</b> = shaft</div>

<script type="module">
import { Niivue, NVMesh } from "https://unpkg.com/@niivue/niivue@0.69.0/dist/index.js";

const BRANCH = "activity-visualizer";
// ?bundle=http://localhost:8000/02_FBM_Clustering/outputs/250_recon/fsaverage/activity_viz/
// points the page at a local copy (python -m http.server 8000 in the analysis repo) to
// check a rebuilt bundle before it is pushed.
const BUNDLE = new URLSearchParams(location.search).get("bundle")
  || `https://raw.githubusercontent.com/lorafanda/Analysis_LoraFanda/${BRANCH}/02_FBM_Clustering/outputs/250_recon/fsaverage/activity_viz/`;
const $ = (id) => document.getElementById(id);
const statusEl = $("status");
const setStatus = (t) => { const e = $("statusText"); if (e) e.textContent = t; };
const fail = (msg) => { statusEl.style.display = "grid"; statusEl.classList.remove("gone", "staged");
  statusEl.classList.add("failed"); $("statusText").innerHTML = msg; console.error(msg); };
function stageStatus(t) { statusEl.classList.add("staged"); setStatus(t); }
function hideStatus() { statusEl.classList.add("gone"); setTimeout(() => { statusEl.style.display = "none"; }, 500); }

async function fetchBin(url, dtype) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url} → HTTP ${r.status}`);
  const buf = await r.arrayBuffer();
  return dtype === "uint16" ? new Uint16Array(buf) : dtype === "float32" ? new Float32Array(buf)
       : dtype === "float16" ? decodeF16(new Uint16Array(buf)) : new Uint8Array(buf);
}
const _F16LUT = (() => {
  const t = new Float32Array(65536);
  for (let h = 0; h < 65536; h++) {
    const s = (h & 0x8000) >> 15, e = (h & 0x7C00) >> 10, f = h & 0x03FF;
    t[h] = e === 0 ? (s ? -1 : 1) * Math.pow(2, -14) * (f / 1024)
         : e === 0x1F ? (f ? NaN : (s ? -Infinity : Infinity)) : (s ? -1 : 1) * Math.pow(2, e - 15) * (1 + f / 1024);
  }
  return t;
})();
function decodeF16(u16) { const out = new Float32Array(u16.length); for (let i = 0; i < u16.length; i++) out[i] = _F16LUT[u16[i]]; return out; }

function bwr(t) { if (t <= 0.5) { const u = t*2; return [u, u, 1]; } const u = (t-0.5)*2; return [1, 1-u, 1-u]; }
function bwr255(val, vmax) { const t = Math.max(0, Math.min(1, (val + vmax)/(2*vmax))), c = bwr(t); return [Math.round(c[0]*255), Math.round(c[1]*255), Math.round(c[2]*255)]; }

// glass, as cluster_visualizer.html does it: a UNIFORM rgba255 at load time takes the
// mesh-level opacity path; a per-vertex buffer (the painted surfaces) bypasses it.
const GLASS_RGBA = [205, 198, 190, 30];
const GLASS_OPACITY = 0.18;
const INFLATED_SHIFT = 65;
const RING = { r: 11, outer: "#000", inner: "#19ff6a" };   // css px; drawn in the viewer's plane

let M, cube, projLhIdx, projLhW, projRhIdx, projRhW, CONTACTS = [], REG = null, REGCOL = {};
const BRAIN_CONDS = ["audio", "picture", "reading"];
const BR = {};
const state = {
  conds: new Set(BRAIN_CONDS), bands: new Set(),
  center: 0, width: 15, vmax: 6, playing: false, speed: 1.0, loop: true,
  surf: "glass", showElec: true, showRegions: false, dotR: 1.8,
  patients: new Set(), sel: -1,
  order: "shaft",      // contact dropdown and arrows: "shaft" (by shaft) or "rank" (strongest first)
  plot: "lines",       // the bottom-right panel: per-contact lines or the selected contact's spectrogram
  hemi: "both",        // "both" | "lh" | "rh": the other hemisphere and its contacts are hidden
};
let RANKED = [], RANKVAL = new Map();   // rank mode: contacts strongest first, and their values
const visibleConds = () => BRAIN_CONDS.filter(c => state.conds.has(c));
const isGlass = () => state.surf === "glass";

let PATIENTS = [], PAT_COUNT = {}, PRESENT = {};
let SEL_LIST = [];     // contact indices of the selected patients, shaft by shaft
let SHAFTS = [];       // [{key, patient, shaft, contacts:[idx...]}] over the selected patients
const shaftOf = (el) => String(el).replace(/[\s_-]*\d+$/, "");
const numOf = (el) => { const m = String(el).match(/(\d+)$/); return m ? +m[1] : 0; };

async function loadBundle() {
  setStatus("Loading the cube…");
  M = await (await fetch(BUNDLE + "manifest.json")).json();
  const f = M.files;
  [cube, projLhIdx, projLhW, projRhIdx, projRhW] = await Promise.all([
    fetchBin(BUNDLE + f.cube.name, f.cube.dtype || "float32"),
    fetchBin(BUNDLE + f.proj_lh_idx.name, "uint16"), fetchBin(BUNDLE + f.proj_lh_w.name, "float32"),
    fetchBin(BUNDLE + f.proj_rh_idx.name, "uint16"), fetchBin(BUNDLE + f.proj_rh_w.name, "float32"),
  ]);
  try { CONTACTS = await (await fetch(BUNDLE + "contacts.json")).json(); } catch (e) { CONTACTS = []; }
  if (M.region_files) {
    const rf = M.region_files;
    try {
      const [el, er, fl, fr] = await Promise.all([fetchBin(BUNDLE+rf.edge_lh,"uint8"), fetchBin(BUNDLE+rf.edge_rh,"uint8"), fetchBin(BUNDLE+rf.fill_lh,"uint8"), fetchBin(BUNDLE+rf.fill_rh,"uint8")]);
      REG = { edgelh:el, edgerh:er, filllh:fl, fillrh:fr }; REGCOL = {}; for (const r of (M.regions||[])) REGCOL[r.id] = r.color;
    } catch (e) { REG = null; }
  }
  state.vmax = M.vmax; state.center = Math.round(M.n_time * 0.5);
  for (let b = 0; b < M.n_band; b++) state.bands.add(b);
  PAT_COUNT = {};
  for (const ct of CONTACTS) PAT_COUNT[ct.patient_id] = (PAT_COUNT[ct.patient_id] || 0) + 1;
  PATIENTS = Object.keys(PAT_COUNT).sort();
  for (const p of PATIENTS) state.patients.add(p);
  for (const cond of BRAIN_CONDS) {
    const ci = M.conditions.indexOf(cond), pr = new Uint8Array(M.n_contact);
    for (let c = 0; c < M.n_contact; c++) { let ok = 0;
      for (let b = 0; b < M.n_band && !ok; b++) for (let t = 0; t < M.n_time; t++) { const v = cubeAt(ci,b,c,t); if (v===v) { ok = 1; break; } }
      pr[c] = ok; }
    PRESENT[cond] = pr;
  }
}
function cubeAt(cond, band, c, t) { return cube[((cond*M.n_band + band)*M.n_contact + c)*M.n_time + t]; }
function bandMean(condIdx, c, bandList, t0, t1) {
  let sum = 0, cnt = 0;
  for (const b of bandList) for (let t = t0; t <= t1; t++) { const v = cubeAt(condIdx, b, c, t); if (v === v) { sum += v; cnt++; } }
  return cnt ? sum/cnt : NaN;
}
function windowBins() {
  const center = Math.max(0, Math.min(M.n_time-1, Math.round(state.center))), half = Math.floor(state.width/2);
  return [Math.max(0, center-half), Math.min(M.n_time-1, center+half)];
}
function computeContactVals(condIdx) {
  const [t0, t1] = windowBins(), A = [...state.bands], cv = new Float32Array(M.n_contact);
  for (let c = 0; c < M.n_contact; c++) cv[c] = bandMean(condIdx, c, A, t0, t1);
  return cv;
}
function contactSeries(condIdx, c) {
  const A = [...state.bands], out = new Float32Array(M.n_time);
  for (let t = 0; t < M.n_time; t++) { let s = 0, n = 0; for (const b of A) { const v = cubeAt(condIdx, b, c, t); if (v === v) { s += v; n++; } } out[t] = n ? s/n : NaN; }
  return out;
}

// ---- selection: patients -> shafts -> contacts -------------------------------------
function rebuildSelList() {
  const nat = (a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" });
  const by = new Map();
  for (let c = 0; c < CONTACTS.length; c++) {
    const ct = CONTACTS[c]; if (!state.patients.has(ct.patient_id)) continue;
    const key = ct.patient_id + " · " + shaftOf(ct.electrode);
    if (!by.has(key)) by.set(key, { key, patient: ct.patient_id, shaft: shaftOf(ct.electrode), contacts: [] });
    by.get(key).contacts.push(c);
  }
  SHAFTS = [...by.values()].sort((a, b) => nat(a.patient, b.patient) || nat(a.shaft, b.shaft));
  for (const s of SHAFTS) s.contacts.sort((i, j) => numOf(CONTACTS[i].electrode) - numOf(CONTACTS[j].electrode) || nat(CONTACTS[i].electrode, CONTACTS[j].electrode));
  SEL_LIST = SHAFTS.flatMap(s => s.contacts);
  if (state.sel >= 0 && !SEL_LIST.includes(state.sel)) state.sel = -1;
  fillShaftSel(); fillContactSel();
}
function shaftIndexOf(c) { return c < 0 ? -1 : SHAFTS.findIndex(s => s.contacts.includes(c)); }
function fillShaftSel() {
  const si = shaftIndexOf(state.sel), sel = $("shaftSel");
  sel.innerHTML = '<option value="">— none —</option>' + SHAFTS.map((s, i) => `<option value="${i}">${_esc(s.key)}  (${s.contacts.length})</option>`).join("");
  sel.value = si >= 0 ? String(si) : "";
}
let _shaftShown = -1;     // the shaft the contact dropdown lists (may hold no selected contact yet)
// rank mode: every selected contact, strongest first - the mean of the selected bands in
// the current window, averaged over the conditions shown. Recomputed when the window, the
// bands or the patients change (not on every playback frame - see refreshRank).
function rankContacts() {
  const conds = visibleConds(), cvs = conds.map(c => computeContactVals(M.conditions.indexOf(c)));
  RANKVAL = new Map();
  for (const c of SEL_LIST) { let s = 0, n = 0; for (const cv of cvs) { const v = cv[c]; if (v === v) { s += v; n++; } } RANKVAL.set(c, n ? s/n : NaN); }
  RANKED = SEL_LIST.slice().sort((a, b) => { const va = RANKVAL.get(a), vb = RANKVAL.get(b); if (va !== va) return 1; if (vb !== vb) return -1; return vb - va; });
}
function refreshRank() { if (state.order !== "rank") return; rankContacts(); fillContactSel(); }
const orderList = () => state.order === "rank" ? RANKED : SEL_LIST;
function fillContactSel(si) {
  const sel = $("contactSel");
  if (state.order === "rank") {
    const fmt = v => v === v ? (v >= 0 ? "+" : "") + v.toFixed(2) : "—";
    sel.innerHTML = '<option value="">— none —</option>' + RANKED.map((c, i) => `<option value="${c}">${i+1}. ${_esc(CONTACTS[c].patient_id)} · ${_esc(CONTACTS[c].electrode)}  ${fmt(RANKVAL.get(c))}</option>`).join("");
    sel.value = state.sel >= 0 ? String(state.sel) : "";
    return;
  }
  if (si === undefined) si = shaftIndexOf(state.sel);
  _shaftShown = si;
  const list = si >= 0 ? SHAFTS[si].contacts : [];
  sel.innerHTML = '<option value="">— none —</option>' + list.map(c => `<option value="${c}">${_esc(CONTACTS[c].electrode)}</option>`).join("");
  sel.value = (state.sel >= 0 && list.includes(state.sel)) ? String(state.sel) : "";
}
function stepContact(dir) {
  const L = orderList(); if (!L.length) return;
  let i = L.indexOf(state.sel);
  if (i < 0 && state.order === "shaft" && _shaftShown >= 0) { const l = SHAFTS[_shaftShown].contacts; i = L.indexOf(dir > 0 ? l[0] : l[l.length-1]) - dir; }
  i = i < 0 ? (dir > 0 ? 0 : L.length - 1) : (i + dir + L.length) % L.length;
  setSelected(L[i]);
}
function stepShaft(dir) {
  if (!SHAFTS.length) return;
  let si = shaftIndexOf(state.sel); if (si < 0) si = _shaftShown;
  si = si < 0 ? (dir > 0 ? 0 : SHAFTS.length - 1) : (si + dir + SHAFTS.length) % SHAFTS.length;
  setSelected(SHAFTS[si].contacts[0]);
}
function setSelected(c) {
  state.sel = c;
  fillShaftSel(); fillContactSel();
  updateElectrodes(); drawConcat(true); updateInfo();
}

// ---- painted surfaces (pial / inflated): the activity visualizer's projection ----
function computeCoverage(condIdx, hemisObj) {
  const present = PRESENT[M.conditions[condIdx]] || new Uint8Array(M.n_contact);
  for (const h of ["lh","rh"]) {
    const H = hemisObj[h], K = M.k_nearest, den = new Float32Array(H.nvert);
    for (let v = 0; v < H.nvert; v++) { let s = 0;
      for (let k = 0; k < K; k++) { const ci = H.idx[v*K+k]; if (present[ci] && state.patients.has(CONTACTS[ci].patient_id)) s += H.w[v*K+k]; }
      den[v] = s; }
    const pos = Float32Array.from(den).filter(x => x > 0).sort();
    const q = pos.length ? pos[Math.min(pos.length-1, Math.floor(pos.length*M.density_norm_q))] : 1;
    const alpha = new Float32Array(H.nvert), aMin=M.alpha_min, aMax=M.alpha_max, g=M.alpha_gamma;
    for (let v = 0; v < H.nvert; v++) { if (den[v] <= 0) { alpha[v] = 0; continue; } const dn = Math.min(1, den[v]/Math.max(q,1e-8)); alpha[v] = aMin + (aMax-aMin)*Math.pow(dn, g); }
    H.den = den; H.alpha = alpha;
  }
}
function colorBrain(cond) {
  const B = BR[cond]; if (!B || !B.hemis.lh) return;
  if (isGlass()) { B.nv.drawScene(); return; }
  const condIdx = M.conditions.indexOf(cond), cv = computeContactVals(condIdx);
  const gray = M.base_brain_gray_rgb, vmax = state.vmax, K = M.k_nearest;
  for (const h of ["lh","rh"]) {
    const H = B.hemis[h], rgba = H.rgba, edgeH = (state.showRegions && REG) ? REG["edge"+h] : null;
    for (let v = 0; v < H.nvert; v++) {
      let num = 0; const den = H.den[v];
      if (den > 0) for (let k = 0; k < K; k++) { const ci = H.idx[v*K+k], val = cv[ci]; if (val === val && state.patients.has(CONTACTS[ci].patient_id)) num += H.w[v*K+k] * val; }
      let r=gray[0], g=gray[1], b=gray[2];
      if (den > 0) { const val = num/den, t = Math.max(0, Math.min(1, (val + vmax)/(2*vmax))), c = bwr(t), a = H.alpha[v];
        r = gray[0]*(1-a)+c[0]*a; g = gray[1]*(1-a)+c[1]*a; b = gray[2]*(1-a)+c[2]*a; }
      const rid = edgeH ? edgeH[v] : 0;
      if (rid) { const col = REGCOL[rid]; if (col) { r = col[0]/255; g = col[1]/255; b = col[2]/255; } }
      const o = v*4; rgba[o] = (r*255)|0; rgba[o+1] = (g*255)|0; rgba[o+2] = (b*255)|0; rgba[o+3] = 255;
    }
    H.mesh.rgba255 = rgba; H.mesh.updateMesh(B.nv.gl);
  }
  B.nv.drawScene();
}
function applyLook() {
  const glass = isGlass();
  document.body.classList.toggle("glass", glass);
  for (const cond of BRAIN_CONDS) {
    const B = BR[cond]; if (!B) continue;
    try { B.nv.opts.meshXRay = 0; B.nv.opts.backColor = glass ? [1,1,1,1] : [0,0,0,1]; } catch (e) {}
    const o = glass ? GLASS_OPACITY : 1.0;
    for (const h of ["lh","rh"]) { const m = B.hemis[h] && B.hemis[h].mesh; if (!m) continue;
      try { if ("opacity" in m) m.opacity = o; if ("layerOpacity" in m) m.layerOpacity = o; if ("meshOpacity" in m) m.meshOpacity = o; } catch (e) {}
      try { B.nv.setMeshShader(m.id, glass ? "Phong" : "Matte"); } catch (e) {} }
    try { B.nv.drawScene(); } catch (e) {}
  }
}
function render() { for (const cond of visibleConds()) colorBrain(cond); if (isGlass() || state.showElec) updateElectrodes(false); updateTimeLabel(); drawConcatPlayhead(); updateInfo(); }

function binPhase(bin) {
  const phs = M.phases || [{name:"time", start:0, end:M.n_time}];
  for (const p of phs) if (bin < p.end || p === phs[phs.length-1]) { const pct = (bin - p.start) / Math.max(1, p.end - p.start) * 100; return { name: p.name, pct: Math.max(0, Math.min(100, pct)) }; }
}
function updateTimeLabel() {
  const [t0, t1] = windowBins(), c = Math.max(0, Math.min(M.n_time-1, Math.round(state.center))), p = binPhase(c);
  $("timeLabel").innerHTML = `<b>${p.name} ${p.pct.toFixed(0)}%</b> &nbsp;<span style="color:var(--muted)">warped · bins ${t0}–${t1}</span>`;
  $("scrub").value = c; updateTrackPlayhead(c);
}

// ---- expected-activity track (reference, not data), as in activity_visualizer ----
const VOICE_ONSET_PCT = 67, CUE_PCT = 50, TAIL_PCT = 85;
const LANES = [
  { key:"hg",    short:"High γ", hz:[70,150], color:"#e4572e" }, { key:"theta", short:"Theta", hz:[4,8], color:"#37b8a8" },
  { key:"delta", short:"Delta",  hz:[1,4],    color:"#2191a6" }, { key:"beta",  short:"Beta",  hz:[13,30], color:"#9aa6bd" },
  { key:"alpha", short:"Alpha",  hz:[8,12],   color:"#b8c0cf" },
];
const LANEIDX = Object.fromEntries(LANES.map((l,i)=>[l.key,i]));
function prodMarkers() { return [
  { lane:"hg", s:CUE_PCT, e:62, label:"preSMA/SMA initiation", sign:"+", style:"fuzzy" },
  { lane:"hg", s:CUE_PCT, e:VOICE_ONSET_PCT, label:"Phonological encoding (IFG)", sign:"+", style:"fuzzy" },
  { lane:"hg", s:VOICE_ONSET_PCT, e:TAIL_PCT, label:"Ventral sensorimotor articulation", sign:"+", style:"fuzzy" },
  { lane:"beta", s:45, e:TAIL_PCT, label:"Beta ERD (motor)", sign:"-", style:"trough" },
  { lane:"beta", s:TAIL_PCT, e:90, label:"Beta rebound", sign:"+", style:"bump" },
  { lane:"alpha", s:2, e:90, label:"Alpha processing ERD", sign:"-", style:"strip", faint:true },
]; }
const PERC = {
  audio: [ { lane:"hg", s:2, e:5, label:"Auditory onset (Heschl's/STG)", sign:"+", style:"tick" }, { lane:"hg", s:30, e:48, label:"Lexical–semantic retrieval", sign:"+", style:"fuzzy" },
    { lane:"theta", s:2, e:48, label:"Auditory syllabic tracking", sign:"+", style:"strip" }, { lane:"delta", s:2, e:48, label:"Prosodic / phrasal tracking", sign:"+", style:"strip" },
    { lane:"delta", s:40, e:50, label:"Semantic / N400 (ant. temporal)", sign:"-", style:"fuzzy" } ],
  picture: [ { lane:"hg", s:8, e:12, label:"Visual onset (occipital/fusiform)", sign:"+", style:"tick" }, { lane:"hg", s:10, e:25, label:"Lexical–semantic retrieval (early)", sign:"+", style:"fuzzy" },
    { lane:"hg", s:2, e:48, label:"Sustained visual", sign:"+", style:"strip", faint:true }, { lane:"delta", s:40, e:50, label:"Semantic / N400 (ant. temporal)", sign:"-", style:"fuzzy" } ],
  reading: [ { lane:"hg", s:2, e:5, label:"Visual onset", sign:"+", style:"tick" }, { lane:"hg", s:40, e:48, label:"Lexical–semantic retrieval (sentence-final blank)", sign:"+", style:"fuzzy" },
    { lane:"hg", s:2, e:48, label:"Sustained reading (visual)", sign:"+", style:"strip", faint:true }, { lane:"theta", s:2, e:48, label:"Syllabic tracking (read sentence)", sign:"+", style:"strip" },
    { lane:"delta", s:2, e:48, label:"Prosodic / phrasal tracking", sign:"+", style:"strip" }, { lane:"delta", s:40, e:50, label:"Semantic / N400 (ant. temporal)", sign:"-", style:"fuzzy" } ],
};
const _esc = (s)=>String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
function trackBlocks() { const v = visibleConds(); return v.length ? v : BRAIN_CONDS; }
function lanesLit() { const lit = new Set(), sel = [...state.bands].map(i => M.bands_hz[i]);
  for (const L of LANES) for (const [lo,hi] of sel) if (lo < L.hz[1] && hi > L.hz[0]) { lit.add(L.key); break; } return lit; }
const TK = { topH:18, laneH:19, gut:70 }; TK.bodyTop = TK.topH; TK.bodyH = LANES.length*TK.laneH; TK.bottom = TK.bodyTop + TK.bodyH;
const GUT_FRAC = TK.gut / 1000;
function segSVG(j, m, X, L) {
  const xs=X(m.s), xe=X(m.e), w=Math.max(0.6, xe-xs), y=TK.bodyTop + j*TK.laneH, pad=4, h=TK.laneH-2*pad, cy=y+TK.laneH/2, mid=(xs+xe)/2;
  const title=`<title>${_esc(`${m.label} · ${L.short} · ${m.sign==="+"?"expected power ↑":"expected power ↓ (ERD)"}`)}</title>`;
  if (m.style==="tick") return `<g>${title}<line x1="${mid}" y1="${y+2}" x2="${mid}" y2="${y+TK.laneH-2}" stroke="${L.color}" stroke-width="2.4"/><circle cx="${mid}" cy="${y+3}" r="2.2" fill="${L.color}"/></g>`;
  if (m.style==="strip") return `<rect x="${xs}" y="${y+pad}" width="${w}" height="${h}" rx="3" fill="${L.color}" opacity="${m.faint?0.16:0.40}">${title}</rect>`;
  if (m.style==="trough") return `<g>${title}<rect x="${xs}" y="${y+pad}" width="${w}" height="${h}" rx="3" fill="${L.color}" opacity="0.10"/><path d="M ${xs} ${cy} Q ${mid} ${y+TK.laneH-3} ${xe} ${cy}" fill="none" stroke="${L.color}" stroke-width="1.8" opacity="0.85"/></g>`;
  if (m.style==="bump") return `<g>${title}<path d="M ${xs} ${y+TK.laneH-4} Q ${mid} ${y+3} ${xe} ${y+TK.laneH-4}" fill="none" stroke="${L.color}" stroke-width="1.8" opacity="0.9"/></g>`;
  return `<rect x="${xs}" y="${y+pad}" width="${w}" height="${h}" rx="3" fill="url(#g_${L.key})" opacity="0.85">${title}</rect>`;
}
function renderTrack() {
  const svg = $("annoTrack"); if (!svg) return;
  const blocks = trackBlocks(), nB = blocks.length, bw = (1000-TK.gut)/nB, lit = lanesLit(), xOf = (i,p)=> TK.gut + i*bw + p/100*bw;
  const curPct = Math.max(0, Math.min(100, Math.round(state.center)/(M.n_time-1)*100));
  let s = "<defs>";
  for (const L of LANES) s += `<linearGradient id="g_${L.key}"><stop offset="0" stop-color="${L.color}" stop-opacity="0"/><stop offset="0.5" stop-color="${L.color}" stop-opacity="0.8"/><stop offset="1" stop-color="${L.color}" stop-opacity="0"/></linearGradient>`;
  s += "</defs>";
  blocks.forEach((cond, i) => {
    const X = (p)=>xOf(i,p);
    s += `<rect x="${X(0)}" y="${TK.bodyTop}" width="${X(50)-X(0)}" height="${TK.bodyH}" fill="#5ab0ff" opacity="0.06"/><rect x="${X(50)}" y="${TK.bodyTop}" width="${X(100)-X(50)}" height="${TK.bodyH}" fill="#ffb45a" opacity="0.06"/>`;
    s += `<rect x="${X(42)}" y="${TK.bodyTop}" width="${X(58)-X(42)}" height="${TK.bodyH}" fill="#ffffff" opacity="0.05"/><rect x="${X(85)}" y="${TK.bodyTop}" width="${X(100)-X(85)}" height="${TK.bodyH}" fill="#000000" opacity="0.16"/>`;
    if (i>0) { const dxv=TK.gut+i*bw; s += `<line x1="${dxv}" y1="0" x2="${dxv}" y2="${TK.bottom+2}" stroke="#ffffff" stroke-opacity="0.18"/>`; }
    s += `<text x="${X(50)}" y="12" text-anchor="middle" font-size="10" font-weight="600" fill="#cdd3dc">${_esc(cond[0].toUpperCase()+cond.slice(1))}</text>`;
    for (let j=0;j<LANES.length;j++){ const y=TK.bodyTop+j*TK.laneH; s += `<line x1="${X(0)}" y1="${y+TK.laneH}" x2="${X(100)}" y2="${y+TK.laneH}" stroke="#ffffff" stroke-opacity="0.05"/>`; }
    for (const m of prodMarkers().concat(PERC[cond]||[])) { const j=LANEIDX[m.lane]; if (j==null) continue; const L=LANES[j]; s += `<g opacity="${lit.has(L.key)?1:0.22}">${segSVG(j,m,X,L)}</g>`; }
    s += `<line x1="${X(50)}" y1="${TK.bodyTop-2}" x2="${X(50)}" y2="${TK.bottom+2}" stroke="#e8e8ec" stroke-width="1.5" opacity="0.85"/><text x="${X(50)}" y="${TK.bottom+10}" text-anchor="middle" font-size="8.5" fill="#e8e8ec">▲ “?” cue</text>`;
    s += `<line x1="${X(VOICE_ONSET_PCT)}" y1="${TK.bodyTop-2}" x2="${X(VOICE_ONSET_PCT)}" y2="${TK.bottom+2}" stroke="#ffd27f" stroke-width="1.2" stroke-dasharray="3 3" opacity="0.8"/><text x="${X(VOICE_ONSET_PCT)}" y="${TK.bottom+10}" text-anchor="middle" font-size="8" fill="#ffd27f">voice ${VOICE_ONSET_PCT}%</text>`;
    s += `<text x="${X(24)}" y="${TK.bottom+10}" text-anchor="middle" font-size="8" fill="#7f8794">PERCEPTION</text><text x="${X(78)}" y="${TK.bottom+10}" text-anchor="middle" font-size="8" fill="#7f8794">PRODUCTION</text>`;
    const px=X(curPct); s += `<line id="ph${i}" x1="${px}" y1="${TK.bodyTop-3}" x2="${px}" y2="${TK.bottom+2}" stroke="#ffffff" stroke-width="1.4" opacity="0.9"/>`;
  });
  for (let j=0;j<LANES.length;j++){ const L=LANES[j], y=TK.bodyTop+j*TK.laneH; s += `<g opacity="${lit.has(L.key)?1:0.45}"><text x="${TK.gut-6}" y="${y+TK.laneH/2+3}" text-anchor="end" font-size="9" font-weight="600" fill="${L.color}">${L.short}</text></g>`; }
  svg.innerHTML = s;
  const cap = $("annoCaption");
  if (cap) cap.innerHTML = `<b>Expected activity — reference, not measured.</b> Perception tags align proportionally across conditions; production tags are <b>fuzzy</b> because voice onset is <b>not anchored</b>. <b>50% = cue (“?”), not voice onset.</b>`;
}
function updateTrackPlayhead(bin) {
  const nB = trackBlocks().length, bw = (1000-TK.gut)/nB, pct = Math.max(0, Math.min(100, bin/(M.n_time-1)*100));
  for (let i=0;i<nB;i++){ const el=$("ph"+i); if (el){ const x=TK.gut + i*bw + pct/100*bw; el.setAttribute("x1",x); el.setAttribute("x2",x); } }
}

// ---- concatenated ERSP (bottom right) ---------------------------------------------
const CC = { W: 872, H: 392, padL: 52, padR: 10, padT: 22, padB: 26, gap: 10, maxLines: 700 };
let _ccBase = null;
// the selected contact's REAL ERSP - the matrix its exemplar figure is drawn from, 0-400 Hz
// at full frequency resolution - one block per condition, bwr on the colour scale. One
// small file per contact (activity_viz/ersp/c<i>.bin, scripts/precompute_contact_ersp.py),
// fetched when the contact is selected and kept.
const ERSP = { manifest: null, missing: false, cache: new Map(), loading: null };
async function erspManifest() {
  if (ERSP.manifest || ERSP.missing) return ERSP.manifest;
  try { const r = await fetch(BUNDLE + "ersp/manifest.json"); if (!r.ok) throw new Error(r.status); ERSP.manifest = await r.json(); }
  catch (e) { ERSP.missing = true; }
  return ERSP.manifest;
}
async function contactErsp(c) {
  if (ERSP.cache.has(c)) return ERSP.cache.get(c);
  const r = await fetch(BUNDLE + `ersp/c${c}.bin`); if (!r.ok) return null;
  const a = new Uint8Array(await r.arrayBuffer()); ERSP.cache.set(c, a); return a;
}
function spectroFrame(g, msg) {
  g.fillStyle = "#fff"; g.fillRect(0, 0, CC.W, CC.H);
  if (msg) { g.font = "12px sans-serif"; g.textBaseline = "top"; g.fillStyle = "#68727d"; g.textAlign = "center"; g.fillText(msg, CC.W/2, CC.H/2 - 6); }
}
async function drawSpectro() {
  const base = document.createElement("canvas"); base.width = CC.W; base.height = CC.H;
  const g = base.getContext("2d");
  const sel = state.sel;
  if (sel < 0) { spectroFrame(g, "select a contact to see its ERSP"); _ccBase = base; $("concatNote").textContent = "no contact selected"; drawConcatPlayhead(); return; }
  const man = await erspManifest();
  if (!man) { spectroFrame(g, "no per-contact ERSP in the bundle yet - run scripts/precompute_contact_ersp.py and push activity_viz/ersp/"); _ccBase = base; $("concatNote").textContent = ""; drawConcatPlayhead(); return; }
  spectroFrame(g, "loading…"); _ccBase = base; drawConcatPlayhead();
  const a = await contactErsp(sel);
  if (state.sel !== sel || state.plot !== "spectro") return;          // the user moved on
  if (!a) { spectroFrame(g, "no ERSP file for this contact"); _ccBase = base; drawConcatPlayhead(); return; }
  spectroFrame(g, null);
  const nB = BRAIN_CONDS.length, w = (CC.W - CC.padL - CC.padR - CC.gap*(nB-1)) / nB, h = CC.H - CC.padT - CC.padB;
  const nf = man.n_freq, nt = man.n_time, fTop = man.f_hz[1], vmin = man.vmin, vmax = man.vmax, span = vmax - vmin;
  g.font = "12px sans-serif"; g.textBaseline = "top"; g.fillStyle = "#68727d"; g.textAlign = "right";
  for (const f of [0, 100, 200, 300, 400]) { if (f > fTop + 3) continue; const y = CC.padT + h - (f / fTop) * h; g.fillText(String(f), CC.padL - 5, y - 7);
    g.strokeStyle = "#c9ced4"; g.beginPath(); g.moveTo(CC.padL - 3, y); g.lineTo(CC.padL, y); g.stroke(); }
  g.save(); g.translate(11, CC.padT + h/2); g.rotate(-Math.PI/2); g.textAlign = "center"; g.fillText("Hz", 0, 0); g.restore();
  const tile = document.createElement("canvas"); tile.width = nt; tile.height = nf;
  const tg = tile.getContext("2d"), img = tg.createImageData(nt, nf), px = img.data;
  const CI = { audio: man.conditions.indexOf("audio"), picture: man.conditions.indexOf("picture"), reading: man.conditions.indexOf("reading") };
  BRAIN_CONDS.forEach((cond, bi) => {
    const x0 = CC.padL + bi*(w + CC.gap), k = CI[cond], X = t => x0 + t/(M.n_time-1) * w;
    g.fillStyle = "#f4f6f8"; g.fillRect(x0, CC.padT, w, h);
    let any = false;
    if (k >= 0) {
      for (let f = 0; f < nf; f++) { const row = nf - 1 - f;               // 0 Hz at the bottom
        for (let t = 0; t < nt; t++) { const b = a[(k*nf + f)*nt + t], o = (row*nt + t)*4;
          if (!b) { px[o] = 244; px[o+1] = 246; px[o+2] = 248; px[o+3] = 255; continue; }
          any = true; const v = vmin + (b - 1) / 254 * span, c = bwr255(v, state.vmax);
          px[o] = c[0]; px[o+1] = c[1]; px[o+2] = c[2]; px[o+3] = 255; } }
      tg.putImageData(img, 0, 0);
      g.imageSmoothingEnabled = false; g.drawImage(tile, x0, CC.padT, w, h); g.imageSmoothingEnabled = true;
    }
    if (!any) { g.fillStyle = "#9aa0aa"; g.textAlign = "center"; g.fillText("no data in this condition", x0 + w/2, CC.padT + h/2 - 6); }
    g.strokeStyle = "#c9ced4"; g.lineWidth = 1; g.strokeRect(x0 + .5, CC.padT + .5, w - 1, h - 1);
    g.fillStyle = "#1b232c"; g.textAlign = "center"; g.fillText(cond, x0 + w/2, 4);
    const pb = (M.phases && M.phases[0]) ? M.phases[0].end : M.n_time/2;
    g.strokeStyle = "#1b232c"; g.setLineDash([4, 3]); g.beginPath(); g.moveTo(X(pb), CC.padT); g.lineTo(X(pb), CC.padT + h); g.stroke(); g.setLineDash([]);
    g.fillStyle = "#68727d"; g.fillText("cue", X(pb), CC.padT + h + 4);
    g.textAlign = "left"; g.fillText(M.phases ? M.phases[0].name : "", x0 + 3, CC.padT + h + 4);
    g.textAlign = "right"; g.fillText(M.phases ? M.phases[1].name : "", x0 + w - 3, CC.padT + h + 4);
  });
  _ccBase = base;
  const ct = CONTACTS[sel];
  $("concatNote").textContent = `${ct.patient_id} · ${ct.electrode} · 0–${Math.round(fTop)} Hz · bwr ±${state.vmax} dB`;
  drawConcatPlayhead();
}
function drawConcat(full) {
  if (!full && _ccBase) { drawConcatPlayhead(); return; }
  $("concatCaption").textContent = state.plot === "spectro"
    ? "the selected contact's ERSP, 0–400 Hz over warped time, one block per condition · cue at the middle · the window shaded"
    : "one thin line per contact of the selected patients · black = mean · green = selected contact · cue at the middle of each block";
  if (state.plot === "spectro") { drawSpectro(); return; }
  const base = document.createElement("canvas"); base.width = CC.W; base.height = CC.H;
  const g = base.getContext("2d");
  g.fillStyle = "#fff"; g.fillRect(0, 0, CC.W, CC.H);
  const blocks = BRAIN_CONDS, nB = blocks.length, w = (CC.W - CC.padL - CC.padR - CC.gap*(nB-1)) / nB, h = CC.H - CC.padT - CC.padB;
  const lim = state.vmax, Y = v => CC.padT + (1 - (Math.max(-lim, Math.min(lim, v)) + lim)/(2*lim)) * h;
  const list = SEL_LIST.slice(); let drawn = list;
  if (list.length > CC.maxLines) { const step = list.length / CC.maxLines; drawn = [];
    for (let i = 0; i < CC.maxLines; i++) drawn.push(list[Math.floor(i*step)]);
    if (state.sel >= 0 && !drawn.includes(state.sel)) drawn.push(state.sel); }
  g.font = "13px sans-serif"; g.textBaseline = "top";
  g.strokeStyle = "#c9ced4"; g.lineWidth = 1; g.fillStyle = "#68727d"; g.textAlign = "right";
  for (const v of [-lim, -lim/2, 0, lim/2, lim]) { const y = Y(v); g.beginPath(); g.moveTo(CC.padL-4, y); g.lineTo(CC.padL, y); g.stroke(); g.fillText(v.toFixed(v%1?1:0), CC.padL-6, y-7); }
  g.save(); g.translate(11, CC.padT + h/2); g.rotate(-Math.PI/2); g.textAlign = "center"; g.fillText("ERSP (dB)", 0, 0); g.restore();
  blocks.forEach((cond, bi) => {
    const x0 = CC.padL + bi*(w + CC.gap), ci = M.conditions.indexOf(cond), pr = PRESENT[cond], X = t => x0 + t/(M.n_time-1) * w;
    g.fillStyle = "#f4f6f8"; g.fillRect(x0, CC.padT, w, h); g.strokeStyle = "#c9ced4"; g.strokeRect(x0 + .5, CC.padT + .5, w - 1, h - 1);
    g.strokeStyle = "#dfe3e8"; g.beginPath(); g.moveTo(x0, Y(0)); g.lineTo(x0+w, Y(0)); g.stroke();
    g.fillStyle = "#1b232c"; g.textAlign = "center"; g.fillText(cond, x0 + w/2, 4);
    const mean = new Float64Array(M.n_time), cnt = new Uint32Array(M.n_time); let selSeries = null;
    g.lineWidth = 1; g.strokeStyle = "rgba(110,120,140,0.22)";
    for (const c of drawn) { if (!pr[c]) continue; const s = contactSeries(ci, c); if (c === state.sel) selSeries = s;
      g.beginPath(); let pen = false;
      for (let t = 0; t < M.n_time; t++) { const v = s[t]; if (v !== v) { pen = false; continue; } mean[t] += v; cnt[t]++; const x = X(t), y = Y(v); if (pen) g.lineTo(x, y); else { g.moveTo(x, y); pen = true; } }
      g.stroke(); }
    g.lineWidth = 2; g.strokeStyle = "#1b232c"; g.beginPath(); let pen = false;
    for (let t = 0; t < M.n_time; t++) { if (!cnt[t]) { pen = false; continue; } const x = X(t), y = Y(mean[t]/cnt[t]); if (pen) g.lineTo(x, y); else { g.moveTo(x, y); pen = true; } }
    g.stroke();
    if (selSeries) for (const [lw, col] of [[4.5, "#000"], [2.2, RING.inner]]) { g.lineWidth = lw; g.strokeStyle = col; g.beginPath(); pen = false;
      for (let t = 0; t < M.n_time; t++) { const v = selSeries[t]; if (v !== v) { pen = false; continue; } const x = X(t), y = Y(v); if (pen) g.lineTo(x, y); else { g.moveTo(x, y); pen = true; } }
      g.stroke(); }
    const pb = (M.phases && M.phases[0]) ? M.phases[0].end : M.n_time/2;
    g.strokeStyle = "#68727d"; g.lineWidth = 1; g.setLineDash([4, 3]); g.beginPath(); g.moveTo(X(pb), CC.padT); g.lineTo(X(pb), CC.padT + h); g.stroke(); g.setLineDash([]);
    g.fillStyle = "#68727d"; g.textAlign = "center"; g.fillText("cue", X(pb), CC.padT + h + 4);
    g.textAlign = "left"; g.fillText(M.phases ? M.phases[0].name : "", x0 + 3, CC.padT + h + 4);
    g.textAlign = "right"; g.fillText(M.phases ? M.phases[1].name : "", x0 + w - 3, CC.padT + h + 4);
  });
  _ccBase = base;
  $("concatNote").textContent = `${SEL_LIST.length} contacts of ${state.patients.size} patient${state.patients.size===1?"":"s"}` + (drawn.length < list.length ? ` · ${drawn.length} lines drawn (every ${(list.length/drawn.length).toFixed(1)}th)` : "");
  drawConcatPlayhead();
}
function drawConcatPlayhead() {
  if (!_ccBase) return;
  const cv = $("concatCanvas"), ctx = cv.getContext("2d"); ctx.drawImage(_ccBase, 0, 0);
  const nB = BRAIN_CONDS.length, w = (CC.W - CC.padL - CC.padR - CC.gap*(nB-1)) / nB, h = CC.H - CC.padT - CC.padB, [t0, t1] = windowBins(), c = Math.round(state.center);
  for (let bi = 0; bi < nB; bi++) { const x0 = CC.padL + bi*(w + CC.gap), X = t => x0 + t/(M.n_time-1) * w;
    ctx.fillStyle = "rgba(90,176,255,0.18)"; ctx.fillRect(X(t0), CC.padT, Math.max(1, X(t1) - X(t0)), h);
    ctx.strokeStyle = "#5ab0ff"; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(X(c), CC.padT); ctx.lineTo(X(c), CC.padT + h); ctx.stroke(); }
}

// ---- info (top right) -----------------------------------------------------------
function selectionLabel() {
  const b = [...state.bands].sort((x, y) => x - y);
  if (b.length === M.n_band) return "all bands";
  if (!b.length) return "no band";
  return b.map(i => `${M.bands_hz[i][0]}–${M.bands_hz[i][1]}`).join(", ") + " Hz";
}
function updateInfo() {
  const [t0, t1] = windowBins(), p = binPhase(Math.round(state.center));
  const shown = {}; for (const cond of visibleConds()) { let n = 0; for (const c of SEL_LIST) if (PRESENT[cond][c]) n++; shown[cond] = n; }
  const kv = [
    ["bundle", `${BRANCH} · ${(M.source_run || "").split("/").slice(-3).join("/")}`],
    ["cube", `${M.n_contact} contacts · ${M.n_band} bands · ${M.n_time} warped bins`],
    ["patients", `${state.patients.size} of ${PATIENTS.length}` + (state.patients.size <= 4 && state.patients.size ? ` (${[...state.patients].join(", ")})` : "")],
    ["contacts", `${SEL_LIST.length} on ${SHAFTS.length} shafts · shown ` + visibleConds().map(c => `${c[0]}:${shown[c]}`).join(" ")],
    ["bands", selectionLabel()],
    ["window", `${p.name} ${p.pct.toFixed(0)}% · bins ${t0}–${t1} (${state.width} wide)`],
    ["surface", state.surf + (isGlass() ? " · contacts coloured" : " · surface painted")],
    ["colour", `bwr ±${state.vmax} dB`],
  ];
  $("infoKV").innerHTML = kv.map(([k, v]) => `<div class="k">${k}</div><div class="v">${_esc(v)}</div>`).join("");
  $("cbHi").textContent = "+" + state.vmax; $("cbLo").textContent = "−" + state.vmax;
  const s = $("infoSel");
  if (state.sel < 0) { s.innerHTML = "no contact selected — pick a shaft and a contact, or ↑ ↓ ← →"; return; }
  const ct = CONTACTS[state.sel], si = shaftIndexOf(state.sel);
  const vals = visibleConds().map(cond => { const ci = M.conditions.indexOf(cond), [a, b] = windowBins(), v = bandMean(ci, state.sel, [...state.bands], a, b);
    return `${cond} ${v === v ? (v >= 0 ? "+" : "") + v.toFixed(2) : "—"}`; });
  s.innerHTML = `<b>${_esc(ct.patient_id)} · ${_esc(ct.electrode)}</b> &nbsp;<span style="color:var(--muted)">${ct.hemi} · ${ct.x.toFixed(0)}, ${ct.y.toFixed(0)}, ${ct.z.toFixed(0)} mm · ` +
    `shaft ${si+1}/${SHAFTS.length}, contact ${si >= 0 ? SHAFTS[si].contacts.indexOf(state.sel)+1 : "?"}/${si >= 0 ? SHAFTS[si].contacts.length : "?"}</span><br>` +
    `<span style="color:var(--muted)">in window:</span> ${vals.join(" &nbsp;")} dB`;
}

// ---- contacts: icospheres coloured bwr by the window value ------------------------
const [_ICO, _ICOF] = (() => {
  const PHI = (1 + Math.sqrt(5)) / 2;
  const V = [[-1,PHI,0],[1,PHI,0],[-1,-PHI,0],[1,-PHI,0],[0,-1,PHI],[0,1,PHI],[0,-1,-PHI],[0,1,-PHI],[PHI,0,-1],[PHI,0,1],[-PHI,0,-1],[-PHI,0,1]]
    .map(v => { const L = Math.hypot(v[0], v[1], v[2]); return [v[0]/L, v[1]/L, v[2]/L]; });
  const F0 = [[0,11,5],[0,5,1],[0,1,7],[0,7,10],[0,10,11],[1,5,9],[5,11,4],[11,10,2],[10,7,6],[7,1,8],[3,9,4],[3,4,2],[3,2,6],[3,6,8],[3,8,9],[4,9,5],[2,4,11],[6,2,10],[8,6,7],[9,8,1]];
  const mid = new Map(), F = [];
  const cut = (x, y) => { const key = x < y ? x + "_" + y : y + "_" + x; if (mid.has(key)) return mid.get(key);
    const va = V[x], vb = V[y]; let mx = (va[0]+vb[0])/2, my = (va[1]+vb[1])/2, mz = (va[2]+vb[2])/2; const L = Math.hypot(mx, my, mz) || 1;
    V.push([mx/L, my/L, mz/L]); mid.set(key, V.length - 1); return V.length - 1; };
  for (const [x, y, z] of F0) { const xy = cut(x, y), yz = cut(y, z), zx = cut(z, x); F.push([x, xy, zx], [y, yz, xy], [z, zx, yz], [xy, yz, zx]); }
  return [V, F];
})();
function buildContactMesh(B, cond) {
  const ci = M.conditions.indexOf(cond), pr = PRESENT[cond], cv = computeContactVals(ci), pts = [], tris = [], cols = []; let vi = 0;
  for (const c of SEL_LIST) {
    if (!pr[c] || !hemiOk(c)) continue;
    const ct = CONTACTS[c], v = cv[c], rgb = v === v ? bwr255(v, state.vmax) : [150, 150, 150], al = v === v ? 255 : 120, r = state.dotR;
    for (const o of _ICO) pts.push(ct.x + o[0]*r, ct.y + o[1]*r, ct.z + o[2]*r);
    for (const f of _ICOF) tris.push(vi + f[0], vi + f[1], vi + f[2]);
    for (let j = 0; j < _ICO.length; j++) cols.push(rgb[0], rgb[1], rgb[2], al);
    vi += _ICO.length;
  }
  return vi ? new NVMesh(new Float32Array(pts), new Uint32Array(tris), "contacts_"+cond, new Uint8Array(cols), 1.0, true, B.nv.gl) : null;
}
function updateElectrodes(draw = true) {
  for (const cond of BRAIN_CONDS) {
    const B = BR[cond]; if (!B) continue;
    if (B.elec) { try { B.nv.removeMesh(B.elec); } catch (e) {} B.elec = null; }
    const want = state.conds.has(cond) && CONTACTS.length && state.surf !== "inflated" && (isGlass() || state.showElec);
    if (want) { try { const m = buildContactMesh(B, cond); if (m) { B.nv.addMesh(m); B.elec = m; } } catch (e) { console.error("contact overlay failed:", e); } }
    if (draw) { try { B.nv.drawScene(); } catch (e) {} }
  }
}

// ---- hemisphere: hide the other side's surface and contacts ----------------------------
const hemiOk = (c) => state.hemi === "both" || CONTACTS[c].hemi === state.hemi;
function applyHemi() {
  for (const cond of BRAIN_CONDS) {
    const B = BR[cond]; if (!B || !B.hemis.lh) continue;
    for (const h of ["lh", "rh"]) { const m = B.hemis[h].mesh; if (m) m.visible = (state.hemi === "both" || state.hemi === h); }
  }
  updateElectrodes();
}
// camera presets, every brain at once (Niivue: azimuth 90 fills the view with the left
// hemisphere, 270 with the right, elevation 90 looks down)
function setView(az, el) {
  for (const cond of BRAIN_CONDS) { const B = BR[cond]; if (!B) continue; try { B.nv.setRenderAzimuthElevation(az, el); B.nv.drawScene(); } catch (e) {} }
}

// ---- click a dot to select it ---------------------------------------------------------
// The contacts are projected with the same MVP the ring uses; the nearest one within a
// few pixels of the click wins. A drag (rotating the brain) is not a click.
function pickAt(cond, clientX, clientY) {
  const B = BR[cond], nv = B.nv, gl = nv.gl, W = gl.canvas.width, H = gl.canvas.height, rect = gl.canvas.getBoundingClientRect();
  if (!W || !H || !rect.width) return;
  const sx = (clientX - rect.left) * (W / rect.width), sy = (clientY - rect.top) * (H / rect.height), tol = 14 * (W / rect.width);
  let mvp; try { mvp = nv.calculateMvpMatrix(null, [0, 0, W, H], nv.scene.renderAzimuth, nv.scene.renderElevation)[0]; } catch (e) { return; }
  const pr = PRESENT[cond]; let best = -1, bd = tol * tol, bz = Infinity;
  for (const c of SEL_LIST) {
    if (!pr[c] || !hemiOk(c)) continue;
    const ct = CONTACTS[c], p = nv.calculateScreenPoint([ct.x, ct.y, ct.z], mvp, [0, 0, W, H]);
    const d = (p[0] - sx) ** 2 + (p[1] - sy) ** 2;
    if (d < bd || (d < tol * tol && Math.abs(d - bd) < 4 && p[2] < bz)) { best = c; bd = d; bz = p[2]; }
  }
  if (best >= 0) setSelected(best);
}
function wirePicking() {
  for (const cond of BRAIN_CONDS) {
    const B = BR[cond]; let down = null;
    B.cell.classList.add("pickable");
    B.cell.addEventListener("pointerdown", e => { if (e.button !== 0 || e.target.closest("button")) { down = null; return; } down = { x: e.clientX, y: e.clientY, t: performance.now() }; });
    B.cell.addEventListener("pointerup", e => { if (!down) return; const moved = Math.hypot(e.clientX - down.x, e.clientY - down.y), dt = performance.now() - down.t; down = null;
      if (moved > 4 || dt > 700 || state.surf === "inflated") return; pickAt(cond, e.clientX, e.clientY); });
  }
}

// ---- the ring: the selected contact projected into the viewer's plane -------------
// Redrawn every frame on a 2D canvas over each brain; the 3D scene is not touched.
function drawRings() {
  for (const cond of BRAIN_CONDS) {
    const B = BR[cond]; if (!B || !B.ov) continue;
    const ov = B.ov, gl = B.nv.gl, W = gl.canvas.width, H = gl.canvas.height;
    if (ov.width !== W || ov.height !== H) { ov.width = W; ov.height = H; }
    const ctx = ov.getContext("2d"); ctx.clearRect(0, 0, W, H);
    if (state.sel < 0 || !state.conds.has(cond) || state.surf === "inflated" || !W || !H || !hemiOk(state.sel)) continue;
    const ct = CONTACTS[state.sel];
    let p;
    try { const mvp = B.nv.calculateMvpMatrix(null, [0, 0, W, H], B.nv.scene.renderAzimuth, B.nv.scene.renderElevation)[0];
          p = B.nv.calculateScreenPoint([ct.x, ct.y, ct.z], mvp, [0, 0, W, H]); } catch (e) { continue; }
    if (!p || !(p[0] === p[0])) continue;
    const dpr = W / Math.max(1, ov.clientWidth), r = RING.r * dpr;
    ctx.lineWidth = 4 * dpr; ctx.strokeStyle = RING.outer; ctx.beginPath(); ctx.arc(p[0], p[1], r + 1.5 * dpr, 0, 2*Math.PI); ctx.stroke();
    ctx.lineWidth = 2.6 * dpr; ctx.strokeStyle = RING.inner; ctx.beginPath(); ctx.arc(p[0], p[1], r, 0, 2*Math.PI); ctx.stroke();
  }
  requestAnimationFrame(drawRings);
}

// ---- video export -------------------------------------------------------------------
const DL_ICON = '<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v12m0 0l-4-4m4 4l4-4M4 21h16"/></svg>';
async function snapshotTrack() {
  const svg = $("annoTrack").cloneNode(true); svg.querySelectorAll('[id^="ph"]').forEach(e => e.remove()); svg.setAttribute("xmlns", "http://www.w3.org/2000/svg");
  const img = new Image(); img.src = "data:image/svg+xml;base64," + btoa(unescape(encodeURIComponent(new XMLSerializer().serializeToString(svg)))); await img.decode(); return img;
}
function pickMime() { for (const m of ["video/webm;codecs=vp9", "video/webm;codecs=vp8", "video/webm"]) if (window.MediaRecorder && MediaRecorder.isTypeSupported(m)) return { mimeType: m }; return {}; }
let _recording = false;
async function recordCondition(cond) {
  if (_recording) return;
  if (!window.MediaRecorder) { alert("Video recording isn't supported in this browser (try Chrome)."); return; }
  const B = BR[cond]; if (!B || !B.hemis.lh) return;
  const canvas = B.cell.querySelector("canvas"), btn = B.cell.querySelector(".dlBtn"); if (btn) btn.disabled = true;
  _recording = true;
  const saveCenter = state.center, saveConds = new Set(state.conds);
  setPlaying(false); state.conds = new Set([cond]); renderTrack();
  const trackImg = await snapshotTrack(); state.conds = saveConds; renderTrack();
  const W = 720, capH = 24, brainAreaH = 470, trackH = Math.round(W * 132 / 1000);
  const comp = document.createElement("canvas"); comp.width = W; comp.height = capH + brainAreaH + trackH; const cx = comp.getContext("2d");
  const rec = new MediaRecorder(comp.captureStream(30), pickMime()); const chunks = []; rec.ondataavailable = (e) => { if (e.data.size) chunks.push(e.data); };
  const stopped = new Promise((res) => (rec.onstop = res)); rec.start();
  const DUR = Math.max(2000, Math.min(20000, 10000 / Math.max(0.1, state.speed))), t0 = performance.now(), sel = selectionLabel();
  const caption = `${cond[0].toUpperCase()+cond.slice(1)} · ${sel} · ${state.patients.size} patient${state.patients.size===1?"":"s"}`;
  await new Promise((resolve) => { const timer = setInterval(() => {
      const p = Math.min(1, (performance.now() - t0) / DUR); state.center = p * (M.n_time - 1); colorBrain(cond); updateElectrodes();
      cx.fillStyle = isGlass() ? "#fff" : "#000"; cx.fillRect(0, 0, W, comp.height);
      cx.fillStyle = isGlass() ? "#1b232c" : "#cdd3dc"; cx.font = "13px -apple-system,Segoe UI,Roboto,Arial,sans-serif"; cx.textBaseline = "middle"; cx.fillText(caption, 10, capH / 2);
      const cw = canvas.width || 1, ch = canvas.height || 1, sc = Math.min(W / cw, brainAreaH / ch), dw = cw * sc, dh = ch * sc, dx = (W - dw) / 2, dy = capH + (brainAreaH - dh) / 2;
      try { cx.drawImage(canvas, dx, dy, dw, dh); if (B.ov) cx.drawImage(B.ov, dx, dy, dw, dh); } catch (e) {}
      cx.drawImage(trackImg, 0, capH + brainAreaH, W, trackH);
      const pct = Math.round(state.center) / (M.n_time - 1) * 100, xph = (TK.gut + pct / 100 * (1000 - TK.gut)) / 1000 * W;
      cx.strokeStyle = isGlass() ? "#000" : "#fff"; cx.lineWidth = 2; cx.beginPath(); cx.moveTo(xph, capH + brainAreaH); cx.lineTo(xph, capH + brainAreaH + trackH); cx.stroke();
      if (p >= 1) { clearInterval(timer); resolve(); } }, 33); });
  rec.stop(); await stopped;
  const blob = new Blob(chunks, { type: "video/webm" }), a = document.createElement("a"); a.href = URL.createObjectURL(blob);
  a.download = `LM_${cond}_${sel.replace(/[^A-Za-z0-9]+/g, "")}.webm`; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(a.href), 5000);
  state.center = saveCenter; state.conds = saveConds; renderTrack(); render(); _recording = false; if (btn) btn.disabled = false;
}
function addDownloadButtons() {
  for (const cond of BRAIN_CONDS) { const B = BR[cond]; if (!B || B.cell.querySelector(".dlBtn")) continue;
    const btn = document.createElement("button"); btn.className = "dlBtn"; btn.title = `Download video (${cond})`; btn.innerHTML = DL_ICON; btn.onclick = () => recordCondition(cond); B.cell.appendChild(btn); }
}

// ---- animation loop -----------------------------------------------------------------
let lastT = null;
function tick(now) {
  if (!state.playing) { lastT = null; return; }
  if (lastT == null) lastT = now;
  const dt = (now - lastT)/1000; lastT = now;
  state.center += dt * (M.n_time / 10) * state.speed;
  if (state.center >= M.n_time-1) { if (state.loop) state.center = 0; else { state.center = M.n_time-1; setPlaying(false); } }
  render(); requestAnimationFrame(tick);
}
function setPlaying(p) { state.playing = p; $("playBtn").textContent = p ? "❚❚" : "▶"; if (p) requestAnimationFrame(tick); else refreshRank(); }

// ---- UI wiring ----------------------------------------------------------------------
function onSelectionChanged() {
  rebuildSelList(); refreshRank();
  for (const cond of BRAIN_CONDS) if (BR[cond].hemis.lh && !isGlass()) computeCoverage(M.conditions.indexOf(cond), BR[cond].hemis);
  render(); drawConcat(true); updateInfo();
}
const segWire = (id, attr, fn) => $(id).addEventListener("click", e => { const b = e.target.closest(`button[${attr}]`); if (!b) return;
  $(id).querySelectorAll("button").forEach(x => x.classList.toggle("on", x === b)); fn(b.getAttribute(attr)); });
function togglePanel(id) { $(id).classList.toggle("hidden"); }
function buildUI() {
  const conds = $("conds");
  BRAIN_CONDS.forEach(c => { const lab = document.createElement("label"); lab.innerHTML = `<input type="checkbox" value="${c}" checked> ${c}`; conds.appendChild(lab); });
  conds.addEventListener("change", e => { const c = e.target.value; if (e.target.checked) state.conds.add(c); else state.conds.delete(c);
    if (state.conds.size === 0) { state.conds.add(c); e.target.checked = true; } setLayout(); render(); renderTrack(); updateRegions(); });

  const pats = $("pats");
  // the count is in the tooltip: four columns leave no room for it beside an 8-character id
  pats.innerHTML = PATIENTS.map(p => `<label title="${_esc(p)} · ${PAT_COUNT[p]} contacts"><input type="checkbox" value="${_esc(p)}" checked><span class="id">${_esc(p)}</span></label>`).join("");
  pats.addEventListener("change", e => { const p = e.target.value; if (e.target.checked) state.patients.add(p); else state.patients.delete(p); onSelectionChanged(); });
  const setPats = on => { state.patients.clear(); pats.querySelectorAll("input").forEach(cb => { cb.checked = on; if (on) state.patients.add(cb.value); }); onSelectionChanged(); };
  $("patsAll").onclick = () => setPats(true); $("patsNone").onclick = () => setPats(false);

  $("shaftSel").onchange = e => { const si = e.target.value === "" ? -1 : +e.target.value; if (si < 0) { setSelected(-1); return; } fillContactSel(si); setSelected(SHAFTS[si].contacts[0]); };
  $("contactSel").onchange = e => setSelected(e.target.value === "" ? -1 : +e.target.value);
  $("contactPrev").onclick = () => stepContact(-1); $("contactNext").onclick = () => stepContact(+1);
  $("shaftPrev").onclick = () => stepShaft(-1); $("shaftNext").onclick = () => stepShaft(+1);
  segWire("orderSeg", "data-order", v => { state.order = v; const byShaft = v === "shaft";
    $("shaftSel").disabled = !byShaft; $("shaftPrev").disabled = !byShaft; $("shaftNext").disabled = !byShaft;
    $("orderNote").textContent = byShaft ? "click a dot on a brain to select it" : "strongest first at the current window · ↑ ↓ walk the ranking · click a dot to select it";
    if (!byShaft) rankContacts(); fillShaftSel(); fillContactSel(); });
  segWire("plotSeg", "data-plot", v => { state.plot = v; drawConcat(true); });
  segWire("viewSeg", "data-view", v => { const [az, el] = v.split(",").map(Number); setView(az, el); });
  segWire("hemiSeg", "data-hemi", v => { state.hemi = v; applyHemi(); drawConcat(false); updateInfo(); });

  const bandsEl = $("bands");
  M.bands_hz.forEach((b,i) => { const lab = document.createElement("label"); lab.innerHTML = `<input type="checkbox" value="${i}" checked> ${b[0]}–${b[1]}`; bandsEl.appendChild(lab); });
  bandsEl.addEventListener("change", e => { const i = +e.target.value; if (e.target.checked) state.bands.add(i); else state.bands.delete(i); refreshRank(); render(); renderTrack(); drawConcat(true); });
  const setAllBands = on => { state.bands.clear(); bandsEl.querySelectorAll("input").forEach((cb,i)=>{ cb.checked=on; if(on) state.bands.add(i); }); refreshRank(); render(); renderTrack(); drawConcat(true); };
  $("bandsAll").onclick = () => setAllBands(true); $("bandsNone").onclick = () => setAllBands(false);

  const width = $("width"); width.value = state.width; $("widthVal").textContent = state.width;
  width.oninput = () => { state.width = +width.value; $("widthVal").textContent = state.width; render(); };
  width.onchange = refreshRank;
  const speed = $("speed"); speed.oninput = () => { state.speed = +speed.value; $("speedVal").textContent = state.speed.toFixed(1)+"×"; };
  const clim = $("clim"); clim.value = state.vmax; $("climVal").textContent = "±"+state.vmax;
  clim.oninput = () => { state.vmax = +clim.value; $("climVal").textContent = "±"+state.vmax; render(); drawConcat(true); };
  const dotR = $("dotR"); dotR.oninput = () => { state.dotR = +dotR.value; $("dotRVal").textContent = state.dotR.toFixed(1); updateElectrodes(); };
  $("loop").onchange = e => state.loop = e.target.checked;
  $("surfSeg").addEventListener("click", e => { const b = e.target.closest("button[data-surf]"); if (b) switchSurface(b.dataset.surf); });
  $("showElec").onchange = e => { state.showElec = e.target.checked; updateElectrodes(); };
  $("showRegions").onchange = e => { state.showRegions = e.target.checked; updateRegions(); };
  if (!REG) $("showRegions").closest("label").style.display = "none";

  $("playBtn").onclick = () => setPlaying(!state.playing);
  const sc = $("scrub"); sc.max = M.n_time-1; sc.style.marginLeft = (GUT_FRAC*100) + "%"; sc.style.width = ((1-GUT_FRAC)*100) + "%";
  sc.oninput = (e) => { setPlaying(false); state.center = +e.target.value; render(); };
  sc.onchange = refreshRank;     // the ranking follows the window once the scrub is released
  const toggleCtl = () => { const c = $("controls").classList.toggle("collapsed"); $("ctlChevron").textContent = c ? "▸" : "▾"; };
  $("ctlToggle").onclick = toggleCtl;

  window.addEventListener("keydown", (e) => {
    const tag = e.target && e.target.tagName;
    if (/^(INPUT|SELECT|TEXTAREA)$/.test(tag) && e.target.type !== "range" && e.target.type !== "checkbox" && !/^Arrow/.test(e.key)) return;
    if (tag === "SELECT" && /^Arrow(Up|Down)$/.test(e.key)) return;    // let the dropdown do its own stepping
    if (e.key === "h") togglePanel("controls");
    else if (e.key === "j") togglePanel("concat");
    else if (e.key === "k") togglePanel("info");
    else if (e.key === "l") { const cb = $("showRegions"); cb.checked = !cb.checked; state.showRegions = cb.checked; updateRegions(); }
    else if (e.key === "c") toggleCtl();
    else if (e.key === " ") { e.preventDefault(); setPlaying(!state.playing); }
    else if (e.key === "ArrowUp") { e.preventDefault(); stepContact(-1); }
    else if (e.key === "ArrowDown") { e.preventDefault(); stepContact(+1); }
    else if (e.key === "ArrowLeft") { e.preventDefault(); stepShaft(-1); }
    else if (e.key === "ArrowRight") { e.preventDefault(); stepShaft(+1); }
  });
  renderTrack();
}

function bindMeshesFor(nvInst, hemisObj) {
  ["lh","rh"].forEach((h,i) => { const m = nvInst.meshes[i], idx = h==="lh"?projLhIdx:projRhIdx, w = h==="lh"?projLhW:projRhW, nvert = m.pts.length/3;
    hemisObj[h] = { mesh:m, idx, w, nvert, rgba:new Uint8Array(nvert*4) }; });
  if (state.surf === "inflated") [[-INFLATED_SHIFT, hemisObj.lh.mesh], [INFLATED_SHIFT, hemisObj.rh.mesh]].forEach(([dx, m]) => { const p = m.pts; for (let k=0;k<p.length;k+=3) p[k] += dx; m.updateMesh(nvInst.gl); });
}
function setLayout() {
  const vis = new Set(visibleConds());
  for (const cond of BRAIN_CONDS) BR[cond].cell.classList.toggle("show", vis.has(cond));
  $("brains").classList.toggle("single", vis.size === 1); fitBrains();
}
function fitBrains() {
  const t = $("transport"), vh = window.innerHeight || 800;
  let reserve = (t ? t.offsetHeight : 230) + 26; reserve = Math.max(180, Math.min(reserve, Math.round(vh * 0.55)));
  $("brains").style.bottom = reserve + "px";
  for (const cond of BRAIN_CONDS) { const B = BR[cond]; if (B && B.cell.classList.contains("show")) { try { B.nv.resizeListener(); } catch (e) {} } }
}
function meshSpecs(kind) {
  const inflated = kind === "inflated", spec = kind === "glass" ? { rgba255: GLASS_RGBA } : {};
  return [{ url: BUNDLE + (inflated ? M.hemis.lh.mesh_inflated : M.hemis.lh.mesh), ...spec }, { url: BUNDLE + (inflated ? M.hemis.rh.mesh_inflated : M.hemis.rh.mesh), ...spec }];
}
async function loadAllSurfaces(kind) {
  for (const cond of BRAIN_CONDS) { const B = BR[cond]; B.elec = null; [...B.nv.meshes].forEach(m => B.nv.removeMesh(m));
    await B.nv.loadMeshes(meshSpecs(kind)); bindMeshesFor(B.nv, B.hemis); if (kind !== "glass") computeCoverage(M.conditions.indexOf(cond), B.hemis); }
  applyLook();
  if (state.hemi !== "both") applyHemi();
}
async function switchSurface(kind) {
  if (kind === state.surf) return;
  state.surf = kind; $("surfSeg").querySelectorAll("button").forEach(b => b.classList.toggle("on", b.dataset.surf === kind));
  stageStatus(`Loading the ${kind} surface…`); statusEl.style.display = "grid"; statusEl.classList.remove("gone");
  await loadAllSurfaces(kind); render(); updateRegions(); hideStatus();
}
let _legendBuilt = false;
function buildRegionLegend() {
  if (_legendBuilt || !REG) return;
  const el = $("regionLegend"); let html = "", lastSys = null;
  for (const r of (M.regions || [])) { if (r.system !== lastSys) { html += `<div class="sys">${r.system}</div>`; lastSys = r.system; } const c = r.color; html += `<div class="ritem"><span class="sw" style="background:rgb(${c[0]},${c[1]},${c[2]})"></span>${r.name}</div>`; }
  el.innerHTML = html; _legendBuilt = true;
}
function updateRegions() { buildRegionLegend(); $("regionLegend").classList.toggle("on", !!(state.showRegions && REG && !isGlass())); render(); }

async function main() {
  try { await loadBundle(); } catch (e) { return fail(`Failed to load the data bundle.<br><small>${e.message}</small>`); }
  try {
    setStatus("Loading the brain…");
    for (const cond of BRAIN_CONDS) {
      const cell = document.querySelector(`.braincell[data-cond="${cond}"]`);
      const nvI = new Niivue({ backColor:[1,1,1,1], show3Dcrosshair:false, isColorbar:false, meshXRay:0.0, isOrientCube:false });
      nvI.attachToCanvas(cell.querySelector("canvas:not(.ov)")); nvI.setSliceType(nvI.sliceTypeRender);
      BR[cond] = { nv:nvI, cell, hemis:{}, ov: cell.querySelector("canvas.ov") };
    }
    await loadAllSurfaces("glass");
  } catch (e) { return fail(`Mesh load failed.<br><small>${e.message}</small>`); }
  try {
    rebuildSelList(); buildUI(); setLayout(); addDownloadButtons(); wirePicking();
    render(); drawConcat(true); updateInfo(); requestAnimationFrame(drawRings);
    window.addEventListener("resize", fitBrains); hideStatus();
    window.__viz = { BR, state, M, SHAFTS: () => SHAFTS, render, setLayout, fitBrains, renderTrack, updateElectrodes, updateRegions, switchSurface, recordCondition, setPlaying, setSelected, stepContact, stepShaft, drawConcat };
  } catch (e) { fail("Init error: " + e.message); throw e; }
}
main();
</script>
</body>
</html>
"""


def main() -> None:
    html = TEMPLATE.replace("{{SPIN_CSS}}", spin_css())
    DST.write_text(html, encoding="utf-8")
    print(f"wrote {DST}  ({len(html):,} chars)")


if __name__ == "__main__":
    main()
