#!/usr/bin/env python3
"""
make_kiss_tab.py - the KISS tab of analysis_status.html. Keep It Simple, Stupid.

Every illustrated explanation lives here, in plain words. The other tabs explain what
was DONE; this one explains what the words MEAN, once, so a term that reads as jargon
somewhere else has exactly one place to be looked up.

The rule for adding to it: whenever an illustrated explanation of a concept is asked
for, the figure goes in outputs/clustering/explainers/ and an entry goes in ENTRIES
below. Nothing else needs touching - the nav button, the index and the section are all
generated from that list.

    python make_kiss_tab.py            # write the fragment
    python make_kiss_tab.py --insert   # AND splice it into the site

Idempotent: the splice is delimited by HTML comments, so re-running replaces the tab
rather than stacking a second one.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
EXPL = ROOT / "outputs" / "clustering" / "explainers"
SITE = Path("C:/Users/fanda/lorafanda.github.io/analysis_status.html")
FIGROOT = "02_FBM_Clustering/outputs/clustering/explainers"

B_SEC = "<!-- BEGIN kiss tab, generated by make_kiss_tab.py - do not hand-edit -->"
E_SEC = "<!-- END kiss tab -->"
B_NAV = "<!-- BEGIN kiss nav -->"
E_NAV = "<!-- END kiss nav -->"

# ── the entries ─────────────────────────────────────────────────────────────
# id, short index label, the question in the form it was actually asked, the plain
# answer as a list of paragraphs, and the figures.
ENTRIES = [
    dict(
        id="kiss-three",
        label="The three algorithms",
        q="What is the actual difference between convex NMF, k-means and Ward?",
        body=[
            "All three take the same electrodes and put them into groups. What differs "
            "is <b>what a group is allowed to be</b>, and <b>how an electrode joins "
            "one</b>.",
            "<b>k-means.</b> Every electrode belongs to exactly one group. A group is "
            "summarised by the <i>average</i> of its members, and an electrode joins "
            "whichever average it is closest to. Move one electrode and the average "
            "moves, so it re-checks, and repeats until nothing moves.",
            "<b>Ward.</b> Same rule &mdash; one electrode, one group &mdash; but built "
            "the opposite way round. Start with every electrode alone, then repeatedly "
            "merge the <i>two groups whose merger costs the least extra spread</i>, and "
            "stop when K groups are left. Because it is a merge history, you can cut it "
            "at any K without refitting.",
            "<b>Convex NMF.</b> An electrode does not have to pick. It gets a "
            "<b>weight on every component</b> &mdash; 0.7 of one and 0.3 of another is "
            "a legal answer, and a real one. And each component is itself built out of "
            "real electrodes rather than being a free point in space.",
            "<b>The trap this figure is built to spring:</b> all three are shown on the "
            "<i>same twelve electrodes</i>, and all three put electrode <code>e5</code> "
            "in the wrong place, in the same way. That is not three bugs. It is what "
            "happens when a real electrode genuinely sits between two response types "
            "and the method is only allowed to name one of them.",
        ],
        figs=[("E.1", "convex NMF, step by step",
               "E1_cnmf_explained.png",
               "convex NMF explained on twelve synthetic electrodes: the loading matrix, "
               "the components as convex combinations of real electrodes, and the "
               "graded membership of the ambiguous electrode"),
              ("E.2", "k-means, on the same twelve electrodes",
               "E2_kmeans_explained.png",
               "k-means explained on the same twelve synthetic electrodes: centroids as "
               "means, nearest-centroid assignment, and the misassignment of e5"),
              ("E.3", "Ward, on the same twelve electrodes",
               "E3_ward_explained.png",
               "Ward hierarchical clustering on the same twelve synthetic electrodes: "
               "the merge history as a dendrogram and the same misassignment of e5")],
    ),
    dict(
        id="kiss-halves",
        label="_half1 and _half2",
        q="What are the _half1 / _half2 files, and why did they break the cohort?",
        body=[
            "Each electrode's trials are split into two halves and <b>each half is "
            "averaged separately</b>. If the two halves look like each other, the "
            "response is real. If they do not, it was noise that happened to average "
            "into a shape.",
            "So a half is a <b>check on an electrode</b>, not an extra electrode. There "
            "is no third recording site; there is one site whose trials were counted "
            "twice in two piles.",
            "<b>What went wrong.</b> The halves were being written next to the full "
            "cubes, and the loader globs <code>ERSP_matrix</code> for cubes. It found "
            "three files per electrode and believed all three. The cohort went from "
            "9,342 real cubes to 19,380 rows, and the responsiveness gate &mdash; which "
            "each half passes easily, because a half of a good electrode is still good "
            "&mdash; went from 35.1% to 96.9% without anything failing.",
            "The fix was to <b>move the files, not to filter them</b>: halves now live "
            "in <code>ERSP_halves/</code>, and nothing that globs "
            "<code>ERSP_matrix</code> can see them. Filtering by filename would have "
            "worked until the next naming convention.",
        ],
        figs=[("E.4", "what a split half is, and what it is not",
               "E4_what_the_halves_are.png",
               "illustration of splitting an electrode's trials into two halves, "
               "averaging each separately, and the difference between using them as a "
               "reliability check and mistaking them for extra electrodes")],
    ),
    dict(
        id="kiss-stability",
        label="What stability means",
        q="What does sweep_stability actually measure?",
        body=[
            "Not <i>is the fit good</i>. It measures <b>would I get the same clusters "
            "again</b>.",
            "It refits the same K many times on random 80% subsamples of the "
            "electrodes, and for every pair of electrodes asks: of the rounds where "
            "<i>both</i> were drawn, how often did they land in the same cluster? A "
            "pair only counts in a round where both were present &mdash; otherwise "
            "sitting out would look like disagreement.",
            "Each cluster's score is the average of that number across its own members. "
            "<b>1.0</b> means every pair stayed together every time it could have. "
            "<b>0.5</b> means the cluster is not a stable object. The number worth "
            "reading is the <b>minimum</b> across clusters, not the mean &mdash; one "
            "unstable cluster is the finding, and averaging hides it.",
        ],
        figs=[("E.5", "the consensus matrix, on six electrodes you can count by hand",
               "E5_sweep_stability.png",
               "four resampling rounds on six electrodes, the resulting consensus "
               "matrix, and how the per-cluster jaccard score is computed from its "
               "diagonal blocks")],
    ),
    dict(
        id="kiss-distinctions",
        label="Three easy confusions",
        q="Threshold vs argmax, convex NMF vs semi-NMF, graded vs convex &mdash; "
          "what is the difference?",
        body=[
            "All three are about the same object: the <b>loading matrix</b> a graded "
            "model returns, one row per electrode, one column per component.",
            "<b>1 &mdash; argmax vs threshold.</b> Argmax reads each row and keeps only "
            "its largest entry, which turns the graded answer back into a partition: "
            "every electrode in exactly one cluster, the gradedness thrown away at the "
            "last step. Threshold keeps <i>every</i> entry above some level, so an "
            "electrode can be in two clusters or in none. Argmax is what the current "
            "figures do, and it is why a graded model can end up reported as if it were "
            "k-means.",
            "<b>2 &mdash; convex NMF vs semi-NMF.</b> Both come from the same paper. "
            "Semi-NMF factorises <code>X &asymp; F G&prime;</code> with only "
            "<code>G</code> forced non-negative &mdash; <code>F</code> is free, so a "
            "component can be any shape at all. Convex NMF adds one more constraint: "
            "<code>X &asymp; G(W&prime;X)</code> with <code>W &ge; 0</code>, which "
            "forces each component to be a <b>weighted average of real electrodes</b>. "
            "Semi-NMF is graded without being convex.",
            "<b>3 &mdash; graded vs convex.</b> These get used as if they were the same "
            "word and they are not. <b>Convex</b> is about the COMPONENT: is it made of "
            "real data? <b>Graded</b> is about the ELECTRODE: may it belong partly to "
            "several? "
            "<b>k-means is already convex</b> &mdash; its centroid is literally the mean "
            "of its own members, which is a convex combination of real electrodes. So "
            "convexity is <i>not</i> what convex NMF buys over k-means. "
            "<b>Gradedness is.</b>",
        ],
        figs=[("E.6", "the same loading matrix, read three ways",
               "E6_three_distinctions.png",
               "three distinctions illustrated on one loading matrix: argmax versus "
               "threshold assignment, convex NMF versus semi-NMF factorisation, and "
               "graded membership versus convex components")],
    ),
    dict(
        id="kiss-corr",
        label="Spearman or Pearson",
        q="What is the difference between Spearman and Pearson for skewed data?",
        body=[
            "Both answer &ldquo;do these two go up together?&rdquo;, but they read "
            "different things. <b>Pearson</b> works on the values and measures how "
            "close the cloud is to a <i>straight line</i>. <b>Spearman</b> throws the "
            "values away, replaces each with its <b>rank</b>, and runs Pearson on "
            "those.",
            "So Spearman asks only <i>does y go up when x goes up</i>, never <i>by how "
            "much</i>. On skewed data that is usually the safer question, because one "
            "far-out value can drag a straight line a long way but is worth exactly one "
            "rank.",
            "<b>Rule of thumb:</b> if the question is &ldquo;do they go up "
            "together&rdquo;, use Spearman. If the SHAPE or the SIZE of the change is "
            "the thing being measured &mdash; a waveform, a lag, a slope &mdash; use "
            "Pearson. Panel D lists where each is used in this project and why; "
            "<code>lf_atlas_corr</code> defaults to Spearman and its docstring gives "
            "the reason.",
        ],
        figs=[("E.7", "one outlier, and one perfectly curved relationship",
               "E7_spearman_vs_pearson.png",
               "Spearman versus Pearson on skewed data: a single leverage point that "
               "makes Pearson report a strong correlation where none exists, a "
               "monotone but non-linear relationship where Spearman reads 1.0, the "
               "value-to-rank transform, and where each is used in this project")],
    ),
]

NAV = ('    <button class="nk" data-t="kiss"><span class="dot"></span>'
       "KISS &middot; plain words</button>")
CSS = "  .nk .dot{background:#c98f00}"


def build() -> str:
    idx = " &nbsp;&middot;&nbsp; ".join(
        f'<a href="#{e["id"]}">{e["label"]}</a>' for e in ENTRIES)
    n_fig = sum(len(e["figs"]) for e in ENTRIES)

    P = [B_SEC, '  <section id="kiss">',
         '    <div class="eyebrow" style="color:#c98f00">Reference</div>',
         "    <h2>KISS &mdash; keep it simple, stupid</h2>",
         '    <div class="method" style="border-left:4px solid #c98f00">',
         "      <b>Every idea on this site, explained once, in plain words, with a "
         "picture.</b> The other tabs say what was <i>done</i>; this one says what the "
         "words <i>mean</i>. If a term reads as jargon somewhere else, it has exactly "
         "one place to be looked up, and this is it.",
         f"      <p style='margin:8px 0 0'>{n_fig} figures, "
         f"{len(ENTRIES)} topics: {idx}</p>",
         "      <p style='margin:8px 0 0;color:#68727d'>Each figure is built by a "
         "script in <code>02_FBM_Clustering/</code> and every number on it is computed "
         "rather than typed, so an explainer cannot quietly disagree with the analysis "
         "it explains. The tab itself is generated by "
         "<code>make_kiss_tab.py</code>.</p>",
         "    </div>"]

    for e in ENTRIES:
        P.append(f'    <h3 id="{e["id"]}">{e["label"]}</h3>')
        P.append('    <div class="callout q" style="margin:0 0 10px">'
                 f'<b>The question.</b> {e["q"]}</div>')
        for para in e["body"]:
            P.append(f'    <p style="margin:0 0 8px">{para}</p>')
        for num, title, img, alt in e["figs"]:
            P.append(f"""
    <figure><div class="cap"><div class="fignum">FIG {num}</div>
      <h4>{title}</h4>
      <div class="runid"><code>{FIGROOT}/{img}</code></div></div>
      <div class="imgwrap"><img data-fig="{FIGROOT}/{img}" alt="{alt}"></div>
    </figure>""")

    P += ["  </section>", E_SEC]
    return "\n".join(P)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    a = ap.parse_args()

    missing = [f[2] for e in ENTRIES for f in e["figs"] if not (EXPL / f[2]).exists()]
    if missing:
        print("MISSING FIGURES - the tab would render placeholders:")
        for m in missing:
            print(f"   {m}")

    html = build()
    out = EXPL / "webblock_kiss.html"
    out.write_text(html, encoding="utf-8")
    print(f"-> {out}   ({len(html):,} chars, "
          f"{sum(len(e['figs']) for e in ENTRIES)} figures)")
    if not a.insert:
        print("\n(pass --insert to splice it into the site)")
        return 0

    s = SITE.read_text(encoding="utf-8")

    # the section
    if B_SEC in s and E_SEC in s:
        i, j = s.index(B_SEC), s.index(E_SEC) + len(E_SEC)
        s = s[:i] + html + s[j:]
        print("replaced the existing kiss section")
    else:
        anchor = '  <section id="caveats">'
        if anchor not in s:
            raise SystemExit("anchor section not found")
        i = s.index(anchor)
        s = s[:i] + html + "\n\n" + s[i:]
        print("inserted the kiss section before #caveats")

    # the nav button
    if B_NAV in s and E_NAV in s:
        i, j = s.index(B_NAV), s.index(E_NAV) + len(E_NAV)
        s = s[:i] + B_NAV + "\n" + NAV + "\n    " + E_NAV + s[j:]
    else:
        anchor = '    <button class="n5" data-t="caveats">'
        if anchor not in s:
            raise SystemExit("nav anchor not found")
        i = s.index(anchor)
        s = s[:i] + B_NAV + "\n" + NAV + "\n    " + E_NAV + "\n" + s[i:]
        print("inserted the nav button before Caveats")

    # the dot colour, once
    if ".nk .dot" not in s:
        a2 = "  .n10 .dot{background:var(--s5)}"
        if a2 not in s:
            raise SystemExit("css anchor not found")
        s = s.replace(a2, CSS + "\n" + a2, 1)
        print("added the .nk dot colour")

    SITE.write_text(s, encoding="utf-8")
    print(f"-> {SITE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
