#!/usr/bin/env python3
"""
make_cohort_figure.py - FIG C.0, what the clustering cohort is made of.

    python make_cohort_figure.py                 newest cache in A, every cache in B
    python make_cohort_figure.py --version 11    pin panel A to concat_source_v11
    python make_cohort_figure.py --insert        also splice the block into the site

A  Per patient, the ERSP cubes that reached the cache - one per electrode x condition,
   in the FIG RT.1 layout: audio | picture | reading, stacked, total at the end. Each
   condition is drawn twice: solid for the cubes whose electrode is in the final gated
   cohort, pale for the ones that are not. "Not in the cohort" is the honest union of
   two different things, and the caption says so: an electrode can fail the activity
   gate, or be removed by a rule before the gate ever sees it (subdural grid,
   microwire, non-neural name, excluded patient, or a condition missing on disk).

B  The same cohort across every concat_source_v<N> on disk: patients by centre, patients
   by task language, and the native anatomy of the gated electrodes. This is the panel
   that says what actually changed between two versions, which the per-patient bars
   cannot.

RUN IT AFTER EVERY CACHE REBUILD. rebuild_concat_cache.py --apply calls this at the end,
so the figure is never older than the cohort it describes. It is also the first step of
the site phase of make_paper2_outputs.py.

WHERE THE THREE B QUANTITIES COME FROM
  centre, language   patient_meta.csv (make_patient_meta.py) - the language is read from
                     the behavioural filename or, where that file predates the
                     convention, from the stimuli; it is never inferred from the centre,
                     because PAT_3975 is a Geneva patient tested in German.
  native anatomy     the LM review bundle's contacts.json, the one place the BIDS
                     tissueLabel column is parsed. Missing for EL051/EL052, which are
                     not in the fsaverage coordinate file at all.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import Patch

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "functions"))
import lf_concat as CC            # noqa: E402
from lf_dataset import (is_non_neural_electrode, is_grid_electrode,  # noqa: E402
                        is_micro_electrode)

DATASET = ROOT / "outputs" / "_dataset"
REVIEW = ROOT / "outputs" / "250_recon" / "fsaverage" / "activity_viz" / "review" / "contacts.json"
META = ROOT / "patient_meta.csv"
OUT = ROOT / "outputs" / "clustering" / "cohort"
SITE = Path(os.environ.get("LF_SITE_DIR") or (Path.home() / "lorafanda.github.io")) / "analysis_status.html"
FIG_REL = "02_FBM_Clustering/outputs/clustering/cohort/C0_cohort_composition.png"

BEGIN = "<!-- BEGIN cohort composition, generated by make_cohort_figure.py - do not hand-edit -->"
END = "<!-- END cohort composition -->"
# Straight after the tab's lead paragraph, i.e. the first content in the section.
# class="tabhead" keeps it above the role strip and visible in every role - see the
# isHdr note in make_site_ui.py; without it the block lands in the Intro group and the
# tab hides it behind its Method button.
ANCHOR = '<div class="method" id="s2runbook"'

CONDS = ("audio", "picture", "reading")
CCOL = {"audio": "#c0392b", "picture": "#2471a3", "reading": "#17a589"}
INK, MUTED = "#22272b", "#7c858e"


def strict(s) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", str(s)).upper()


def caches() -> list[Path]:
    ds = [Path(p) for p in glob.glob(str(DATASET / "concat_source_v*")) if Path(p).is_dir()]
    return sorted(ds, key=lambda p: int(p.name.rsplit("_v", 1)[1]))


def cohort_of(cache: Path):
    """(df_meta with an `in_cohort` column, the gated electrode keys, the patient list).

    lf_concat's own rule chain, applied here rather than re-stated: non-neural names,
    subdural grids, microwires, excluded patients, then all three conditions present,
    then the activity gate. Each mask is recomputed on the frame it is applied to - a
    boolean built on the ORIGINAL frame and applied to a shortened one raises, and
    silently mis-aligns if the lengths happen to match.
    """
    df = pd.read_parquet(cache / "df_meta.parquet").reset_index(drop=True)
    df["contact"] = df["electrode"].map(CC.normalize_label)
    df["key"] = df.patient_id.astype(str) + "|" + df.contact.astype(str)

    keep = df
    for mask in (lambda d: d["electrode"].map(is_non_neural_electrode),
                 lambda d: d.apply(lambda r: is_grid_electrode(r["electrode"], r["patient_id"]), axis=1),
                 lambda d: d.apply(lambda r: is_micro_electrode(r["electrode"], r["patient_id"]), axis=1)):
        keep = keep[~mask(keep).values].reset_index(drop=True)
    excl = {str(p) for p in CC.DEFAULT_EXCLUDE_PATIENTS}
    keep = keep[~keep.patient_id.astype(str).isin(excl).values].reset_index(drop=True)

    g = keep.groupby("key")
    full = set(g.condition.nunique().pipe(lambda s: s[s == 3]).index)
    hot = g.high_activity.any()
    gated = {k for k in full if bool(hot.loc[k])}
    df["in_cohort"] = df.key.isin(gated)
    pats = sorted({k.split("|")[0] for k in gated})
    return df, gated, pats


def regions_for(gated: set[str]) -> pd.Series:
    """Native anatomy of the gated electrodes, from the LM review bundle."""
    if not REVIEW.exists():
        return pd.Series(dtype=int)
    rows = json.loads(REVIEW.read_text(encoding="utf-8"))
    rows = rows if isinstance(rows, list) else list(rows.values())[0]
    lut = {f"{r['patient']}|{strict(r['name'])}": ((r.get("native") or {}).get("region") or "")
           for r in rows}
    vals = [lut.get(f"{k.split('|')[0]}|{strict(k.split('|')[1])}", "") for k in gated]
    return pd.Series([v for v in vals if v]).value_counts()


def panel_a(ax, df: pd.DataFrame, cache_name: str) -> None:
    piv = (df.groupby(["patient_id", "condition", "in_cohort"]).size()
             .unstack(["condition", "in_cohort"], fill_value=0))
    order = sorted(piv.index, key=lambda p: (0 if str(p).startswith("EL") else 1, str(p)))
    piv = piv.loc[order]
    y = np.arange(len(piv))[::-1]

    left = np.zeros(len(piv))
    for c in CONDS:
        for state in (True, False):
            if (c, state) not in piv.columns:
                continue
            w = piv[(c, state)].to_numpy(float)
            ax.barh(y, w, left=left, height=0.72, color=CCOL[c],
                    alpha=1.0 if state else 0.26,
                    edgecolor="white", linewidth=0.4, zorder=3)
            left += w

    tot = piv.sum(1).to_numpy(float)
    kept = piv[[c for c in piv.columns if c[1]]].sum(1).to_numpy(float)
    for yi, t, k in zip(y, tot, kept):
        ax.text(t + max(tot) * 0.012, yi, f"{int(t)}", va="center", ha="left",
                fontsize=7.2, color=INK)
        ax.text(t + max(tot) * 0.075, yi, f"({int(k)} kept)", va="center", ha="left",
                fontsize=6.6, color=MUTED)

    ax.set_yticks(y); ax.set_yticklabels(piv.index, fontsize=7.4)
    ax.set_xlabel("ERSP cubes in the cache  (one per electrode × condition)", fontsize=8.6)
    ax.set_title(f"A  ·  Per patient  —  {cache_name}", fontsize=10.5,
                 loc="left", color=INK, pad=8)
    ax.set_xlim(0, max(tot) * 1.16)
    ax.grid(axis="x", color="#dfe3e8", lw=0.6, zorder=0)
    ax.set_axisbelow(True)
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.tick_params(axis="y", length=0)
    handles = [Patch(facecolor=CCOL[c], label=c) for c in CONDS]
    handles += [Patch(facecolor="#888", alpha=0.26, label="not in the cohort")]
    ax.legend(handles=handles, fontsize=7.4, frameon=False, ncol=4,
              loc="lower right", bbox_to_anchor=(1.0, -0.085))


def version_block(ax, name, cen, lan, reg, n_pat, n_gated, cen_pal, lang_pal) -> None:
    """One cache version: three proportional bars, labels on the left.

    Three separate axes stacked with their own titles collided with the next version's
    heading and clipped every in-bar label, so this is one axes with three rows and the
    category names as y ticks - nothing to overlap.
    """
    series = [("centre", cen, lambda k, i: cen_pal.get(k, "#9aa3ad")),
              ("language", lan, lambda k, i: lang_pal.get(k, "#9aa3ad")),
              ("anatomy", reg, lambda k, i: ("#aeb4bc" if str(k).startswith("other")
                                             else plt.get_cmap("tab20")(i % 20)))]
    for row, (label, counts, pal) in enumerate(series):
        y = 2 - row
        tot = float(counts.sum()) or 1.0
        left = 0.0
        for i, k in enumerate(counts.index):
            v = float(counts[k])
            ax.barh([y], [100 * v / tot], left=[100 * left / tot], height=0.66, zorder=3,
                    color=pal(k, i), edgecolor="white", linewidth=0.7)
            # only where the slice is wide enough to hold the text without clipping
            if 100 * v / tot >= 11:
                ax.text(100 * (left + v / 2) / tot, y, f"{k} {int(v)}", ha="center",
                        va="center", fontsize=6.5, color="white")
            left += v
    ax.set_xlim(0, 100); ax.set_ylim(-0.6, 2.6)
    ax.set_yticks([2, 1, 0]); ax.set_yticklabels(["centre", "language", "anatomy"],
                                                 fontsize=7.2, color=MUTED)
    ax.set_xticks([])
    ax.tick_params(axis="y", length=0)
    ax.set_title(f"{name}   ·   {n_pat} patients, {n_gated} gated",
                 fontsize=8.6, loc="left", color=INK, pad=4)
    for s in ax.spines.values():
        s.set_visible(False)


def build(version: int | None):
    cs = caches()
    if not cs:
        raise SystemExit(f"no concat_source_v* under {DATASET}")
    target = next((c for c in cs if c.name.endswith(f"_v{version}")), None) if version else cs[-1]
    if target is None:
        raise SystemExit(f"no concat_source_v{version}")

    meta = pd.read_csv(META) if META.exists() else pd.DataFrame(columns=["patient", "centre", "language"])
    mcentre = dict(zip(meta.patient.astype(str), meta.centre.astype(str)))
    mlang = {str(p): ("" if not isinstance(l, str) or not l.strip() else l.strip())
             for p, l in zip(meta.patient, meta.language)}

    rows = []
    for c in cs:
        try:
            df, gated, pats = cohort_of(c)
        except Exception as e:                       # a schema that predates a column
            print(f"  {c.name}: skipped ({type(e).__name__}: {e})")
            continue
        rows.append(dict(name=c.name, df=df, gated=gated, pats=pats))
        if c == target:
            tdf = df
    if not rows:
        raise SystemExit("no readable cache")

    fig = plt.figure(figsize=(15.2, 10.4), dpi=200)
    gs = fig.add_gridspec(1, 2, width_ratios=[1.0, 0.95], wspace=0.34,
                          left=0.065, right=0.965, top=0.848, bottom=0.075)
    panel_a(fig.add_subplot(gs[0, 0]), tdf, target.name)

    # ---- B: one axes per cache version, three proportional bars each
    right = gs[0, 1].subgridspec(len(rows), 1, hspace=0.72)
    cen_pal = {"Bern": "#5b6bbf", "Geneva": "#c77f2a"}
    lang_pal = {"GER": "#7d5ba6", "FRE": "#3f9e8c", "ENG": "#b5651d", "ITA": "#8aa62f"}
    for j, e in enumerate(rows):
        pats = e["pats"]
        cen = pd.Series([mcentre.get(p, "unknown") for p in pats]).value_counts()
        lan = pd.Series([mlang.get(p, "") or "unknown" for p in pats]).value_counts()
        reg = regions_for(e["gated"])
        top = reg.head(6)
        if len(reg) > 6:
            top = pd.concat([top, pd.Series({f"other ({len(reg) - 6})": int(reg[6:].sum())})])
        version_block(fig.add_subplot(right[j]), e["name"], cen, lan, top,
                      len(pats), len(e["gated"]), cen_pal, lang_pal)

    fig.text(0.065, 0.960, "FIG C.0  ·  What the clustering cohort is made of",
             fontsize=13.5, color=INK)
    fig.text(0.065, 0.936,
             "A: every ERSP cube that reached the cache. Pale = its electrode is not in the "
             "final cohort — it failed the activity gate, or a rule removed it first "
             "(subdural grid, microwire, non-neural name, excluded patient, a condition "
             "missing on disk).", fontsize=8.2, color=MUTED)
    fig.text(0.535, 0.905, "B  ·  Every cache on disk, side by side",
             fontsize=10.5, color=INK)
    fig.text(0.535, 0.888,
             "Bars are proportions. TODAY'S rules applied to each cache, so a version's "
             "count here can differ from what it published at the time — the microwire "
             "and grid rules have both changed since v8.",
             fontsize=7.4, color=MUTED)

    OUT.mkdir(parents=True, exist_ok=True)
    png = OUT / "C0_cohort_composition.png"
    fig.savefig(png, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    summary = {e["name"]: dict(patients=len(e["pats"]), gated=len(e["gated"]),
                               cubes=int(len(e["df"])),
                               centres=pd.Series([mcentre.get(p, "unknown") for p in e["pats"]])
                               .value_counts().to_dict(),
                               languages=pd.Series([mlang.get(p, "") or "unknown" for p in e["pats"]])
                               .value_counts().to_dict())
               for e in rows}
    (OUT / "C0_cohort_composition.json").write_text(
        json.dumps(dict(target=target.name, versions=summary), indent=1), encoding="utf-8")
    print(f"  -> {png}")
    for n, s in summary.items():
        print(f"     {n:<20} {s['patients']:>3} patients  {s['gated']:>5} gated  "
              f"{s['cubes']:>5} cubes  {s['centres']}  {s['languages']}")
    return target.name, summary


def insert_block(target: str, summary: dict) -> None:
    s = summary[target]
    cen = " / ".join(f"{k} {v}" for k, v in sorted(s["centres"].items()))
    lan = " / ".join(f"{k} {v}" for k, v in sorted(s["languages"].items()))
    block = f"""{BEGIN}
    <figure class="tabhead" style="margin:0 0 18px">
      <div class="cap"><div class="fignum">FIG C.0</div>
        <h4>What the clustering cohort is made of &mdash; {target}</h4>
        <div class="runid">{s['patients']} patients &middot; {s['gated']} gated electrodes
          &middot; {s['cubes']} ERSP cubes in the cache &middot; {cen} &middot; {lan}
          &middot; <code>make_cohort_figure.py</code>, re-run by
          <code>rebuild_concat_cache.py --apply</code></div></div>
      <div class="imgwrap"><img data-fig="{FIG_REL}" alt="per-patient ERSP cubes with the
        ungated ones in pale, and every cache version compared by centre, task language
        and native anatomy"></div>
    </figure>
{END}
"""
    if not SITE.exists():
        print(f"  (no {SITE} - block not inserted)")
        return
    html = SITE.read_text(encoding="utf-8")
    if BEGIN in html:
        i, j = html.index(BEGIN), html.index(END) + len(END)
        html = html[:i] + block.strip() + html[j:]
        print("  replaced the existing block")
    else:
        # the top of the clustering tab: the first heading inside <section id="s2">
        k = html.index('<section id="s2"')
        a = html.index(ANCHOR, k)
        a = html.rindex("\n", 0, a) + 1
        html = html[:a] + block + html[a:]
        print("  inserted at the top of the clustering tab")
    SITE.write_text(html, encoding="utf-8")
    print(f"  -> {SITE}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", type=int, default=None,
                    help="cache version for panel A (default: the newest)")
    ap.add_argument("--insert", action="store_true", help="splice the block into the site")
    a = ap.parse_args()
    target, summary = build(a.version)
    if a.insert:
        insert_block(target, summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
