#!/usr/bin/env python3
"""The "Paper 2 · outline" tab of analysis_status.html - preprocessing to clustering outputs,
in Cell Reports order, as bullets whose darkness is the confidence in them.

    python make_outline_tab.py            (build the block, write nothing)
    python make_outline_tab.py --insert   (splice it into the site: section + nav button)

SOURCE = paper2_outline.md next to this script. Lora edits that file and re-runs. Syntax:
    # Heading                    -> h3 (a sub-tab of the page's strip)
    ## Sub-heading               -> h4
    - text                       -> bullet, confidence 1 (black: read from the code / the run)
    -2 text  -3 text  -4 text    -> bullet, confidence 2 / 3 / 4 (greyer = less certain:
                                    2 = from memory of the pipeline, 3 = plausible, needs a check,
                                    4 = placeholder for Lora - citations with section / paragraph
                                    slots, numbers still to be read off a run)
    indentation by two spaces    -> nested bullet
    `code`, **bold**, *italic*   -> as in Markdown; [cite: Author et al. 2019, sec 2.3 par 1] -> a
                                    citation chip (rendered at the bullet's confidence)
    > text                       -> a note box (the "fill in" hints)
Nothing else in the site file is touched; the nav button is added once (make_site_ui.py
groups it under "Writing" - add "outline" to GROUPS there).
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "paper2_outline.md"
SITE = Path("C:/Users/fanda/lorafanda.github.io/analysis_status.html")
B_SEC = "<!-- BEGIN outline tab, generated by make_outline_tab.py - do not hand-edit -->"
E_SEC = "<!-- END outline tab -->"
BTN = '    <button class="np" data-t="outline"><span class="dot"></span>Paper 2 &middot; outline</button>'
ANCHOR_SEC = '  <section id="paper">'
ANCHOR_BTN = 'data-t="paper"'

CSS = """<style id="outline-css">
  #outline .cf1{color:var(--ink)} #outline .cf2{color:color-mix(in srgb,var(--ink) 68%,var(--bg))}
  #outline .cf3{color:color-mix(in srgb,var(--ink) 46%,var(--bg))} #outline .cf4{color:color-mix(in srgb,var(--ink) 30%,var(--bg))}
  #outline .cf4 code,#outline .cf3 code{opacity:.85}
  #outline .cite{font-size:12px;border:1px solid currentColor;border-radius:999px;padding:0 7px;margin-left:4px;opacity:.9;white-space:nowrap}
  #outline .legend{display:flex;flex-wrap:wrap;gap:6px 14px;font-size:12.5px;margin:0 0 14px}
  #outline .legend span::before{content:"\\25A0";margin-right:5px}
  #outline .note{border-left:3px solid var(--line);background:var(--chip);padding:8px 12px;margin:8px 0;font-size:13.5px;color:var(--muted)}
  #outline ul{margin:4px 0 0;padding-left:20px} #outline li{margin:3px 0} #outline li ul{margin-top:2px}
  #outline h4{margin:14px 0 4px}
</style>"""

_e = html.escape


def inline(s: str) -> str:
    """Markdown-ish inline: escape, then `code`, **bold**, *italic*, [cite: ...]."""
    s = _e(s)
    s = re.sub(r"\[cite:\s*([^\]]+)\]", lambda m: f'<span class="cite">{m.group(1).strip()}</span>', s)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", s)
    s = re.sub(r"(?<![*\w])\*([^*]+)\*(?![*\w])", r"<i>\1</i>", s)
    return s


def slug(s: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return "o-" + s[:40]


def build(md: str) -> str:
    today = dt.date.today().isoformat()
    out = [B_SEC, CSS, '  <section id="outline">',
           '    <div class="eyebrow">Manuscript</div>',
           '    <h2 class="title">Paper 2 &middot; outline, preprocessing &rarr; clustering outputs</h2>',
           f'    <p class="lead">Every section of the paper as bullets, in Cell Reports order. The darkness of a line is how sure it is: '
           f'black was read from the code or the run, lighter is memory, a guess, or a slot to fill. '
           f'Source: <code>02_FBM_Clustering/paper2_outline.md</code>, rebuilt {today}.</p>',
           '    <div class="legend"><span class="cf1">read from the code / run</span><span class="cf2">from the pipeline as I know it</span>'
           '<span class="cf3">plausible, check</span><span class="cf4">your slot: citation section / paragraph, number, decision</span></div>']
    stack: list[int] = []          # open <ul> indent levels
    open_div = False
    n_bul = 0

    def close_lists(to_level: int = -1) -> None:
        while stack and stack[-1] > to_level:
            stack.pop(); out.append("</ul>")

    for raw in md.splitlines():
        if not raw.strip():
            continue
        m = re.match(r"^(\s*)-(\d)?\s+(.*)$", raw)
        if raw.startswith("# "):
            close_lists()
            if open_div:
                out.append("    </div>"); open_div = False
            t = raw[2:].strip()
            out.append(f'    <h3 id="{slug(t)}">{inline(t)}</h3>')
            out.append('    <div class="method">'); open_div = True
        elif raw.startswith("## "):
            close_lists()
            out.append(f"    <h4>{inline(raw[3:].strip())}</h4>")
        elif raw.startswith("> "):
            close_lists()
            out.append(f'    <div class="note">{inline(raw[2:].strip())}</div>')
        elif m:
            indent, cf, text = len(m.group(1)) // 2, m.group(2) or "1", m.group(3)
            close_lists(indent)
            if not stack or stack[-1] < indent:
                stack.append(indent); out.append("<ul>")
            out.append(f'<li class="cf{cf}">{inline(text)}</li>'); n_bul += 1
        else:                      # a plain line: a bullet at level 0, confidence 1
            close_lists(0)
            if not stack:
                stack.append(0); out.append("<ul>")
            out.append(f'<li class="cf1">{inline(raw.strip())}</li>'); n_bul += 1
    close_lists()
    if open_div:
        out.append("    </div>")
    out.append("  </section>")
    out.append(E_SEC)
    print(f"outline: {n_bul} bullets")
    return "\n".join(out)


def insert(block: str) -> None:
    s = SITE.read_text(encoding="utf-8")
    if B_SEC in s and E_SEC in s:
        i, j = s.index(B_SEC), s.index(E_SEC) + len(E_SEC)
        s = s[:i] + block + s[j:]
        print("replaced the generated block")
    else:
        k = s.index(ANCHOR_SEC)
        s = s[:k] + block + "\n\n" + s[k:]
        print("inserted the section before the manuscript tab")
    if 'data-t="outline"' not in s:
        # own marker pair after the manuscript tab's, so neither generator rewrites the other's button
        nav_end = s.index("</nav>")
        k = s.index("<!-- END paper2 nav -->", s.index("<nav>")) if "<!-- END paper2 nav -->" in s[:nav_end] else s.index(ANCHOR_BTN, s.index("<nav>"))
        line_end = s.index("\n", k)
        s = s[:line_end] + "\n    <!-- BEGIN outline nav -->\n" + BTN + "\n    <!-- END outline nav -->" + s[line_end:]
        assert s.index('data-t="outline"') < s.index("</nav>")
        print("added the nav button (run make_site_ui.py --insert to group it)")
    SITE.write_text(s, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true")
    a = ap.parse_args()
    block = build(SRC.read_text(encoding="utf-8"))
    print(f"block: {len(block):,} chars")
    if a.insert:
        insert(block)
        print(f"wrote {SITE}")
    else:
        print("(pass --insert to splice it into the site)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
