#!/usr/bin/env python3
"""
make_cluster_webblock.py - the statistics block of the 02 clustering tab, generated
FROM outputs/clustering/statistics/ so the page cannot drift away from the analysis.

This is make_bsf_webblock.py's rule applied to the rebuilt cohort. That script pins one
run and writes tab 07; this one follows the CURRENT runs - whatever 240/241/242 last
produced, at whatever K 249 picked from the convex-NMF held-out peak - and writes the
statistics section of the 02 tab. Nothing here is typed in, INCLUDING the sentences: a
claim like "Ward separates best" is decided from the numbers each time it is generated,
because that particular sentence was true at K=8 on the ungated cohort and is not true
of every cohort since.

    python make_cluster_webblock.py            # write the fragment, print it
    python make_cluster_webblock.py --insert   # AND splice it into analysis_status.html

The splice is delimited by HTML comments and is idempotent - running it twice replaces
the block rather than stacking two of them.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
STATS = ROOT / "outputs" / "clustering" / "statistics"
BSF = ROOT / "outputs" / "clustering" / "bsf_comparison"
SITE = Path("C:/Users/fanda/lorafanda.github.io/analysis_status.html")
FIGROOT = "02_FBM_Clustering/outputs/clustering/statistics"

BEGIN = "<!-- BEGIN generated by make_cluster_webblock.py - do not hand-edit -->"
END = "<!-- END generated by make_cluster_webblock.py -->"

ORDER = ["kmeans", "hierarchical", "cnmf"]
NICE = {"kmeans": "k-means", "hierarchical": "Ward", "cnmf": "convex NMF"}
TAG = {"kmeans": "a", "hierarchical": "b", "cnmf": "c"}
GREEN, RED, MUTED, INK = "#1b7837", "#c1121f", "#68727d", "#1b232c"

FS_NOTE = {
    "concat_hg": ("high gamma only &mdash; 3 conditions &times; 300 time-normalised "
                  "bins = 900 features"),
    "concat_rawds": ("15 frequency bands &times; 3 conditions &times; 30 downsampled "
                     "bins = 1350 features, the SAME electrodes described more fully"),
    "concat_bands5": ("5 frequency bands &times; 3 conditions &times; 30 downsampled "
                      "bins = 450 features &mdash; the same spectrum as "
                      "<code>concat_rawds</code> at a third of the width, each band a "
                      "union of contiguous 15-band edges"),
    "concat_bands5z": ("the same 5 bands with each one z-scored to equal weight "
                       "&mdash; <b>units are SD within a band, not dB</b>. Raw against "
                       "z-scored changes the partition more (ARI 0.37) than changing "
                       "the algorithm does"),
    "concat_hg_all": "high gamma, responsiveness gate LIFTED",
}


def esc(s) -> str:
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def fmt(v, n=3, sign=False):
    if v is None or (isinstance(v, float) and not np.isfinite(v)):
        return "&mdash;"
    return f"{v:+.{n}f}" if sign else f"{v:.{n}f}"


# ── loading ─────────────────────────────────────────────────────────────────
def discover():
    """Every {feature_set}_K{k} directory that actually has a summary in it."""
    out = []
    for d in sorted(STATS.glob("*_K*")):
        f = d / "stats_summary.json"
        if f.exists():
            out.append((d, json.loads(f.read_text())))
    # concat_hg before concat_rawds, which is the order the argument runs in
    rank = {"concat_hg": 0, "concat_rawds": 1, "concat_bands5": 2,
            "concat_bands5z": 3, "concat_hg_all": 4}
    out.sort(key=lambda t: rank.get(t[1].get("feature_set", ""), 9))
    return out


def load(d):
    g = {}
    for k, f in (("sep", "stats_separation.csv"), ("agr", "stats_agreement.csv"),
                 ("coh", "stats_coherence.csv"), ("sizes", "stats_cluster_sizes.csv"),
                 ("lopo", "stats_lopo.csv")):
        p = d / f
        g[k] = pd.read_csv(p) if p.exists() else None
    return g


# ── tables ──────────────────────────────────────────────────────────────────
def t_separation(sep):
    if sep is None:
        return "<p><i>separation not computed</i></p>"
    rows = ["<tr><th></th><th>home space</th><th>silhouette</th><th>matched null</th>"
            "<th>z (home)</th><th>z in the other space</th></tr>"]
    for m in ORDER:
        h = sep[(sep.method == m) & (sep.home)]
        o = sep[(sep.method == m) & (~sep.home)]
        if h.empty:
            continue
        h = h.iloc[0]
        o = o.iloc[0] if not o.empty else None
        z = float(h.z)
        zc = GREEN if z > 3 else (RED if z < 2 else INK)
        rows.append(
            f"<tr><td><b>{NICE[m]}</b></td><td><code>{h.space}</code></td>"
            f"<td>{fmt(h.silhouette, 4, True)}</td>"
            f"<td>{fmt(h.null_mean, 4, True)} &plusmn; {fmt(h.null_sd, 4)}</td>"
            f"<td style='color:{zc}'><b>{fmt(z, 1, True)}</b></td>"
            f"<td><i>{fmt(o.z, 1, True) if o is not None else '&mdash;'}</i></td></tr>")
    return "<table class='sum' style='margin:8px 0'>" + "".join(rows) + "</table>"


def t_agreement(agr):
    if agr is None:
        return ""
    rows = ["<tr><th>pair</th><th>ARI</th><th>NMI</th></tr>"]
    for _, r in agr.iterrows():
        rows.append(f"<tr><td>{NICE[r.a]} vs {NICE[r.b]}</td>"
                    f"<td><b>{fmt(r.ari)}</b></td><td>{fmt(r.nmi)}</td></tr>")
    return "<table class='sum' style='margin:8px 0'>" + "".join(rows) + "</table>"


def t_coherence(coh, sizes):
    if coh is None:
        return ""
    rows = ["<tr><th></th><th>neighbours sharing label</th><th>over chance</th>"
            "<th>largest cluster</th><th>smallest</th></tr>"]
    best = float(coh.over_chance.max())
    for m in ORDER:
        r = coh[coh.method == m]
        if r.empty:
            continue
        r = r.iloc[0]
        s = sizes[sizes.method == m] if sizes is not None else None
        big = int(s.n.max()) if s is not None and not s.empty else None
        small = int(s.n.min()) if s is not None and not s.empty else None
        # a python 3.11 f-string expression may not contain a backslash, so the
        # escaped quotes are precomputed rather than inlined
        style = f' style="color:{GREEN}"' if r.over_chance >= best - 1e-9 else ""
        tiny = f' style="color:{RED}"' if (small is not None and small < 10) else ""
        rows.append(f"<tr><td><b>{NICE[m]}</b></td>"
                    f"<td>{fmt(r.neighbours_sharing_label)}</td>"
                    f"<td{style}><b>{fmt(r.over_chance, 2)}&times;</b></td>"
                    f"<td>{big if big is not None else '&mdash;'}</td>"
                    f"<td{tiny}>{small if small is not None else '&mdash;'}</td></tr>")
    return "<table class='sum' style='margin:8px 0'>" + "".join(rows) + "</table>"


def t_lopo(summ):
    lp = (summ or {}).get("lopo") or {}
    if not lp:
        return ""
    rows = ["<tr><th></th><th>worst fold</th><th>size-matched null</th><th>z</th>"
            "<th>verdict</th></tr>"]
    for m in ORDER:
        s = lp.get(m)
        if not s:
            continue
        # THE SIGN CARRIES THE MEANING. Inside the null is the pass; above it is better
        # than the pass; only BELOW means one patient is holding the solution together.
        # An abs(z) test here would have printed Ward's +2.03 as a failure.
        z = float(s["z"])
        if z <= -2:
            v, c = "BELOW &mdash; a patient is carrying it", RED
        elif z >= 2:
            v, c = "above &mdash; more robust than chance", GREEN
        else:
            v, c = "inside &mdash; no patient carries it", GREEN
        rows.append(f"<tr><td><b>{NICE[m]}</b></td><td>{fmt(s['real_min'])}</td>"
                    f"<td>{fmt(s['null_min_mean'])} &plusmn; {fmt(s['null_min_sd'])}</td>"
                    f"<td>{fmt(z, 2, True)}</td>"
                    f"<td style='color:{c}'>{v}</td></tr>")
    return "<table class='sum' style='margin:8px 0'>" + "".join(rows) + "</table>"


# ── the sentences, decided from the numbers ─────────────────────────────────
def say_separation(sep):
    h = sep[sep.home].set_index("method")
    win = h.z.idxmax()
    lo = h.z.idxmin()
    s = (f"<b>{NICE[win]} separates best here (z&nbsp;=&nbsp;{h.z[win]:+.1f})</b>, "
         f"{NICE[lo]} least (z&nbsp;=&nbsp;{h.z[lo]:+.1f}).")
    weak = [m for m in ORDER if m in h.index and h.z[m] < 2]
    if weak:
        s += (" " + " and ".join(NICE[m] for m in weak) +
              (" barely clears its null" if len(weak) == 1 else " barely clear their nulls") +
              " at all.")
    o = sep[~sep.home].set_index("method")
    collapse = [m for m in ORDER if m in o.index and o.z[m] < 0]
    if len(collapse) == len(ORDER):
        s += (" <b>Every method collapses in the other's space</b> &mdash; all three "
              "cross-space z below zero &mdash; exactly as C.7 reported: they describe "
              "different structure, they do not disagree about the same structure.")
    elif collapse:
        v = "collapses" if len(collapse) == 1 else "collapse"
        s += (" " + ", ".join(NICE[m] for m in collapse) + f" {v} when scored in the "
              "other space, but not all three do here.")
    else:
        s += (" Unusually, <b>none of the three collapses in the other space</b> &mdash; "
              "every cross-space z is positive, so this feature set's structure is "
              "visible from both.")
    return s


def say_agreement(agr):
    lo, hi = float(agr.ari.min()), float(agr.ari.max())
    tone = ("agree only weakly" if hi < 0.4 else
            "agree moderately" if hi < 0.6 else "agree substantially")
    return (f"Three defensible methods on identical electrodes {tone}, at ARI "
            f"{lo:.2f}&ndash;{hi:.2f}.")


def say_coherence(coh, sizes):
    c = coh.set_index("method")
    win = c.over_chance.idxmax()
    others = [m for m in ORDER if m != win and m in c.index]
    s = (f"<b>{NICE[win]} wins on anatomy &mdash; {c.over_chance[win]:.2f}&times; "
         f"chance against " +
         " and ".join(f"{c.over_chance[m]:.2f}&times;" for m in others) + "</b>")
    if c.neighbours_sharing_label[win] <= c.neighbours_sharing_label.min() + 1e-12:
        s += (", <b>while having the LOWEST raw neighbour-sharing</b>. The chance "
              "correction is doing the work")
    s += ". "
    if sizes is not None:
        rng = {m: (int(sizes[sizes.method == m].n.min()),
                   int(sizes[sizes.method == m].n.max())) for m in ORDER
               if not sizes[sizes.method == m].empty}
        deg = [m for m, (a, _) in rng.items() if a < 10]
        if deg:
            s += ("The cluster-size columns show why: " +
                  ", ".join(f"{NICE[m]} puts {rng[m][1]} electrodes in one cluster and "
                            f"{rng[m][0]} in another" for m in deg) +
                  f", while {NICE[win]} spans {rng[win][0]}&ndash;{rng[win][1]}. "
                  "<b>A hard method can look anatomically coherent simply by having one "
                  "cluster that covers everything</b>, and the chance correction is what "
                  "takes that back.")
        else:
            s += ("No method has a degenerate cluster here &mdash; the smallest is " +
                  f"{min(a for a, _ in rng.values())} electrodes &mdash; so the ranking "
                  "is not an artefact of one cluster swallowing the cohort.")
    s += (" <b>This is the criterion that is about the brain rather than about the "
          "fit</b>: no method is given a coordinate.")
    return s


def say_lopo(summ):
    lp = (summ or {}).get("lopo") or {}
    zs = {m: float(v["z"]) for m, v in lp.items()}
    bad = [m for m, z in zs.items() if z <= -2]
    good = [m for m, z in zs.items() if z >= 2]
    if bad:
        return ("<b>" + ", ".join(NICE[m] for m in bad) + " falls BELOW the null</b> "
                "&mdash; losing that patient costs more than losing the same number of "
                "random electrodes, which is what a single patient carrying the solution "
                "looks like.")
    s = "<b>Sitting inside the null is the pass.</b> It means losing a patient costs no "
    s += "more than losing that many random electrodes. "
    if good:
        s += ("All three do, and " + " and ".join(NICE[m] for m in good) +
              " sits above it &mdash; more robust than chance.")
    else:
        s += "All three do."
    return s


# ── figures ─────────────────────────────────────────────────────────────────
def figure(fid, num, title, bullets, img, alt, runid):
    li = "".join(f"<li>{b}</li>" for b in bullets)
    return f"""
    <figure id="{fid}"><div class="cap"><div class="fignum">FIG {num}</div>
      <h4>{title}</h4>
      <ul>{li}</ul>
      <div class="runid">{runid}</div></div>
      <div class="imgwrap"><img data-fig="{FIGROOT}/{img}" alt="{esc(alt)}"></div>
    </figure>"""


C3_BULLETS = [
    "<b>A.</b> Held-out variance vs K, <b>bi-cross-validated</b>. The curve elsewhere on "
    "the site holds out electrodes only and refits them across the full feature set, "
    "which makes it monotone in K by construction; this one holds out a block of rows "
    "AND columns, so an extra component has to earn its place.",
    "<b>C.</b> How confident each label is. <b>Silhouette</b> for k-means and Ward, "
    "<b>largest normalised loading</b> for convex NMF &mdash; the same question, but not "
    "the same axis, and the panel says so on itself. Only convex NMF has a graded "
    "membership to report at all.",
    "<b>B1.</b> Each cluster's mean response in raw dB, audio | picture | reading, on one "
    "shared y-axis so cluster amplitudes are comparable.",
    "<b>B2.</b> Where those electrodes sit &mdash; sagittal fsaverage projection, "
    "anterior on the left, one shared frame for every panel.",
    "<b>E.</b> Leave-one-patient-out against the size-matched null.",
]
C8_BULLETS = [
    "Every electrode's confidence, sorted within its cluster, coloured by whether it "
    "passes the responsiveness gate. On a gated feature set every electrode passes, so "
    "the two curves coincide and the panel reads as a per-cluster confidence profile.",
    "A cluster whose curve sits low across its whole width is not a confident cluster, "
    "however large it is.",
]


def build():
    found = discover()
    if not found:
        raise SystemExit(f"no statistics directories under {STATS}")

    pk = STATS / "heldout_peaks_figure.csv"
    peaks = pd.read_csv(pk) if pk.exists() else None

    P = []
    A = P.append
    A(BEGIN)

    # ── the held-out curve, which is what chose every K below ───────────────
    turn = ""
    if peaks is not None and not peaks.empty:
        t = peaks[~peaks.monotone]
        meths = sorted(set(t.method_label))
        turn = (f" {len(t)} of {len(peaks)} curves turn over inside K=5..30"
                + (f", and the only method that turns over in <i>every</i> panel is "
                   f"<b>convex NMF</b>" if meths == ["convex NMF"] else "") + ".")
    A(f"""
    <figure id="s2heldout"><div class="cap"><div class="fignum">FIG C.13</div>
      <h4>Held-out variance over components &mdash; and how K was chosen</h4>
      <ul>
        <li>One panel per feature set, every method fitted AND scored in its <b>home
          space</b> &mdash; convex NMF unit-normed, k-means and Ward in raw dB. The SHAPE
          of each curve is meaningful; the heights are NOT comparable across methods,
          because they are explaining variance in two different matrices.</li>
        <li>A triangle marks a curve that <b>turns over</b> inside the tested range.{turn}
          k-means and Ward keep buying variance with every extra cluster, which is what a
          partition does &mdash; it has no way to say an extra cluster was not worth
          it.</li>
        <li><b>This is what picks K.</b> Each feature set is cut at its own convex-NMF
          peak, marked with the dashed line, because convex NMF is the only one of the
          three whose curve has an interior optimum to read.</li>
      </ul>
      <div class="runid"><code>make_heldout_variance.py</code> +
        <code>make_heldout_figure.py</code> &middot; bi-cross-validated, 4&times;4 folds,
        n_iter=300 &middot; numbers in <code>heldout_peaks_figure.csv</code></div></div>
      <div class="imgwrap"><img data-fig="{FIGROOT}/C13_heldout_variance.png"
        alt="held-out variance explained versus K from 5 to 30 for k-means, Ward and convex NMF on concat_hg and concat_rawds, each in its home space; only the convex NMF curves turn over"></div>
    </figure>""")

    # ── one block per feature set ───────────────────────────────────────────
    for d, summ in found:
        fs, K = summ["feature_set"], int(summ["K"])
        g = load(d)
        n, npat = int(summ["n_electrodes"]), int(summ.get("n_patients", 0))
        nn = int(summ.get("n_null", 0))
        sid = f"s2stats_{fs}"

        A(f"""
    <h4 id="{sid}">The statistics &mdash; <code>{fs}</code> at K={K}</h4>
    <p style="margin:0 0 8px">{FS_NOTE.get(fs, '')}. Four measures, each answering a
      different question, all computed at the same K on the same <b>{n} electrodes across
      {npat} patients</b>, with <b>{nn} matched nulls per cell</b>. The three runs were
      verified to hold a bit-identical <code>X_train</code> in identical electrode order
      ({'<b>verified</b>' if summ.get('x_train_identical') else '<b style="color:' + RED + '">NOT verified</b>'}),
      so any difference below is the method and nothing else.</p>""")

        A('<p style="margin:10px 0 4px"><b>1 &mdash; Does it beat a null?</b> The null is '
          "a Gaussian carrying this feature set's own covariance: correlated features, "
          "smooth time courses, one blob, no cluster structure, refitted by the same "
          "method. White noise would be trivially beatable and would prove nothing.</p>")
        A(t_separation(g["sep"]))
        if g["sep"] is not None:
            A(f'<p style="margin:0 0 8px">{say_separation(g["sep"])}</p>')

        A('<p style="margin:10px 0 4px"><b>2 &mdash; Do they find the same thing?</b></p>')
        A(t_agreement(g["agr"]))
        if g["agr"] is not None:
            A(f'<p style="margin:0 0 8px">{say_agreement(g["agr"])}</p>')

        A('<p style="margin:10px 0 4px"><b>3 &mdash; Does it track anatomy it was never '
          "given?</b> Of an electrode's 10 nearest neighbours in fsaverage space, how "
          "many share its label, divided by the same quantity under a label shuffle. The "
          "chance correction matters: a solution with one dominant cluster scores high on "
          "the raw version for free.</p>")
        A(t_coherence(g["coh"], g["sizes"]))
        if g["coh"] is not None:
            A(f'<p style="margin:0 0 8px">{say_coherence(g["coh"], g["sizes"])}</p>')

        A('<p style="margin:10px 0 4px"><b>4 &mdash; Is one patient carrying it?</b> Each '
          "patient removed in turn, refit with the SAME method, compared to the "
          "full-cohort solution by ARI, then scored against a null that removes the same "
          "NUMBER of electrodes at random. <code>lf_decompose.lopo_stability</code> "
          "hard-codes KMeans, which would silently have made this the wrong test for the "
          "other two; the version used here delegates the refit to the method.</p>")
        A(t_lopo(summ))
        A(f'<p style="margin:0 0 8px">{say_lopo(summ)}</p>')

        runs = summ.get("runs", {})
        for m in ORDER:
            r = str(runs.get(m, "")).replace("\\", "/")
            A(figure(
                f"c3{TAG[m]}_{fs}", f"C.3{TAG[m]}",
                f"The decomposition at K={K} &mdash; {NICE[m]} on <code>{fs}</code>",
                C3_BULLETS, f"{fs}_K{K}/C3{TAG[m]}_{m}_K{K}.png",
                f"six-panel decomposition figure for {m} at K={K} on {n} electrodes: "
                f"held-out variance curve, label-confidence histogram, "
                f"leave-one-patient-out bars, {K} cluster mean response profiles and "
                f"{K} sagittal electrode maps",
                f"<code>{r}</code> &middot; K={K} &middot; "
                f"<code>make_cluster_figures.py</code>"))
        for m in ORDER:
            A(figure(
                f"c8{TAG[m]}_{fs}", f"C.8{TAG[m]}",
                f"Per-electrode confidence at K={K} &mdash; {NICE[m]} on <code>{fs}</code>",
                C8_BULLETS, f"{fs}_K{K}/C8{TAG[m]}_{m}_K{K}.png",
                f"per-electrode confidence for {m} at K={K}, sorted within each cluster "
                f"and coloured by whether the electrode passes the responsiveness gate",
                f"<code>{r}</code> &middot; K={K} &middot; "
                f"<code>make_cluster_figures.py</code>"))

    # ── the cross-feature-set read ──────────────────────────────────────────
    if len(found) > 1:
        A(cross(found))
    A(END)
    return "\n".join(P)


def cross(found):
    """The comparison the two blocks above cannot make individually."""
    rows = ["<tr><th></th>" + "".join(
        f"<th><code>{s['feature_set']}</code> K={s['K']}</th>" for _, s in found) +
        "</tr>"]

    def row(label, fn):
        return ("<tr><td>" + label + "</td>" +
                "".join(f"<td>{fn(d, s)}</td>" for d, s in found) + "</tr>")

    def sepz(d, s):
        f = d / "stats_separation.csv"
        if not f.exists():
            return "&mdash;"
        x = pd.read_csv(f)
        x = x[x.home]
        return " / ".join(f"{NICE[m]} {float(x[x.method == m].z.iloc[0]):+.1f}"
                          for m in ORDER if (x.method == m).any())

    def ari(d, s):
        f = d / "stats_agreement.csv"
        if not f.exists():
            return "&mdash;"
        x = pd.read_csv(f)
        return f"{x.ari.min():.2f}&ndash;{x.ari.max():.2f}"

    def coh(d, s):
        f = d / "stats_coherence.csv"
        if not f.exists():
            return "&mdash;"
        x = pd.read_csv(f).set_index("method")
        return " / ".join(f"{NICE[m]} {x.over_chance[m]:.2f}&times;"
                          for m in ORDER if m in x.index)

    def small(d, s):
        f = d / "stats_cluster_sizes.csv"
        if not f.exists():
            return "&mdash;"
        x = pd.read_csv(f)
        out = []
        for m in ORDER:
            y = x[x.method == m]
            if y.empty:
                continue
            lo = int(y.n.min())
            out.append(f"<span style='color:{RED if lo < 10 else INK}'>{NICE[m]} {lo}"
                       f"</span>")
        return " / ".join(out)

    def lopo(d, s):
        lp = s.get("lopo") or {}
        return " / ".join(f"{NICE[m]} {float(lp[m]['z']):+.1f}"
                          for m in ORDER if m in lp)

    rows += [row("separation z, home space", sepz),
             row("agreement between methods (ARI)", ari),
             row("anatomical coherence over chance", coh),
             row("smallest cluster", small),
             row("leave-one-patient-out z", lopo)]

    # decide the verdict rather than assert one
    best = None
    try:
        scored = []
        for d, s in found:
            x = pd.read_csv(d / "stats_cluster_sizes.csv")
            lo = min(int(x[x.method == m].n.min()) for m in ORDER
                     if not x[x.method == m].empty)
            a = pd.read_csv(d / "stats_agreement.csv").ari.mean()
            c = pd.read_csv(d / "stats_coherence.csv").over_chance.mean()
            scored.append((lo >= 10, a, c, s["feature_set"], s["K"]))
        scored.sort(reverse=True)
        best = scored[0]
    except Exception:
        pass

    note = ""
    if best is not None and len(found) == 2:
        # WHICH lines actually improve, checked rather than asserted
        w = [d for d, s_ in found if s_["feature_set"] == best[3]][0]
        o = [d for d, s_ in found if s_["feature_set"] != best[3]][0]
        os_ = [s_ for _, s_ in found if s_["feature_set"] != best[3]][0]
        ws_ = [s_ for _, s_ in found if s_["feature_set"] == best[3]][0]
        won = []
        try:
            for name, f_, col, agg in (
                    ("separation", "stats_separation.csv", "z", "min"),
                    ("agreement between the methods", "stats_agreement.csv", "ari", "mean"),
                    ("anatomical coherence", "stats_coherence.csv", "over_chance", "min"),
                    ("the smallest cluster", "stats_cluster_sizes.csv", "n", "min")):
                a = pd.read_csv(w / f_)
                b = pd.read_csv(o / f_)
                if "home" in a.columns:
                    a, b = a[a.home], b[b.home]
                if getattr(a[col], agg)() > getattr(b[col], agg)():
                    won.append(name)
            lz = min(float(v["z"]) for v in (ws_.get("lopo") or {}).values())
            oz = min(float(v["z"]) for v in (os_.get("lopo") or {}).values())
            if lz > oz:
                won.append("leave-one-patient-out")
        except Exception:
            won = []
        n_lines = 5
        how = ("on every line" if len(won) >= n_lines else
               f"on {len(won)} of the {n_lines} lines &mdash; " + ", ".join(won))
        note = (f"<p style='margin:0 0 8px'><b>Read across the columns rather than down "
                f"them.</b> <code>{best[3]}</code> at K={best[4]} is the better-behaved "
                f"solution {how}. "
                f"{'No method produces a degenerate cluster there' if best[0] else 'The degeneracy is milder there'}, "
                f"and the methods agree with each other more. Describing the same "
                f"electrodes with 15 bands instead of high gamma alone does not just add "
                f"features &mdash; <b>it makes the three algorithms converge on something "
                f"they can all see</b>.</p>")

    return ("""
    <h4 id="s2stats_cross">The two feature sets against each other</h4>
    <p style="margin:0 0 8px">Same electrodes, same patients, same three algorithms
      &mdash; the only difference is how each electrode is described, and each cut at its
      own convex-NMF held-out peak.</p>
    <table class='sum' style='margin:8px 0'>""" + "".join(rows) + "</table>" + note)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true",
                    help="splice into analysis_status.html between the markers")
    a = ap.parse_args()

    html = build()
    out = STATS / "webblock_s2stats.html"
    out.write_text(html, encoding="utf-8")
    print(f"-> {out}   ({len(html):,} chars)")
    for d, s in discover():
        print(f"   {s['feature_set']:<14} K={s['K']:<3} n={s['n_electrodes']}")

    if not a.insert:
        print("\n(pass --insert to splice it into the site)")
        return 0
    if not SITE.exists():
        raise SystemExit(f"{SITE} not found")

    s = SITE.read_text(encoding="utf-8")
    if BEGIN in s and END in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + html + s[j:]
        print("replaced the existing generated block")
    else:
        # first time: take over the hand-written region, from the statistics heading up
        # to the next figure that is not ours
        anchor = '<h4 id="s2stats">'
        stop = '<figure id="s2three">'
        hfig = '<figure id="s2heldout">'
        if hfig not in s or anchor not in s or stop not in s:
            raise SystemExit("anchors not found - splice by hand this once")
        i, j = s.index(hfig), s.index(stop)
        if not i < j:
            raise SystemExit("anchors out of order")
        s = s[:i] + html + "\n    " + s[j:]
        print("replaced the hand-written block (C.13 + statistics)")
    SITE.write_text(s, encoding="utf-8")
    print(f"-> {SITE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
