#!/usr/bin/env python3
"""
make_paper_tab.py - the "Paper 2 - manuscript" tab of analysis_status.html.

    python make_paper_tab.py            print the block, change nothing
    python make_paper_tab.py --insert   splice it into the site

WHAT THIS IS. A writing scaffold for the Cell Reports submission, not prose. Every
section of the manuscript gets a subtab, every subtab a set of headed prompts, and every
prompt an empty box to write into. The prompts are questions to answer; the answers are
yours and nothing here writes them for you.

WHERE THE TEXT LIVES. In the browser, under localStorage keys `fbm.paper2.<field id>`.
That is why the field ids below are explicit slugs and not positions: THE OUTLINE CAN BE
REGENERATED, REORDERED OR EXTENDED WITHOUT LOSING A WORD, as long as an id keeps its
name. Renaming an id orphans its text - the box comes back empty and the old value stays
in localStorage - so change labels and prompts freely, and ids only on purpose.

Because the text is browser-local it is NOT in git and NOT on another machine. The tab
says so at the top, keeps a visible saved/unsaved state, and carries Export (Markdown,
copy or download) and Import (read a previously exported file back). Export is the only
thing that makes the writing durable.

EXAMPLES. Under the Introduction and the three figure sections, two example answers sit
above each box (EXAMPLES below, keyed by field id). They are drafts to react to, written
in the paper's voice with the numbers from the current run, and a "Use as draft" button
copies one into the box. Every number in them was read off the figures' CSVs and captions
when they were written; [REF] and [brackets] mark what only the author can fill.
"""
from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

SITE = Path.home() / "lorafanda.github.io" / "analysis_status.html"
BEGIN = "<!-- BEGIN paper2 tab, generated by make_paper_tab.py - do not hand-edit -->"
END = "<!-- END paper2 tab -->"
NAV_BEGIN = "<!-- BEGIN paper2 nav -->"
NAV_END = "<!-- END paper2 nav -->"

esc = lambda t: html.escape(str(t), quote=True)


# ---------------------------------------------------------------------------
# helpers for building the outline
# ---------------------------------------------------------------------------
def G(text, sub=""):
    """A group heading inside a subtab."""
    return {"kind": "group", "h": text, "sub": sub}


def F(fid, h, prompt, rows=5, limit=None, placeholder=""):
    """One prompt and its box. `fid` is the localStorage key and must stay stable."""
    return {"kind": "field", "id": fid, "h": h, "prompt": prompt, "rows": rows,
            "limit": limit, "ph": placeholder}


def L(fid, h, prompt, limit=None, placeholder=""):
    """A one-line field - titles, names, a single sentence."""
    return {"kind": "line", "id": fid, "h": h, "prompt": prompt, "limit": limit,
            "ph": placeholder}


W = lambda n: {"unit": "words", "n": n}
C = lambda n: {"unit": "chars", "n": n}


# ---------------------------------------------------------------------------
# THE OUTLINE
#
# Section order and the limits quoted below follow the Cell Reports research-article
# format: summary 150 words, 3-4 highlights of at most 85 characters, a 40-word eTOC
# blurb, main text around 5,000 words over Introduction/Results/Discussion, a required
# Limitations of the study, and STAR Methods in its four fixed subsections behind a key
# resources table. Confirm against the guide-to-authors at submission time - limits move.
# ---------------------------------------------------------------------------
SECTIONS = [
    # ---------------------------------------------------------------- front matter
    {
        "key": "front", "label": "Front matter", "tag": "title, authors, contacts",
        "lede": "The parts the editorial office checks first. Quick to fill, easy to "
                "leave until the last day, and the title is worth as much thought as "
                "any paragraph in the paper.",
        "blocks": [
            L("front.title", "Title",
              "One line. Cell Reports titles are usually a claim or a subject, not a "
              "question. Does yours say what was found, or only what was studied?",
              placeholder="e.g. Natural response types in human language cortex ..."),
            L("front.running", "Running title",
              "The short header, typically under 50 characters."),
            F("front.authors", "Authors and affiliations",
              "Full author list in final order, with superscript affiliation numbers. "
              "Agree the order before submission, not after review.", rows=4),
            L("front.lead", "Lead contact",
              "One author, with an email that will still work in five years."),
            F("front.keywords", "Keywords",
              "Six to ten terms. Think about what a clinician searching for functional "
              "mapping alternatives would actually type.", rows=2),
        ],
    },
    # ------------------------------------------------------------------- highlights
    {
        "key": "high", "label": "Highlights &amp; eTOC", "tag": "3-4 bullets, 85 chars",
        "lede": "Written last, read first. Each highlight is capped at 85 characters "
                "including spaces and the counters below enforce it as you type. Aim "
                "each one at a different finding rather than restating the same result "
                "four ways.",
        "blocks": [
            G("Highlights", "Three or four. 85 characters each, spaces included."),
            L("high.h1", "Highlight 1", "The headline finding.", limit=C(85)),
            L("high.h2", "Highlight 2", "The second, distinct finding.", limit=C(85)),
            L("high.h3", "Highlight 3", "The third.", limit=C(85)),
            L("high.h4", "Highlight 4 (optional)", "Only if it earns its place.",
              limit=C(85)),
            G("eTOC blurb", "About 40 words, third person, for the table of contents "
                            "and email alerts."),
            F("high.etoc", "eTOC / in-brief blurb",
              "Context, then what you did, then why a non-specialist should care. "
              "Written about the paper, not by it: \"Fanda et al. show that ...\"",
              rows=4, limit=W(40)),
            G("Graphical abstract", "Optional, strongly encouraged. 1200x1200 px."),
            F("high.graphical", "What the graphical abstract should show",
              "Sketch it in words first. Which single figure panel carries the whole "
              "argument, and what has to be added around it to make it stand alone?",
              rows=4),
        ],
    },
    # ---------------------------------------------------------------------- summary
    {
        "key": "summary", "label": "Summary", "tag": "150 words",
        "lede": "One paragraph, no citations, 150 words. The counter turns red past the "
                "limit.",
        "blocks": [
            F("summary.body", "Summary",
              "The conventional five moves: why the problem matters clinically, what is "
              "missing from current practice, what you did, what you found, what it "
              "means. Resist putting the whole Results in here - one or two numbers at "
              "most, and only the ones a reader could remember.", rows=10, limit=W(150)),
        ],
    },
    # ----------------------------------------------------------------- INTRODUCTION
    {
        "key": "intro", "label": "Introduction", "tag": "the full arc",
        "lede": "The arc runs clinical problem &rarr; current standard and its limits "
                "&rarr; the alternative &rarr; our paradigm and what the first paper "
                "established &rarr; the question this paper asks. Each prompt below is "
                "a question to answer, not a heading to keep; most of these become one "
                "paragraph each, and several will merge as you write.",
        "blocks": [
            G("1 &middot; Epilepsy surgery and the need for functional mapping",
              "Where the first paper started. Open on the patient, not the method."),
            F("intro.epilepsy", "Drug-resistant focal epilepsy and surgery",
              "How common is focal epilepsy, what fraction stops responding to "
              "medication, and what does resective surgery offer them? Pick the one "
              "number you want the reader to carry into the rest of the paper.",
              rows=6),
            F("intro.tradeoff", "The trade-off that makes mapping necessary",
              "Resect enough tissue to stop the seizures, spare enough to leave the "
              "person intact. Say what is actually lost when the boundary is drawn "
              "wrong - this is the sentence that justifies the whole field.", rows=6),
            F("intro.whylanguage", "Why language cortex in particular",
              "Why can a surgeon not work from an atlas or a textbook map? Individual "
              "variability, atypical lateralisation, reorganisation around a lesion. "
              "What does post-operative aphasia cost a patient?", rows=6),
            G("2 &middot; Electrical stimulation mapping - the standard",
              "Give ESM its due before saying where it falls short. A reader who "
              "does ESM every week has to recognise their own practice here."),
            F("intro.esm_what", "What ESM is",
              "The procedure in two or three sentences: current through an electrode "
              "pair, a task, a disruption. What does a positive site mean, and why is "
              "the inference treated as causal rather than correlational?", rows=6),
            F("intro.esm_good", "What ESM does well",
              "Its real strengths - causal, focal, decades of surgical validation, "
              "directly actionable in theatre. Be generous here; the argument is "
              "stronger if the standard is presented at its best.", rows=6),
            F("intro.esm_lacks", "Where ESM falls short",
              "The honest list. Time under anaesthesia or in the EMU; afterdischarges "
              "and induced seizures; only the pairs you have time to test; an "
              "essentially binary read-out; task batteries that differ between centres; "
              "the judgement call in scoring a disruption; patients who cannot comply, "
              "and sites that cannot safely be stimulated. Which of these matter most "
              "for your argument?", rows=8),
            F("intro.gap", "The gap that leaves",
              "State plainly what a clinician cannot currently get. One or two "
              "sentences - this is the hinge of the introduction and the thing your "
              "Discussion will come back to.", rows=5),
            G("3 &middot; Passive mapping from intracranial recordings",
              "The alternative, and what is and is not settled about it."),
            F("intro.passive", "Recording instead of stimulating",
              "The idea in its simplest form: the patient performs a task, the "
              "electrodes are already there, and the response is read out rather than "
              "provoked. What signal carries it, and why high-frequency broadband "
              "activity in particular?", rows=6),
            F("intro.prior", "What prior work established",
              "The studies you are building on and what they showed - agreement with "
              "ESM, sensitivity and specificity where reported. What is now uncontested?",
              rows=6),
            F("intro.unresolved", "What is still unresolved",
              "Where the literature stops. Thresholds and features chosen study by "
              "study; one number per electrode standing in for a whole response; no "
              "agreed vocabulary for the KINDS of response a language electrode can "
              "show. This paragraph has to make the reader want the next section.",
              rows=7),
            G("4 &middot; Our paradigm, and what the first paper established",
              "The bridge from the companion paper. Assume the reader has not read it."),
            F("intro.paradigm", "The FBM paradigm",
              "The conditions and why those three: auditory comprehension, reading, "
              "picture naming. What does each one isolate, and what does having all "
              "three in the same patients let you ask that one alone could not?",
              rows=7),
            F("intro.paper1", "What the first paper showed",
              "Two or three sentences on the result you are standing on, cited as the "
              "companion paper. Enough that this paper reads on its own.", rows=6),
            F("intro.pivot", "Why that raises this paper's question",
              "The pivot, and the reason the two papers are separate: the first asks "
              "WHICH electrodes respond, this one asks WHAT KINDS of response there "
              "are. Say why the second question does not follow automatically from the "
              "first.", rows=6),
            G("5 &middot; The question this paper asks",
              "State hypotheses that could fail. A hypothesis that cannot come out "
              "negative will not convince a reviewer."),
            F("intro.q_types", "Do responses fall into a small number of natural types?",
              "The central claim. Phrase it so that a negative answer is a real "
              "possibility, and say what a negative result would look like - a "
              "continuum with no reproducible structure, clusters that are one "
              "patient's electrode strip, a K that keeps rising with no plateau.",
              rows=7),
            F("intro.q_stable", "Are those types stable?",
              "Stability is what separates a response type from an artefact of one "
              "analysis choice: across feature representations, across algorithms, and "
              "above all across patients. Say here that you treat agreement as the "
              "test, so the reader is not surprised when a whole figure is spent on it.",
              rows=7),
            F("intro.q_anatomy", "Do the types line up with known language anatomy?",
              "What the atlas comparison is for, and what it can and cannot settle - a "
              "probabilistic atlas is a prior about a location, not a measurement in "
              "your patient. Worth saying in advance that a mostly negative answer here "
              "is still informative.", rows=7),
            F("intro.q_clinical", "Why it matters clinically",
              "Close the loop with the gap you named in section 2. If a stable "
              "taxonomy of response types existed, what would change about how a "
              "patient is mapped? Keep the claim proportionate to the evidence.",
              rows=6),
            G("6 &middot; Roadmap", "Cell Reports introductions usually close with one "
                                    "short paragraph previewing the paper."),
            F("intro.roadmap", "What we did and what we found",
              "Four to six sentences walking through the paper in order. Findings, not "
              "numbers - the numbers belong in Results.", rows=6),
        ],
    },
    # -------------------------------------------------------------------- results
    {
        "key": "results", "label": "Results", "tag": "one claim per figure",
        "lede": "One subsection per figure, each headed by the claim it supports rather "
                "than the method it used. Cell Reports allows up to seven main figures.",
        "blocks": [
            F("results.cohort", "Cohort and recordings",
              "Patients, electrodes, how many survived gating, and the coverage. The "
              "paragraph that lets a reader judge every number that follows.", rows=6),
            G("Figure 1 &middot; the clusters themselves"),
            F("results.f1", "What the response types are",
              "How many types, what each one looks like, and how they differ across "
              "the three conditions. Describe them so a reader could recognise one in "
              "their own data.", rows=7),
            F("results.f1_k", "Choosing K, and why the held-out peak is not the answer",
              "The disagreement between the held-out peak and K=8 is a result, not a "
              "housekeeping detail: held-out variance cannot see a cluster that is one "
              "patient's electrode strip. Say what the reader should conclude.", rows=7),
            G("Figure 2 &middot; does the answer depend on the analysis?"),
            F("results.f2", "Agreement across feature sets and algorithms",
              "What agrees, what does not, and against what baseline. Give the "
              "self-agreement ceiling its own sentence - a method that disagrees with "
              "itself limits how much any cross-method number can mean.", rows=7),
            F("results.f2_left", "What is left out",
              "The electrodes no two solutions place together, and what that fraction "
              "means for the taxonomy claim.", rows=6),
            G("Figure 3 &middot; where the types sit"),
            F("results.f3", "Relation to the language atlas",
              "The ranking, the effect sizes, and both nulls. If the honest summary is "
              "that the effects are small, say so here plainly rather than in the "
              "Limitations.", rows=7),
            G("Further results"),
            F("results.extra", "Anything else that earns a figure",
              "Additional analyses, or a placeholder for the figure you have not made "
              "yet.", rows=6),
        ],
    },
    # ------------------------------------------------------------------ discussion
    {
        "key": "disc", "label": "Discussion", "tag": "what it means",
        "lede": "Interpretation, not a second Results. The usual shape: what was found, "
                "how it sits with prior work, what it changes, what is still open.",
        "blocks": [
            F("disc.summary", "What the study establishes",
              "Two or three sentences a reader could quote back. Say what is now "
              "supported and, just as explicitly, what is not.", rows=6),
            F("disc.prior", "How this sits with prior work",
              "Where you agree with the existing literature, where you differ, and "
              "why. If a result contradicts a published one, address it directly.",
              rows=7),
            F("disc.mechanism", "What the response types might mean",
              "The interpretive paragraph - what could produce these types "
              "physiologically or cognitively. Flag speculation as speculation.",
              rows=7),
            F("disc.clinical", "Clinical implications",
              "Return to the gap from the Introduction. What would have to be true, "
              "and what would have to be shown next, before any of this could touch a "
              "surgical decision? Under-claiming here is safer than over-claiming.",
              rows=7),
            F("disc.future", "What comes next",
              "The experiment that would settle what this one could not.", rows=6),
        ],
    },
    # ----------------------------------------------------------------- limitations
    {
        "key": "limits", "label": "Limitations", "tag": "required section",
        "lede": "A required section in Cell Reports, and one reviewers read closely. A "
                "limitation you raise yourself costs far less than one a reviewer "
                "finds. Each prompt is a candidate - keep the ones that are real.",
        "blocks": [
            F("limits.cohort", "Cohort and coverage",
              "Electrode placement is decided clinically, so coverage is neither "
              "uniform nor random, and no patient has whole-brain sampling. What can "
              "this cohort not speak to?", rows=6),
            F("limits.patients", "Generalisation across patients",
              "Clusters that are largely one patient, and what that does to a claim "
              "about response types in general.", rows=6),
            F("limits.k", "The choice of K",
              "There is no unique correct number of clusters, and different criteria "
              "give different answers. Say how much of the result survives that choice.",
              rows=6),
            F("limits.method", "Dependence on the analysis pipeline",
              "Feature representation, algorithm, normalisation, and the time warp - "
              "which removes absolute time. What does a reader lose by not having it?",
              rows=6),
            F("limits.atlas", "What the atlas comparison can and cannot show",
              "Coverage of the atlas over your electrodes, whose brains it was built "
              "from, and the difference between a probabilistic prior and a "
              "measurement in this patient.", rows=6),
            F("limits.esm", "No stimulation ground truth",
              "If the paper does not compare against ESM in the same patients, say so "
              "and say what that leaves unresolved.", rows=6),
            F("limits.other", "Anything else",
              "The one that occurs to you at 2 a.m.", rows=5),
        ],
    },
    # ---------------------------------------------------------------- STAR Methods
    {
        "key": "methods", "label": "STAR Methods", "tag": "four fixed subsections",
        "lede": "Cell Press fixes this structure: a key resources table, then resource "
                "availability, experimental model and study participant details, method "
                "details, and quantification and statistical analysis. No word limit, "
                "and it does not have to be in this format at first submission - but "
                "writing it in the right shape now costs nothing later.",
        "blocks": [
            G("Key resources table"),
            F("methods.krt", "What belongs in the key resources table",
              "For a computational study: software and versions, the deposited data, "
              "the analysis code, and any atlas or template used. List them here and "
              "build the table from this.", rows=6),
            G("Resource availability", "Three fixed subheadings."),
            L("methods.lead", "Lead contact", "Name and email."),
            L("methods.materials", "Materials availability",
              "Usually \"this study did not generate new unique reagents\"."),
            F("methods.data_code", "Data and code availability",
              "Where the data goes, where the code goes, and what a reader has to do "
              "to get it. Human intracranial data usually cannot be fully open - say "
              "precisely what is available and under what conditions.", rows=6),
            G("Experimental model and study participant details"),
            F("methods.participants", "Participants",
              "Number, ages, sex, handedness, language dominance where known, clinical "
              "context, implantation reason. Cell Press asks explicitly about sex and "
              "ethnicity reporting, and about how they were determined.", rows=7),
            F("methods.ethics", "Ethics and consent",
              "Approving committee, protocol number, how consent was obtained.", rows=4),
            G("Method details"),
            F("methods.recording", "Recording and hardware",
              "Electrodes, amplifier, sampling rate, referencing, synchronisation with "
              "stimulus delivery.", rows=6),
            F("methods.task", "Task and stimuli",
              "Enough that another lab could rebuild the paradigm: trial structure, "
              "timings, stimulus counts, response collection.", rows=7),
            F("methods.preproc", "Preprocessing",
              "Filtering, artefact rejection, electrode gating, localisation and "
              "normalisation. State the gating criteria explicitly - they determine the "
              "electrode count every result rests on.", rows=7),
            F("methods.features", "Spectral estimation and feature construction",
              "Time-frequency method, bands, baseline, the time warp and its "
              "proportions, and how a feature vector is assembled per electrode.",
              rows=7),
            F("methods.cluster", "Clustering",
              "The algorithms, what convex NMF is and why it was chosen, "
              "initialisation, restarts, and how K was selected.", rows=7),
            G("Quantification and statistical analysis"),
            F("methods.stats", "Statistics",
              "Every test, with exact n, what n represents, the definition of centre "
              "and dispersion, and the multiple-comparison correction. Cell Press asks "
              "for this specifically and reviewers check it.", rows=7),
            F("methods.nulls", "Null models and permutations",
              "Each null, what it preserves and what it destroys, and how many "
              "permutations. A null that keeps spatial structure and one that does not "
              "answer different questions - say which is which.", rows=7),
        ],
    },
    # -------------------------------------------------------------------- figures
    {
        "key": "figs", "label": "Figures &amp; legends", "tag": "up to 7 main",
        "lede": "A legend should let a reader understand the figure without the main "
                "text: what is plotted, what the error bars are, what n is, and what "
                "any test was.",
        "blocks": [
            F("figs.f1", "Figure 1 legend", "Title sentence, then panel by panel.",
              rows=7),
            F("figs.f2", "Figure 2 legend", "", rows=7),
            F("figs.f3", "Figure 3 legend", "", rows=7),
            F("figs.f4", "Figure 4 legend", "", rows=7),
            F("figs.supp", "Supplemental figures",
              "What goes to supplement, and which main figure each one supports.",
              rows=6),
        ],
    },
    # ----------------------------------------------------------------- back matter
    {
        "key": "back", "label": "Back matter", "tag": "credit, funding, interests",
        "blocks": [
            F("back.ack", "Acknowledgments",
              "Funding with grant numbers, the clinical and technical staff, and the "
              "patients. Check every funder's required wording.", rows=6),
            F("back.credit", "Author contributions",
              "CRediT taxonomy: conceptualization, methodology, software, validation, "
              "formal analysis, investigation, resources, data curation, writing - "
              "original draft, writing - review and editing, visualization, "
              "supervision, project administration, funding acquisition.", rows=6),
            L("back.interests", "Declaration of interests",
              "Usually \"the authors declare no competing interests\"."),
            F("back.supplement", "Supplemental information",
              "What is in it and how it is referenced from the main text.", rows=5),
        ],
    },
]


# ---------------------------------------------------------------------------
# THE EXAMPLES
#
# Two per field, for the Introduction and the three figure sections. Written in the
# paper's voice: short sentences, direct, one idea each. A and B take different angles
# on the same prompt rather than rewording each other. Numbers are from the K=8 run of
# 2026-09-03 (FIG1a concat_hg, FIG2, FIG3 concat_hg); [REF] marks a citation to add and
# [brackets] a value only the author has. Keys must be field ids - main() checks.
# ---------------------------------------------------------------------------
EXAMPLES = {
    # ---- 1 - epilepsy surgery and the need for mapping ------------------------
    "intro.epilepsy": [
        "Epilepsy affects about one person in a hundred [REF]. In a third of them the "
        "drugs do not work [REF]. When the seizures start from one place, that place can "
        "be removed, and for the right patient surgery is the only treatment that offers "
        "seizure freedom. About two in three become seizure-free after temporal lobe "
        "resection [REF]. The condition is common, the drugs often fail, and the "
        "operation works. The difficulty is deciding what to cut.",
        "Around a third of people with epilepsy keep having seizures on medication "
        "[REF]. Where the seizures arise from a single region, resective surgery can "
        "stop them, and in most patients it does [REF]. The benefit is large and "
        "lasting. The procedure is still underused, and one reason is the cost of "
        "getting the boundary wrong.",
    ],
    "intro.tradeoff": [
        "Two goals pull against each other. Remove enough tissue to stop the seizures. "
        "Leave enough to keep the patient who they are. The seizure focus does not "
        "respect functional boundaries. It can sit in, or next to, the cortex that "
        "supports speech, comprehension, movement or memory. Cut too little and the "
        "seizures continue. Cut too much and the patient wakes up unable to speak. "
        "Functional mapping exists to draw that line before the operation, not after.",
        "Every resection is a bet. The tissue removed should contain the focus and "
        "nothing the patient cannot spare. The two are often neighbours. A few "
        "millimetres separate a cure from a permanent deficit, and the decision is made "
        "once. That is why function is mapped in each patient before surgery, and why "
        "the quality of that map matters more than almost anything else in the "
        "procedure.",
    ],
    "intro.whylanguage": [
        "Language is the function most at risk and the hardest to predict. The textbook "
        "puts it in Broca's and Wernicke's areas, on the left. Individual patients are "
        "not the textbook. Language sites are found well outside the classical areas "
        "[REF], the dominant hemisphere is not always the left [REF], and years of "
        "seizures can move function away from a lesion [REF]. An atlas gives a "
        "probability. The surgeon needs a location. Postoperative aphasia is rare when "
        "mapping is done and common when it is skipped [REF]. When it happens it is "
        "permanent.",
        "Motor cortex is predictable. Language cortex is not. Its extent, its hemisphere "
        "and its exact position differ between people, and they differ more in people "
        "with epilepsy [REF]. A group map built from healthy brains cannot resolve this "
        "for one patient. A wrong guess costs naming, reading or comprehension, and the "
        "loss does not recover. This is the function mapping has to get right.",
    ],
    # ---- 2 - ESM --------------------------------------------------------------
    "intro.esm_what": [
        "Electrical stimulation mapping (ESM) is the clinical standard. A brief current "
        "is passed between two implanted contacts while the patient performs a task, "
        "usually naming or counting. If the task breaks down during stimulation and "
        "recovers when it stops, the site is marked as eloquent. The logic is causal: "
        "the current disrupted the function, so the tissue supports it. The output is a "
        "map of sites that must be spared.",
        "In ESM the surgeon stimulates cortex and watches the patient. Current is "
        "applied to a pair of contacts for a few seconds during a language task. Speech "
        "arrest, anomia or a comprehension error in that window marks the site as "
        "critical. Nothing is measured. The function is switched off and the effect is "
        "observed. Because it is an intervention rather than a recording, ESM is treated "
        "as the ground truth against which every other method is judged.",
    ],
    "intro.esm_good": [
        "ESM has real strengths. It is causal. It tests the tissue that will be cut, in "
        "the patient who will be operated on, with the function that matters. It has "
        "decades of surgical validation behind it [REF]: resections that respect "
        "ESM-positive sites rarely produce new deficits. Every epilepsy surgeon "
        "understands it, and its output maps directly onto a surgical decision. No "
        "recording method can claim all of that.",
        "The case for ESM is simple. It answers the surgical question directly: will "
        "removing this tissue cause a deficit? A positive site is a site to leave alone. "
        "The method is focal, it can be repeated within a session, and its value for "
        "predicting outcome has been shown across thousands of patients [REF]. Any "
        "alternative has to be measured against this, not against nothing.",
    ],
    "intro.esm_lacks": [
        "The limits are just as real. ESM is slow. Each pair of contacts is tested in "
        "turn, and a full map takes hours the patient may not tolerate. Stimulation "
        "triggers afterdischarges and sometimes seizures, which end the session or "
        "invalidate the site [REF]. Only the pairs that were tested are known; "
        "everything else is a gap. The read-out is binary, eloquent or not, with no "
        "measure of how much a site contributes. Task batteries differ between centres "
        "[REF], and whether a pause counts as speech arrest is a judgement call. Some "
        "patients cannot cooperate. Some regions cannot safely be stimulated. Each of "
        "these is a site that goes unmapped, or is mapped wrongly.",
        "Four problems follow the method everywhere. Time: contacts are tested one pair "
        "at a time, and coverage is limited by what the patient can endure. Safety: "
        "current induces afterdischarges and seizures, which cut testing short [REF]. "
        "Resolution: the answer at each site is yes or no, and nothing between. "
        "Consistency: tasks, thresholds and scoring vary between centres and between "
        "examiners [REF]. Together they mean the map is incomplete in a way that is hard "
        "to see, because a site that was never tested looks the same as a site that was "
        "tested and found silent.",
    ],
    "intro.gap": [
        "What a clinician cannot currently get is a complete map of language function, "
        "in every implanted patient, without stimulating. The electrodes are already in "
        "place and the patient is already there for days. A method that read function "
        "from the recording, at every contact at once, would remove the time cost, the "
        "seizure risk and the coverage gaps in one step. That is the gap.",
        "The clinical need is a passive map: function at every implanted contact, from "
        "a task the patient can do in twenty minutes, with no current applied. ESM "
        "cannot provide it and was never designed to. The rest of this paper is about "
        "whether the recorded signal can.",
    ],
    # ---- 3 - passive mapping ---------------------------------------------------
    "intro.passive": [
        "The alternative is to record. The patient performs a language task while the "
        "implanted electrodes capture cortical activity, and the response at each "
        "contact is read out. The signal that carries it is high-frequency broadband "
        "activity, 70 to 150 Hz, which tracks local population firing [REF] and rises "
        "within tens of milliseconds of a stimulus. Every contact is measured at once. "
        "The cost to the patient is the length of the task.",
        "Passive mapping turns the problem around. Instead of disrupting function and "
        "looking for a deficit, it presents a task and looks for a response. In "
        "intracranial recordings that response is a rise in high-gamma power: focal, "
        "time-locked to the event, and a well-established proxy for local neuronal "
        "activity [REF]. The whole array is mapped in one session, with no stimulation "
        "and no induced seizures.",
    ],
    "intro.prior": [
        "The approach is not new. High-gamma responses to language tasks have been "
        "compared with ESM in several cohorts [REF]. The agreement is good but not "
        "complete. Most ESM-positive sites show a high-gamma response, and many "
        "high-gamma sites are ESM-negative. Sensitivity is usually reported above 80% "
        "and specificity lower [REF]. What is accepted is that the recording contains "
        "the information. What is not settled is how to read it.",
        "Passive high-gamma mapping has been tested against ESM in naming, reading and "
        "listening tasks, in adults and in children [REF]. It finds the ESM-positive "
        "sites. It also finds more. Whether the extra sites are false positives or real "
        "function that stimulation missed is still argued [REF]. Some centres now use "
        "it alongside ESM. None uses it instead.",
    ],
    "intro.unresolved": [
        "Three things remain open. First, the threshold. Each study picks its own "
        "criterion for what counts as a response, and the map changes with it. Second, "
        "the summary. Most methods reduce an electrode to one number, a peak or a mean, "
        "and discard the shape of the response in time. Third, the vocabulary. There is "
        "no agreed set of response types that a language electrode can show. Without "
        "one, two studies cannot compare their maps, and a clinician cannot say what "
        "kind of site an electrode is. This paper is about the third problem.",
        "The literature agrees that language cortex responds and disagrees about what a "
        "response is. Definitions vary by study, by task and by frequency band. An "
        "electrode is scored active or not, on one number, and the time course of its "
        "activity is not used. No taxonomy of language responses exists. Whether the "
        "responses fall into a small number of recurring kinds, or lie on a continuum "
        "with no natural joints, has not been asked directly. It is the question this "
        "study asks.",
    ],
    # ---- 4 - our paradigm and paper 1 ------------------------------------------
    "intro.paradigm": [
        "Our paradigm presents language in three forms. The patient listens to speech, "
        "sees a picture to name, or reads a sentence, and after a cue responds. The "
        "three conditions share the output and differ in the input. Auditory "
        "comprehension, object recognition and reading each take a different route into "
        "the same response. Recording all three at the same contacts lets us ask which "
        "responses are modality-specific and which are shared. One condition alone "
        "cannot separate those.",
        "The task has three conditions and one structure: fixation, stimulus, GO cue, "
        "response. In the auditory condition the stimulus is spoken. In the picture "
        "condition it is an image to name. In the reading condition it is a written "
        "sentence. Every trial ends with a response after the cue, so the output stage "
        "is common to all three and the input is what differs. An electrode's profile "
        "across the three conditions becomes a signature: the same in all three, or "
        "different, and if different, how.",
    ],
    "intro.paper1": [
        "In the companion paper [REF] we showed that this task maps language cortex in "
        "the clinical setting. High-gamma responses were found at [n]% of implanted "
        "contacts, agreed with ESM at [x]% of stimulated sites, and were obtained in "
        "[minutes] at the bedside. That paper asked which electrodes respond. It "
        "established the recording as a mapping tool.",
        "The first paper [REF] used this paradigm to identify responsive electrodes and "
        "compared the result with stimulation. It reported [sensitivity] and "
        "[specificity] against ESM, from a fraction of the time. The pipeline, the "
        "cohort and the gating criteria used here come from that work. What it did not "
        "do is look at what the responses were.",
    ],
    "intro.pivot": [
        "Finding a responsive electrode is not the same as knowing what it does. Two "
        "contacts can both pass a threshold and carry different signals: one rising at "
        "the sound of the word, the other only at the onset of speech. The first paper "
        "treated both as language sites. This paper asks whether that is enough. If "
        "responses come in a few distinct kinds, a map that ignores the kind is "
        "discarding the most useful thing in the signal.",
        "The pivot is from where to what. A binary map says which contacts respond. It "
        "does not say whether the response is to the input, to the output, to one "
        "modality or to all three. Those are the distinctions a surgeon would want, and "
        "they are not in the first paper because the first paper did not need them. "
        "Answering the second question takes a different analysis, not a larger version "
        "of the first.",
    ],
    # ---- 5 - the question ------------------------------------------------------
    "intro.q_types": [
        "The central question is whether language responses form a small number of "
        "natural types. We treat this as a hypothesis that can fail. If it is false, "
        "the electrodes will spread along a continuum with no stable structure, "
        "clustering will keep improving as the number of clusters grows, and each "
        "cluster it produces will belong to a single patient. If it is true, a few "
        "clusters will capture the responses, each will draw on many patients, and "
        "adding more will only split them.",
        "We ask a simple question. Across 1693 electrodes from 27 patients, do the "
        "responses repeat? A response type is a temporal profile that many electrodes "
        "share and that is not tied to one person or one implant. The alternative is "
        "that each electrode is its own case. Both outcomes are possible and the "
        "analysis has to be able to return either. A clustering algorithm always "
        "returns clusters. The test is whether they survive.",
    ],
    "intro.q_stable": [
        "A cluster is only a type if it is still there when the analysis changes. We "
        "test that three ways. Across feature representations: the same electrodes "
        "described by high gamma alone, by five frequency bands, or by the full "
        "spectrum. Across algorithms: convex NMF, k-means and hierarchical clustering on "
        "the same features. Across patients: whether each cluster draws on many people "
        "or on one. A type that appears under one setting and vanishes under another is "
        "an artefact of the setting. We spend a full figure on this because the "
        "taxonomy claim rests on it.",
        "Any partition can be produced. The question is which partitions agree. We hold "
        "the electrodes fixed and vary everything else: the features, the algorithm and "
        "the number of clusters. Agreement across those choices is the evidence for a "
        "type, and disagreement the evidence against. We report it per cluster and per "
        "electrode, against chance, and against the ceiling set by how well each method "
        "agrees with itself.",
    ],
    "intro.q_anatomy": [
        "If the types are real, they should sit somewhere. We compare each cluster with "
        "LanA, a probabilistic atlas of language cortex built from fMRI in over 800 "
        "people [REF]. LanA gives the probability that a location is language-responsive "
        "in a typical brain. It is a prior about a place, not a measurement in the "
        "patient. A cluster that concentrates in high-probability cortex sits where "
        "language usually is. A cluster that does not may still be language, in this "
        "patient, at this contact. The comparison can support a type. It cannot refute "
        "one.",
        "We also ask whether the types respect known anatomy. The reference is the LanA "
        "atlas [REF], which assigns each cortical location a probability of belonging "
        "to the language network. This is a group prior, not a per-patient truth. We "
        "test whether any cluster sits in higher-probability cortex than a null that "
        "preserves the spatial structure of the recordings. A negative result is "
        "informative. It means the types are defined by what the electrodes do, not by "
        "where they are.",
    ],
    "intro.q_clinical": [
        "The clinical stake is the gap named above. Today a passive map says active or "
        "silent. If responses come in stable kinds, the map can say which kind: "
        "input-locked, output-locked, modality-specific, suppressed. A surgeon deciding "
        "on a margin would treat those differently. That use is not established by this "
        "paper and we do not claim it. What the paper establishes is whether the kinds "
        "exist and whether they are trustworthy enough to build on.",
        "A taxonomy of responses would change what a passive map can say. It would "
        "separate contacts that respond to hearing from contacts that respond to "
        "speaking, and both from contacts that shut down during the task. Whether that "
        "distinction predicts surgical outcome is a question for a later study. This "
        "one asks the prior question: is there a stable set of types to distinguish at "
        "all.",
    ],
    # ---- 6 - roadmap -----------------------------------------------------------
    "intro.roadmap": [
        "We clustered the responses of 1693 electrodes from 27 patients under three "
        "language conditions. Eight response types were found. We then tested whether "
        "they held when the features, the algorithm and the number of clusters were "
        "changed, and found that some did and some did not. Finally we compared the "
        "types with the LanA atlas and found that none was placed by anatomy. A small "
        "number of response types exist, not all of them generalise, and the ones that "
        "do are defined by what the electrodes do rather than by where they sit.",
        "The paper proceeds in three steps. First we describe the response types that "
        "clustering finds, and show why the number of clusters cannot be chosen by fit "
        "alone. Second we test the types against every analysis choice we could vary, "
        "and report where the agreement is and where it is not. Third we ask whether "
        "the types have an anatomical basis in the language atlas, and find that they "
        "do not. Each step is one figure.",
    ],
    # ---- RESULTS ---------------------------------------------------------------
    "results.cohort": [
        "We recorded from 27 patients implanted with depth electrodes for presurgical "
        "evaluation. After gating for signal quality and cortical location, 1693 "
        "electrodes remained (criteria in STAR Methods). No patient contributes more "
        "than 9.2% of the cohort. Coverage was set by clinical need and is densest in "
        "temporal and frontal cortex, bilaterally. Every result below refers to these "
        "1693 electrodes.",
        "The cohort is 27 patients and 1693 gated electrodes. No patient holds more "
        "than a tenth of the data. Placement followed clinical need, so coverage is "
        "dense in the temporal lobe and sparse elsewhere, and no single patient samples "
        "the whole language network. Each electrode is described by its high-gamma "
        "response in three conditions, time-warped so that the GO cue falls at the same "
        "point in every trial.",
    ],
    "results.f1": [
        "At K = 8, convex NMF separates the electrodes into eight types (Figure 1). The "
        "largest, c1 (n = 436), rises after the GO cue in all three conditions and "
        "returns to baseline before the next trial: a production response, indifferent "
        "to the input. c3 (n = 199) adds a sharp onset at the start of the auditory "
        "block, locked to the sound, and then the same rise at production; it is the "
        "tightest type, with its mean clearing one standard deviation in 28% of time "
        "bins, the most of any cluster. c4 (n = 228) is the inverse: suppression below "
        "baseline during the stimulus in every condition. c5 (n = 162) responds only to "
        "reading and sits mostly on the left (91 electrodes to 53). c2 (n = 185) "
        "responds mainly to the picture. The remaining three, c0, c6 and c7, carry "
        "little signal, and c7 is the one cluster that leans on a single patient.",
        "Eight types emerge and they differ in two ways: when they respond and whether "
        "they care which condition it is. Three are condition-general. c1 responds at "
        "production, c3 at the auditory stimulus and again at production, and c4 is "
        "suppressed during the stimulus. Two are condition-specific: c5 for reading, c2 "
        "for pictures. Three carry little signal. Figure 1 shows each type as its mean "
        "response with one standard deviation, the electrodes that carry it, and the "
        "patients it draws on. The element that recurs is a peak after the GO cue. The "
        "types differ in what happens before it.",
    ],
    "results.f1_k": [
        "Held-out variance, estimated by bi-cross-validation, peaks at K = 11 for high "
        "gamma and at 12 to 14 for the other feature sets (Figure 1A). We do not use "
        "those values. At K = 11, two of eleven clusters draw more than half their "
        "electrodes from one patient; at K = 14 on the five-band features, one cluster "
        "is 75 of a single patient's 77 electrodes. Across feature sets, 15 to 45% of "
        "the electrodes sit in one-patient clusters at the held-out peak (Figure 1D). "
        "Held-out variance cannot see this. Splitting a cohort until each patient has "
        "their own component fits held-out data perfectly well. We cut at K = 8, the "
        "largest K at which no high-gamma cluster is dominated by one patient and at "
        "most one is in any other feature set.",
        "The number of clusters is a choice, and the standard criterion gives the wrong "
        "answer. Bi-cross-validated fit rises to a peak near K = 11 and falls slowly "
        "after (Figure 1A). But the share of electrodes in clusters that belong to one "
        "patient starts rising at K = 9 and reaches 60% by K = 30 (Figure 1D). A "
        "cluster that is one patient's electrode strip explains held-out variance as "
        "well as a real one. It is not a response type. K = 8 is the last value at "
        "which every high-gamma cluster draws on many patients. That is the K we "
        "report, and we show the held-out peak beside it so the reader can see what was "
        "traded.",
    ],
    "results.f2": [
        "Figure 2 asks whether the eight types depend on how the electrodes were "
        "described or on which algorithm was used. Between feature sets, the adjusted "
        "Rand index ranges from 0.16 to 0.53, median 0.31. Between algorithms on the "
        "same features it ranges from 0.16 to 0.45, median 0.18. Per electrode, all "
        "four feature sets agree on the cluster for 21.7% of electrodes, against 0.4% "
        "by chance; all four algorithms agree for 24.7%, against 1.1%. The ceiling "
        "matters. Convex NMF on high gamma agrees with itself, on resamples of the same "
        "data, at a Jaccard of only 0.55. K-means reaches 0.82. No cross-method "
        "agreement can exceed what a method reproduces on its own.",
        "The types are partly stable. Feature sets agree at a median ARI of 0.31 and "
        "algorithms at 0.18, both far above chance and far below 1. Per cluster the "
        "picture is uneven (Figure 2B, E). c3, the auditory type, is recovered by every "
        "feature set and every algorithm. c0, c5 and c7 are missed by at least one. "
        "Several low cells are splits rather than disagreements: the reference cluster "
        "is two clusters in the other solution, which a one-to-one matching scores as a "
        "failure and is not one. Agreement across K peaks at K = 29 for feature sets, "
        "which is where most clusters are one patient. High agreement between two "
        "methods is not evidence of a real type when both have found the same patient.",
    ],
    "results.f2_left": [
        "The agreement figures also say what is not stable. For 4.3% of electrodes no "
        "two feature sets agree on a cluster, and for 10.2% no two algorithms do. These "
        "are not evenly spread. They concentrate in the three weak types, c0, c6 and "
        "c7, and at the borders between the strong ones. Roughly one electrode in five "
        "belongs to a type that every method finds. The rest belong to a type that some "
        "methods find. The taxonomy claim holds for the first group and is provisional "
        "for the second.",
        "Not every electrode has a type. Figure 2C and F colour each electrode by how "
        "many methods place it in the same cluster. About a fifth are placed "
        "identically by all four. A tenth are placed differently by every algorithm. "
        "The unstable electrodes are the weak responders, and the unstable clusters are "
        "the ones with the least signal. This is the expected failure mode and the "
        "honest one. The clustering is uncertain where the data are uncertain, not "
        "where they are clear.",
    ],
    "results.f3": [
        "Figure 3 compares the eight types with the LanA language atlas. 1396 of 1693 "
        "electrodes fall within atlas coverage; the missing 297 are three whole "
        "patients whose scans predate the atlas registration. Ranked by mean LanA "
        "probability, c3 sits highest at 0.226 against a cohort mean of 0.143, and c2 "
        "lowest at 0.101. Against a within-patient permutation, c3 is enriched "
        "(q = 0.008). Against a null that preserves the spatial structure of each "
        "electrode shaft, it is not (q = 0.45), and no cluster is. The correlation "
        "between an electrode's loading on a cluster and its atlas probability is below "
        "|rho| = 0.10 for every type. The clusters are not placed by the atlas.",
        "The atlas comparison is negative, and the reason is instructive. Under a "
        "liberal null that shuffles atlas values within each patient, one cluster, c3, "
        "appears enriched in language cortex. Under a null that shifts labels along "
        "each electrode shaft, keeping neighbouring contacts together, the enrichment "
        "disappears: 0 of 8 clusters pass at q < 0.05. Neighbouring contacts on a shaft "
        "have nearly identical atlas values, so the liberal null inflates every "
        "comparison. The largest correlation between loading and atlas probability is "
        "0.097. At 1396 electrodes a q-value is almost free; the effect size is what "
        "counts, and it is near zero for every type. The response types are defined by "
        "what the electrodes do, not by where the atlas says language should be.",
    ],
}


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------
def examples_html(fid):
    """The two example answers above a box, each with a button that copies it in."""
    ex = EXAMPLES.get(fid)
    if not ex:
        return ""
    items = "".join(
        f'<div class="pf-ex-item"><span class="pf-ex-tag">{tag}</span>'
        f'<p>{esc(t)}</p>'
        f'<button type="button" class="pf-ex-use">Use as draft</button></div>'
        for tag, t in zip("AB", ex))
    return ('<div class="pf-ex"><div class="pf-ex-h">Two ways to answer it'
            '<span>drafts to react to, not text to keep &middot; numbers are from the '
            'current run &middot; [REF] and [brackets] are yours</span></div>'
            + items + '</div>')


def field_html(b):
    fid = b["id"]
    lim = b["limit"]
    limattr = f' data-lim="{lim["n"]}" data-limunit="{lim["unit"]}"' if lim else ""
    if lim:
        hint = (f'<span class="pf-lim" data-for="{esc(fid)}">'
                f'0 / {lim["n"]} {lim["unit"]}</span>')
    else:
        hint = f'<span class="pf-lim" data-for="{esc(fid)}">0 words</span>'
    prompt = (f'<p class="pf-prompt">{b["prompt"]}</p>' if b.get("prompt") else "")
    ph = esc(b.get("ph", ""))
    if b["kind"] == "line":
        box = (f'<input class="pf-in" id="pf-{esc(fid)}" data-pf="{esc(fid)}"'
               f'{limattr} placeholder="{ph}" autocomplete="off">')
    else:
        box = (f'<textarea class="pf-in" id="pf-{esc(fid)}" data-pf="{esc(fid)}"'
               f'{limattr} rows="{b["rows"]}" placeholder="{ph}"></textarea>')
    return (f'<div class="pf-block" data-block="{esc(fid)}">'
            f'<div class="pf-head"><label for="pf-{esc(fid)}">{b["h"]}</label>{hint}</div>'
            f'{prompt}{examples_html(fid)}{box}</div>')


def build():
    nav = (f'{NAV_BEGIN}\n'
           f'    <button class="np" data-t="paper"><span class="dot"></span>'
           f'Paper 2 &middot; manuscript</button>\n    {NAV_END}')

    P = [BEGIN,
         '  <section id="paper">',
         '    <div class="eyebrow">Manuscript</div>',
         '    <h2 class="title">Paper 2 &middot; Cell Reports</h2>',
         '    <p class="lead">A writing scaffold. One subtab per section of a Cell '
         'Reports research article, each holding the questions that section has to '
         'answer and a box to answer them in. Under the Introduction and the three '
         'figure sections, two example answers sit above each box &mdash; drafts to '
         'react to, in the paper&rsquo;s voice, with the current run&rsquo;s numbers. '
         'They are a starting point, not the text.</p>',
         '',
         '    <div class="pf-warn">',
         '      <b>Your writing is saved in this browser only.</b> It is not in git, not '
         'on the other machine, and not visible to anyone you send this page to. '
         '<b>Export it</b> to keep it &mdash; Markdown, copied to the clipboard or '
         'downloaded as a file &mdash; and Import reads an exported file back in. '
         'Clearing site data for this domain erases everything typed here.',
         '      <p style="margin:7px 0 0">Storage is also tied to the <b>address you '
         'open this page from</b>: text typed on <code>lorafanda.github.io</code> will '
         'not appear when you open the local copy of the file, and the reverse. Pick '
         'one and stay on it, or move between them with Export and Import.</p>',
         '      <div class="pf-tools">',
         '        <button class="pf-btn" id="pf-export">Export Markdown</button>',
         '        <button class="pf-btn ghost" id="pf-copy">Copy to clipboard</button>',
         '        <button class="pf-btn ghost" id="pf-import">Import a file</button>',
         '        <input type="file" id="pf-file" accept=".md,.markdown,.txt" hidden>',
         '        <span class="pf-status" id="pf-status">nothing written yet</span>',
         '      </div>',
         '    </div>',
         '',
         '    <div class="pf-bar">']
    for s in SECTIONS:
        P.append(f'      <button data-pt="{s["key"]}">{s["label"]}'
                 f'<span class="pf-count" data-count="{s["key"]}"></span></button>')
    P.append('    </div>')

    for s in SECTIONS:
        P.append(f'\n    <div class="pf-pane" id="pf-pane-{s["key"]}">')
        P.append(f'      <h3 style="margin-top:6px">{s["label"]}'
                 + (f' <span class="pf-tag">{s["tag"]}</span>' if s.get("tag") else "")
                 + '</h3>')
        if s.get("lede"):
            P.append(f'      <p class="pf-lede">{s["lede"]}</p>')
        for b in s["blocks"]:
            if b["kind"] == "group":
                P.append(f'      <div class="pf-group"><h4>{b["h"]}</h4>'
                         + (f'<p>{b["sub"]}</p>' if b.get("sub") else "")
                         + '</div>')
            else:
                P.append("      " + field_html(b))
        P.append('    </div>')

    P.append('  </section>')
    P.append(END)
    return nav, "\n".join(P)


# ---------------------------------------------------------------------------
# the CSS and JS that make it work, spliced into the page's own <style>/<script>
# ---------------------------------------------------------------------------
CSS_BEGIN = "/* BEGIN paper2 css, generated by make_paper_tab.py */"
CSS_END = "/* END paper2 css */"
CSS = CSS_BEGIN + """
  .np .dot{background:#b8336a}
  .pf-warn{background:#fdf7ee;border:1px solid #e8d5b5;border-left:3px solid var(--warn);
    border-radius:0 10px 10px 0;padding:12px 16px;margin:0 0 18px;font-size:13.3px;line-height:1.55}
  .pf-tools{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:11px 0 0}
  .pf-btn{background:var(--accent);color:#fff;border:1px solid var(--accent);font:inherit;
    font-size:12.5px;font-weight:600;padding:6px 13px;border-radius:8px;cursor:pointer}
  .pf-btn:hover{background:var(--accent2);border-color:var(--accent2)}
  .pf-btn.ghost{background:var(--panel);color:var(--accent2);border-color:var(--line)}
  .pf-btn.ghost:hover{background:var(--chip)}
  .pf-status{font-size:12px;color:var(--muted);margin-left:2px}
  .pf-bar{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 18px}
  .pf-bar button{background:#eef2f6;border:1px solid var(--line);border-radius:20px;
    padding:6px 13px;font:inherit;font-size:12.5px;cursor:pointer;color:var(--muted)}
  .pf-bar button:hover{background:#e3eaf1}
  .pf-bar button.on{background:#b8336a;border-color:#b8336a;color:#fff;font-weight:600}
  .pf-count{margin-left:7px;font-size:10.5px;opacity:.75;font-variant-numeric:tabular-nums}
  .pf-pane{display:none} .pf-pane.on{display:block}
  .pf-tag{font-size:11px;font-weight:500;letter-spacing:.3px;text-transform:none;
    color:var(--muted);background:var(--chip);border-radius:999px;padding:2px 9px;margin-left:6px}
  .pf-lede{font-size:13.6px;color:#39434e;margin:0 0 18px;max-width:76ch;line-height:1.6}
  .pf-group{margin:26px 0 10px;padding:0 0 6px;border-bottom:1px solid var(--line)}
  .pf-group h4{margin:0;font-size:14.5px;letter-spacing:-.1px}
  .pf-group p{margin:4px 0 0;font-size:12.5px;color:var(--muted)}
  .pf-block{background:var(--panel);border:1px solid var(--line);border-radius:12px;
    padding:13px 16px 14px;margin:0 0 11px}
  .pf-block.done{border-left:3px solid var(--ok)}
  .pf-head{display:flex;justify-content:space-between;align-items:baseline;gap:12px}
  .pf-head label{font-size:14px;font-weight:600;cursor:pointer}
  .pf-lim{font-size:11px;color:var(--muted);font-variant-numeric:tabular-nums;
    white-space:nowrap;flex:0 0 auto}
  .pf-lim.over{color:var(--stale);font-weight:700}
  .pf-lim.near{color:var(--warn)}
  .pf-prompt{margin:5px 0 9px;font-size:12.9px;color:var(--muted);line-height:1.55;max-width:82ch}
  .pf-in{display:block;width:100%;font:inherit;font-size:14px;line-height:1.6;color:var(--ink);
    background:#fbfcfd;border:1px solid var(--line);border-radius:8px;padding:9px 11px;
    resize:vertical}
  .pf-in:focus{outline:none;border-color:var(--accent);background:var(--panel);
    box-shadow:0 0 0 3px rgba(31,119,180,.10)}
  .pf-in::placeholder{color:#aeb6be}
  .pf-ex{margin:2px 0 10px;padding:9px 12px 4px;background:#f4f6f9;border:1px solid var(--line);
    border-left:3px solid #b8336a;border-radius:0 8px 8px 0}
  .pf-ex-h{font-size:10.5px;font-weight:700;letter-spacing:.7px;text-transform:uppercase;
    color:#b8336a;margin:0 0 4px}
  .pf-ex-h span{font-weight:400;letter-spacing:0;text-transform:none;color:var(--muted);
    margin-left:8px}
  .pf-ex-item{display:grid;grid-template-columns:22px 1fr auto;gap:9px;align-items:start;
    padding:7px 0;border-top:1px solid #e6eaef}
  .pf-ex-h+.pf-ex-item{border-top:0}
  .pf-ex-tag{font-size:11px;font-weight:700;color:#b8336a;background:var(--panel);
    border:1px solid #e8c9d6;border-radius:5px;width:20px;height:20px;display:inline-flex;
    align-items:center;justify-content:center;margin-top:2px}
  .pf-ex-item p{margin:0;font-size:13.2px;line-height:1.58;color:#39434e;max-width:82ch}
  .pf-ex-use{font:inherit;font-size:11.5px;color:var(--accent2);background:var(--panel);
    border:1px solid var(--line);border-radius:6px;padding:3px 9px;cursor:pointer;
    white-space:nowrap;margin-top:1px}
  .pf-ex-use:hover{background:var(--chip)}
  @media(max-width:700px){.pf-ex-item{grid-template-columns:22px 1fr}.pf-ex-use{grid-column:2}}
""" + CSS_END

JS_BEGIN = "// BEGIN paper2 js, generated by make_paper_tab.py"
JS_END = "// END paper2 js"
JS = JS_BEGIN + r"""
(function(){
  const KEY = "fbm.paper2.";
  const boxes = Array.from(document.querySelectorAll(".pf-in[data-pf]"));
  if (!boxes.length) return;
  const status = document.getElementById("pf-status");

  const words = t => (t.trim().match(/\S+/g) || []).length;
  const store = {
    get(id){ try { return localStorage.getItem(KEY + id) || ""; } catch(e){ return ""; } },
    set(id, v){ try { v ? localStorage.setItem(KEY + id, v)
                        : localStorage.removeItem(KEY + id); return true; }
                catch(e){ return false; } }
  };

  function meter(b){
    const t = b.value, lim = b.dataset.lim ? +b.dataset.lim : null;
    const unit = b.dataset.limunit || "words";
    const n = unit === "chars" ? t.length : words(t);
    const el = document.querySelector('.pf-lim[data-for="' + CSS.escape(b.dataset.pf) + '"]');
    if (el){
      el.textContent = lim ? (n + " / " + lim + " " + unit) : (n + " word" + (n===1?"":"s"));
      el.classList.toggle("over", !!lim && n > lim);
      el.classList.toggle("near", !!lim && n <= lim && n > lim * 0.9);
    }
    b.closest(".pf-block").classList.toggle("done", n > 0);
  }

  function counts(){
    let filled = 0, total = boxes.length, w = 0;
    document.querySelectorAll(".pf-pane").forEach(p => {
      const bs = Array.from(p.querySelectorAll(".pf-in[data-pf]"));
      const f = bs.filter(x => x.value.trim()).length;
      const tag = document.querySelector('.pf-count[data-count="' + p.id.slice(8) + '"]');
      if (tag) tag.textContent = f ? f + "/" + bs.length : "";
    });
    boxes.forEach(b => { if (b.value.trim()){ filled++; w += words(b.value); } });
    status.textContent = filled
      ? filled + " of " + total + " sections written · " + w.toLocaleString()
        + " words · saved in this browser"
      : "nothing written yet";
  }

  boxes.forEach(b => {
    b.value = store.get(b.dataset.pf);
    meter(b);
    let t = null;
    b.addEventListener("input", () => {
      meter(b);
      clearTimeout(t);
      t = setTimeout(() => {
        if (!store.set(b.dataset.pf, b.value)) status.textContent =
          "COULD NOT SAVE — this browser is blocking local storage. Export before leaving.";
        else counts();
      }, 250);
    });
  });
  counts();

  // subtabs, with the last one remembered
  const tabs = Array.from(document.querySelectorAll(".pf-bar button[data-pt]"));
  function openPane(k){
    tabs.forEach(x => x.classList.toggle("on", x.dataset.pt === k));
    document.querySelectorAll(".pf-pane").forEach(p =>
      p.classList.toggle("on", p.id === "pf-pane-" + k));
    try { localStorage.setItem(KEY + "_tab", k); } catch(e){}
  }
  tabs.forEach(b => b.onclick = () => openPane(b.dataset.pt));
  let last = ""; try { last = localStorage.getItem(KEY + "_tab") || ""; } catch(e){}
  openPane(tabs.some(t => t.dataset.pt === last) ? last : tabs[0].dataset.pt);

  // "Use as draft": copy an example into its box - never over text already there
  document.querySelectorAll(".pf-ex-use").forEach(btn => btn.onclick = () => {
    const block = btn.closest(".pf-block");
    const box = block && block.querySelector(".pf-in[data-pf]");
    const p = btn.parentElement && btn.parentElement.querySelector("p");
    if (!box || !p) return;
    const t = p.textContent.trim();
    if (box.value.trim() && box.value.trim() !== t){
      if (!confirm("This box already has text.\n\nReplace it with the example?")) return;
    }
    box.value = t;
    box.dispatchEvent(new Event("input", {bubbles: true}));
    box.focus();
  });

  // ---- export / import ----
  function markdown(){
    const out = ["# Paper 2 — manuscript draft", "",
                 "Exported from analysis_status.html. Each block is tagged with its",
                 "field id; Import reads those tags back.", ""];
    document.querySelectorAll(".pf-pane").forEach(p => {
      const h = p.querySelector("h3");
      const bs = Array.from(p.querySelectorAll(".pf-in[data-pf]"))
                      .filter(x => x.value.trim());
      if (!bs.length) return;
      out.push("", "## " + (h ? h.childNodes[0].textContent.trim() : p.id), "");
      bs.forEach(b => {
        const lab = document.querySelector('label[for="' + CSS.escape(b.id) + '"]');
        out.push("### " + (lab ? lab.textContent.trim() : b.dataset.pf));
        out.push("<!-- field: " + b.dataset.pf + " -->");
        out.push("");
        out.push(b.value.trim());
        out.push("");
      });
    });
    return out.join("\n");
  }

  document.getElementById("pf-export").onclick = () => {
    const blob = new Blob([markdown()], {type: "text/markdown;charset=utf-8"});
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "paper2_draft.md";
    document.body.appendChild(a); a.click();
    setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 1000);
  };

  document.getElementById("pf-copy").onclick = async () => {
    const t = markdown();
    try { await navigator.clipboard.writeText(t); status.textContent = "copied to clipboard"; }
    catch(e){
      const ta = document.createElement("textarea");
      ta.value = t; document.body.appendChild(ta); ta.select();
      try { document.execCommand("copy"); status.textContent = "copied to clipboard"; }
      catch(e2){ status.textContent = "could not copy — use Export instead"; }
      ta.remove();
    }
    setTimeout(counts, 2500);
  };

  document.getElementById("pf-import").onclick = () =>
    document.getElementById("pf-file").click();

  document.getElementById("pf-file").onchange = ev => {
    const f = ev.target.files && ev.target.files[0];
    if (!f) return;
    const r = new FileReader();
    r.onload = () => {
      const text = String(r.result).replace(/\r\n/g, "\n");
      const re = /<!--\s*field:\s*([^\s>]+)\s*-->\n([\s\S]*?)(?=\n###\s|\n##\s|$)/g;
      let m, found = 0, skipped = 0;
      while ((m = re.exec(text)) !== null){
        const id = m[1], body = m[2].trim();
        const box = document.querySelector('.pf-in[data-pf="' + CSS.escape(id) + '"]');
        if (!box){ skipped++; continue; }
        // never silently destroy writing that is already here
        if (box.value.trim() && box.value.trim() !== body){
          if (!confirm("\"" + id + "\" already has text here.\n\nReplace it with the "
                       + "imported version?")) continue;
        }
        box.value = body; store.set(id, body); meter(box); found++;
      }
      counts();
      status.textContent = found + " section" + (found===1?"":"s") + " imported"
        + (skipped ? " · " + skipped + " unknown field" + (skipped===1?"":"s")
                     + " ignored" : "");
      ev.target.value = "";
    };
    r.readAsText(f);
  };
})();
""" + JS_END


# ---------------------------------------------------------------------------
def splice(s, begin, end, block, anchor=None, before=True, what=""):
    """Replace a marked block, or insert it relative to `anchor` the first time."""
    if begin in s and end in s:
        i, j = s.index(begin), s.index(end) + len(end)
        return s[:i] + block + s[j:], f"replaced {what}"
    if anchor is None or anchor not in s:
        raise SystemExit(f"anchor for {what} not found - splice by hand this once")
    i = s.index(anchor)
    if before:
        return s[:i] + block + "\n" + s[i:], f"inserted {what}"
    i += len(anchor)
    return s[:i] + "\n" + block + s[i:], f"inserted {what}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--insert", action="store_true", help="write into the site")
    ap.add_argument("--site", default=str(SITE))
    a = ap.parse_args()

    nav, block = build()
    nfields = sum(1 for s in SECTIONS for b in s["blocks"] if b["kind"] != "group")
    ids = [b["id"] for s in SECTIONS for b in s["blocks"] if b["kind"] != "group"]
    dup = {i for i in ids if ids.count(i) > 1}
    if dup:
        raise SystemExit(f"duplicate field ids, which would share one box: {sorted(dup)}")
    # an example keyed to a field that does not exist would silently render nowhere
    orphan = sorted(set(EXAMPLES) - set(ids))
    if orphan:
        raise SystemExit(f"EXAMPLES keyed to fields that do not exist: {orphan}")
    short = sorted(k for k, v in EXAMPLES.items() if len(v) != 2)
    if short:
        raise SystemExit(f"every field needs exactly two examples: {short}")
    nex = sum(len(v) for v in EXAMPLES.values())

    if not a.insert:
        print(block)
        print(f"\n<!-- {len(SECTIONS)} subtabs, {nfields} fields, "
              f"{nex} examples on {len(EXAMPLES)} of them -->")
        print("(pass --insert to splice it into the site)")
        return 0

    site = Path(a.site)
    if not site.exists():
        raise SystemExit(f"no {site}")
    s = site.read_text(encoding="utf-8")

    s, m1 = splice(s, NAV_BEGIN, NAV_END, nav,
                   anchor='    <button class="n5" data-t="caveats"', what="nav button")
    s, m2 = splice(s, BEGIN, END, block,
                   anchor='  <section id="caveats">', what="tab body")
    s, m3 = splice(s, CSS_BEGIN, CSS_END, CSS, anchor="</style>", what="css")
    s, m4 = splice(s, JS_BEGIN, JS_END, JS, anchor="</script>", what="js")

    site.write_text(s, encoding="utf-8")
    for m in (m1, m2, m3, m4):
        print("  " + m)
    print(f"-> {site}  ({len(SECTIONS)} subtabs, {nfields} fields, "
          f"{nex} examples on {len(EXAMPLES)} of them)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
