#!/usr/bin/env python3
"""
retire_sections.py - comment out whole sections of analysis_status.html, reversibly.

    python retire_sections.py --check                     which sections are retired
    python retire_sections.py --apply                     retire the default five
    python retire_sections.py --apply --ids s3 s4         retire some
    python retire_sections.py --restore [--ids ...]       bring them back

WHAT HAPPENS TO A RETIRED SECTION. Its <section> element stays, so its nav button
still works and in-page links into it still land somewhere. Inside it, one visible
line says it is retired and when; below that the ENTIRE original content sits inside
a single HTML comment, untouched byte for byte. Its nav label is struck through and
dimmed. Nothing is deleted.

--restore puts the content and the label back, and the file is then identical to what
it was. The script proves that to itself before it writes: it applies, restores in
memory, and refuses to touch the file unless the round trip is byte-identical.

WHY THIS AND NOT A DELETE. "I don't want to delete anything for now." A section in a
comment is still in git, still in the file, still greppable, and one command away.

THE ONE THING A COMMENT CANNOT HOLD. An HTML comment ends at the first '-->' inside it,
so a section that already contains a comment cannot be wrapped this way. The script
checks and refuses rather than half-hiding. (None of the default five contains one;
the generated blocks with markers all live in sections that stay.)
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

SITE = Path.home() / "lorafanda.github.io" / "analysis_status.html"
DEFAULT_IDS = ["s3", "s4", "s5", "integrity", "clustercmp"]
STAMP = dt.date.today().isoformat()

NOTE = ('<div class="callout retired-note"><b>Retired {stamp}.</b> This section is no '
        'longer maintained. Its content is commented out in the page source &mdash; '
        'nothing was deleted &mdash; and <code>retire_sections.py --restore --ids '
        '{sid}</code> brings it back.</div>')
CSS_BEGIN = "/* BEGIN retired sections css, generated by retire_sections.py */"
CSS_END = "/* END retired sections css */"
CSS = CSS_BEGIN + """
  nav button.retired{opacity:.55}
  nav button.retired.on{opacity:.9}
  nav button.retired s{text-decoration-thickness:1.5px}
  .retired-note{border-left-color:#c0392b;background:#fbe6e3;margin:0 0 14px}
""" + CSS_END


# ---- locating -------------------------------------------------------------------
def section_bounds(s: str, sid: str):
    """(start of inner content, start of '</section>') for one section, or None."""
    m = re.search(r'<section id="' + re.escape(sid) + r'"[^>]*>', s)
    if not m:
        return None
    a = m.end()
    b = s.find("</section>", a)
    if b < 0:
        raise SystemExit(f"{sid}: no closing </section>")
    if "<section" in s[a:b]:
        raise SystemExit(f"{sid}: nested <section> - not handled")
    return a, b


def nav_button(s: str, sid: str):
    return re.search(r'(<button class=")([^"]*)(" data-t="' + re.escape(sid)
                     + r'">\s*<span class="dot"></span>)(.*?)(</button>)', s, re.S)


def is_retired(s: str, sid: str) -> bool:
    ab = section_bounds(s, sid)
    return bool(ab) and f"<!-- RETIRED-BEGIN {sid} " in s[ab[0]:ab[1]]


# ---- the two transforms --------------------------------------------------------------
def apply_one(s: str, sid: str) -> str:
    ab = section_bounds(s, sid)
    if ab is None:
        raise SystemExit(f"no section id={sid!r} in the file")
    a, b = ab
    body = s[a:b]
    if f"<!-- RETIRED-BEGIN {sid} " in body:
        return s                                              # already
    if "-->" in body or "--!>" in body:
        raise SystemExit(f"{sid}: contains an HTML comment end; a comment cannot wrap it")
    new = ("\n    " + NOTE.format(stamp=STAMP, sid=sid)
           + f"\n    <!-- RETIRED-BEGIN {sid} {STAMP}\n" + body
           + f"\nRETIRED-END {sid} -->\n  ")
    s = s[:a] + new + s[b:]
    m = nav_button(s, sid)
    if m and "retired" not in m.group(2).split():
        s = (s[:m.start()] + m.group(1) + m.group(2) + " retired" + m.group(3)
             + "<s>" + m.group(4) + "</s>" + m.group(5) + s[m.end():])
    if CSS_BEGIN not in s:
        i = s.index("</style>")
        s = s[:i] + CSS + "\n" + s[i:]
    return s


def restore_one(s: str, sid: str) -> str:
    ab = section_bounds(s, sid)
    if ab is None:
        raise SystemExit(f"no section id={sid!r} in the file")
    a, b = ab
    inner = s[a:b]
    m = re.fullmatch(r'\n    <div class="callout retired-note">.*?</div>\n    '
                     r'<!-- RETIRED-BEGIN ' + re.escape(sid) + r' \S+\n(.*)\nRETIRED-END '
                     + re.escape(sid) + r' -->\n  ', inner, re.S)
    if not m:
        return s                                              # not retired, or not by us
    s = s[:a] + m.group(1) + s[b:]
    n = nav_button(s, sid)
    if n and "retired" in n.group(2).split():
        cls = " ".join(c for c in n.group(2).split() if c != "retired")
        lab = re.fullmatch(r"<s>(.*)</s>", n.group(4), re.S)
        lab = lab.group(1) if lab else n.group(4)
        s = (s[:n.start()] + n.group(1) + cls + n.group(3) + lab + n.group(5)
             + s[n.end():])
    if "<!-- RETIRED-BEGIN " not in s and CSS_BEGIN in s:
        i, j = s.index(CSS_BEGIN), s.index(CSS_END) + len(CSS_END)
        if s[j:j + 1] == "\n":
            j += 1
        s = s[:i] + s[j:]
    return s


# ---- main -----------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--apply", action="store_true")
    g.add_argument("--restore", action="store_true")
    ap.add_argument("--ids", nargs="+", default=DEFAULT_IDS)
    ap.add_argument("--site", default=str(SITE))
    a = ap.parse_args()

    site = Path(a.site)
    if not site.exists():
        raise SystemExit(f"no {site}")
    s0 = site.read_text(encoding="utf-8")
    for sid in a.ids:
        if section_bounds(s0, sid) is None:
            raise SystemExit(f"no section id={sid!r} in {site.name}")

    if a.check:
        for sid in a.ids:
            ab = section_bounds(s0, sid)
            on = is_retired(s0, sid)
            print(f"  {sid:<11} {'RETIRED' if on else 'live':<8} "
                  f"{ab[1] - ab[0]:>8} chars inside")
        return 0

    s = s0
    if a.apply:
        for sid in a.ids:
            s = apply_one(s, sid)
        if s == s0:
            print("  nothing to do - already retired")
            return 0
        # prove the round trip before writing anything: restoring what we are about
        # to write must give back exactly the file we read
        back = s
        for sid in a.ids:
            back = restore_one(back, sid)
        if back != s0:
            raise SystemExit("round trip is NOT byte-identical - refusing to write")
        changed = [sid for sid in a.ids if not is_retired(s0, sid)]
        what = "retired"
    else:
        for sid in a.ids:
            s = restore_one(s, sid)
        if s == s0:
            print("  nothing to do - not retired")
            return 0
        changed = [sid for sid in a.ids if is_retired(s0, sid)]
        what = "restored"
    site.write_text(s, encoding="utf-8")
    s1 = site.read_text(encoding="utf-8")
    if s1 != s:
        raise SystemExit("read-back differs from what was written - check the file")
    print(f"  {what}: {', '.join(changed)}   ({len(s0):,} -> {len(s):,} chars)")
    print(f"  -> {site}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
